-- | Render a 'DAPackage' to a single self-contained docassemble interview
-- (YAML). Output is built as plain @[Text]@ + 'Text.unlines' (never a @Doc@)
-- so indentation is exact and golden-stable — doubly binding here, because
-- YAML is indentation-sensitive and docassemble splits the file into blocks
-- with a whole-line regex /before/ YAML parsing.
--
-- Emission hygiene (spec R9), all enforced by construction in this module:
--
--   1. Every L4-derived string passes through the one escape function
--      'escapeL4' (Mako @${@, @<%@, @</%@, line-leading @%@ and @##@ — every
--      escape is itself a Mako compile trigger, so the escaped text renders
--      identically whether or not docassemble compiles it), and inline YAML
--      scalars are additionally double-quoted via 'yamlStr'.
--   2. Prose lands only inside block scalars whose every line is indented two
--      spaces ('blockScalar'), so no generated line can ever match
--      docassemble's block-splitting regex @^--- *$@ (@parse.py:138@).
--   3. Top-level keys are lower-case only and drawn from the vendored
--      whitelist 'daRecognisedKeys' — docassemble silently ignores unknown
--      keys, so 'emitterVocabularyViolations' exists for a test to assert
--      empty.
--   4. Every @code:@ block carries a deterministic @id:@, explicit @sets:@,
--      and @depends on:@ over its direct inputs (docassemble variables are
--      otherwise stale-by-default).
--   5. Emitted Python contains no @all([…])@/@any([…])@ list forms (v1 emits
--      no @any@/@all@ at all — @and@/@or@ chains short-circuit natively).
--   6. The mandatory driver is idempotent — pure references and conditionals
--      — and never wraps exceptions; @mandatory:@ is never mixed with
--      @initial:@; every directive block carries @question:@.
module L4.Docassemble.Emit
  ( renderPackage
  , renderPackageTree
  , packageSlug
  , escapeL4
  , emitterKeyVocabulary
  , daRecognisedKeys
  , emitterVocabularyViolations
  ) where

import Base
import Data.Char (isAlphaNum, isAscii, toLower)
import Data.Ratio (denominator, numerator)
import qualified Data.Set as Set
import qualified Data.Text as Text

import L4.Docassemble.IR

renderPackage :: DAPackage -> Text
renderPackage = renderInterview []

-- | The interview, optionally preceded by extra top-level blocks the caller
-- supplies (M2 uses this for the package tree's @modules:@ block, which must
-- NOT appear in the bare artifact: a bare YAML has no package for @.l4runtime@
-- to resolve against, and @from … import *@ of a missing module aborts
-- assembly).
renderInterview :: [[Text]] -> DAPackage -> Text
renderInterview extraBlocks pkg =
  Text.unlines
    ( intercalate ["---"]
        ( firstBlock
            : extraBlocks
           <> glossaryBlocks
           <> featuresBlocks
           <> map blockLines pkg.pkgBlocks ) )
 where
  firstBlock = headerLines pkg <> metadataLines pkg
  glossaryBlocks
    | null pkg.pkgGloss = []
    | otherwise         = [glossaryLines pkg.pkgGloss]
  -- R9.10: emit interview-scale guards when the generated graph could
  -- plausibly approach docassemble's defaults of 500 (parse.py:7942).
  featuresBlocks
    | length pkg.pkgBlocks > 200 =
        [ [ "id: features_main"
          , "features:"
          , "  loop limit: " <> tshow guardLimit
          , "  recursion limit: " <> tshow guardLimit
          ] ]
    | otherwise = []
  guardLimit = max 500 (4 * length pkg.pkgBlocks) :: Int

headerLines :: DAPackage -> [Text]
headerLines pkg =
  [ "# Generated by `l4 docassemble` from " <> pkg.pkgSource <> "."
  , "# Do not edit by hand; regenerate from the L4 source instead."
  , "# Emitted against the docassemble 1.10.7 block-key vocabulary"
  , "# (docassemble_base/docassemble/base/parse.py:1947 at commit 1b6678384)."
  ]

-- | The one documented exception to R9.4's "@id:@ on every block": a
-- @metadata:@ block admits ONLY @metadata@ and @comment@ keys — any other
-- key, @id:@ included, is a hard @DASourceError@ ("A metadata directive
-- cannot be mixed with other directives", @parse.py:2748-2751@ at 1.10.7,
-- re-proven by the round-trip harness when an id was tried). Objects and
-- features blocks carry ids; metadata cannot.
metadataLines :: DAPackage -> [Text]
metadataLines pkg =
  [ "metadata:"
  , "  title: " <> yamlStr (escapeL4 pkg.pkgTitle)
  ]

-- | The @auto terms:@ glossary (M2). Docassemble reads @auto terms@ ONLY from a
-- block that carries no @question@ key —
-- @if \'auto terms\' in data and \'question\' not in data@,
-- @parse.py:2878@ at 1b6678384 — so a glossary emitted inside a question block
-- is silently ignored. This block therefore stands alone.
--
-- Docassemble lower-cases and whitespace-collapses each key
-- (@parse.py:2905-2907@) and compiles it into a case-insensitive
-- @(?i){?\\b(term)\\b}?@ that auto-links the phrase wherever it appears in
-- prose, so the L4 term survives as the user-facing vocabulary. Both halves go
-- through 'escapeL4': each is handed to a 'TextObject' at parse time
-- (@parse.py:2906,2908@), and an unclosed @\<%@ in a @\@desc@ would otherwise
-- fail the whole interview before any question is asked.
glossaryLines :: [(Text, Text)] -> [Text]
glossaryLines entries =
     [ "id: auto_terms_main"
     , "auto terms:"
     ]
  <> [ "  " <> yamlStr (escapeL4 term) <> ": " <> yamlStr (escapeL4 defn)
     | (term, defn) <- entries
     ]

blockLines :: DABlock -> [Text]
blockLines = \case
  DAObjectsBlock entries ->
    "id: objects_main"
      : "objects:" : [ "  - " <> var <> ": " <> cls | (var, cls) <- entries ]
  DAQuestionBlock q -> questionLines q
  DACodeBlock c     -> codeLines c
  DADriverBlock d   -> driverLines d
  DAScreenBlock s   -> screenLines s

-- ---------------------------------------------------------------------------
-- Question blocks (one field per question, R2)
-- ---------------------------------------------------------------------------

questionLines :: DAQuestion -> [Text]
questionLines q =
     [ "id: " <> q.qId
     , "question: |"
     ]
  <> blockScalar (escapeL4 q.qText)
  <> [ "fields:"
     , "  - " <> yamlStr (escapeL4 q.qLabel) <> ": " <> q.qVar
     ]
  <> controlLines q.qControl
  <> [ "    default: " <> defaultScalar d | Just d <- [q.qDefault] ]
  <> [ "    help: " <> yamlStr (escapeL4 h) | Just h <- [q.qHelp] ]

controlLines :: DAFieldControl -> [Text]
controlLines = \case
  CtlYesNoRadio   -> ["    datatype: yesnoradio"]
  CtlYesNoMaybe   -> ["    datatype: yesnomaybe"]
  CtlNumber       -> ["    datatype: number"]
  CtlText         -> ["    datatype: text"]
  CtlTextOptional -> ["    datatype: text", "    required: False"]
  CtlDate         -> ["    datatype: date"]
  CtlRadio choices ->
       [ "    datatype: radio"
       , "    choices:"
       ]
    -- Constructor names ride as verbatim, type-homogeneous strings: a choice
    -- list whose keys were all YAML booleans would be silently retyped
    -- boolean (parse.py:7725), and quoting forecloses that.
    <> [ "      - " <> yamlStr (escapeL4 c) | c <- choices ]

-- | @default:@ is only ever emitted alongside @datatype:@ (a bare default
-- would make docassemble infer the field type from the default's Python
-- type, parse.py:4107).
defaultScalar :: DAExpr -> Text
defaultScalar = \case
  DABoolLit b -> if b then "True" else "False"
  DANum r     -> renderNum r
  DAStrLit t  -> yamlStr (escapeL4 t)
  other       -> yamlStr (renderPyExpr other)  -- unreachable: Lower admits literals only

-- ---------------------------------------------------------------------------
-- Code blocks (R3 survival)
-- ---------------------------------------------------------------------------

codeLines :: DACode -> [Text]
codeLines c =
     [ "id: " <> c.cId
     , "code: |"
     ]
  <> map ("  " <>) (commentL <> pyBody)
  <> depsLines
  <> [ "sets:"
     , "  - " <> c.cVar
     ]
 where
  commentL = [ "# L4: `" <> escapeL4 l4 <> "`" | Just l4 <- [c.cL4] ]
  pyBody = assignment <> citeLines
  assignment = case c.cBody of
    DAAssign e -> [ c.cVar <> " = " <> renderPyExpr e ]
    DAIfChain arms d -> chainLines c.cVar arms d
    DAInstantiate cls ->
      -- instanceName passed explicitly: docassemble otherwise sniffs the
      -- caller's bytecode to recover it, which generated code defeats (R2).
      [ c.cVar <> " = " <> cls <> "(" <> pyStr c.cVar <> ")" ]
  -- M2. `explain` is a docassemble.base.util function, auto-exec'd into every
  -- interview dict unless a `modules:` block names `docassemble.base.util`
  -- itself (parse.py:2765-2767, 8523-8524), which this emitter never does — so
  -- no import is needed. It append-if-absents to
  -- `_internal['explanations']['default']` (util.py:13227), which
  -- `logic_explanation()` reads back (util.py:13259).
  --
  -- The call sits AFTER the assignment on purpose: a code block whose
  -- assignment raises on an undefined input has decided nothing, and
  -- docassemble re-runs the whole block once the input arrives. Citing before
  -- the assignment would record a rule that had not yet fired.
  --
  -- The citation is a Python string literal, not Mako: `code:` blocks are
  -- compiled and exec'd (parse.py:3706), never Mako-rendered, so a citation
  -- beginning with `%` or carrying a literal `${ … }` rides through verbatim.
  citeLines = [ "explain(" <> pyStr cite <> ")" | Just cite <- [c.cCite] ]
  depsLines
    | null c.cDeps = []
    | otherwise    = "depends on:" : [ "  - " <> dep | dep <- c.cDeps ]

chainLines :: Text -> [(DAExpr, DAExpr)] -> DAExpr -> [Text]
chainLines var arms d =
     concat
       [ [ kw <> renderPyExpr cond <> ":"
         , "    " <> var <> " = " <> renderPyExpr val
         ]
       | (kw, (cond, val)) <- zip ("if " : repeat "elif ") arms
       ]
  <> [ "else:"
     , "    " <> var <> " = " <> renderPyExpr d
     ]

-- ---------------------------------------------------------------------------
-- The mandatory driver and terminal screens (R4)
-- ---------------------------------------------------------------------------

driverLines :: DADriver -> [Text]
driverLines = \case
  DASeamDriver did goalL4 scopeV reqV verdictV evC evI evN ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# verdict driver for @export `" <> escapeL4 goalL4 <> "` — scope-first (R4)."
       , "# Never `not scope or requirement`: NotApplicable is not Complies."
       , "if " <> scopeV <> ":"
       , "    if " <> reqV <> ":"
       , "        " <> verdictV <> " = 'Complies'"
       , "        " <> evC
       , "    else:"
       , "        " <> verdictV <> " = 'InBreach'"
       , "        " <> evI
       , "else:"
       , "    " <> verdictV <> " = 'NotApplicable'"
       , "    " <> evN
       ]
    <> [ "sets:"
       , "  - " <> verdictV
       ]
  DABoolDriver did goalL4 goalV evH evF ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# driver for @export `" <> escapeL4 goalL4 <> "`"
       , "if " <> goalV <> ":"
       , "    " <> evH
       , "else:"
       , "    " <> evF
       ]
  DAValueDriver did goalL4 goalV evR ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# driver for @export `" <> escapeL4 goalL4 <> "`"
       , goalV
       , evR
       ]

screenLines :: DAScreen -> [Text]
screenLines s =
     [ "id: " <> s.sId
     , "event: " <> s.sEvent
     , "question: |"
     ]
  <> blockScalar (escapeL4 s.sGoalL4 <> ": " <> s.sVerdict)
  <> [ "subquestion: |" ]
  <> blockScalar subBody
 where
  subBody =
       maybe "" (\d -> escapeL4 d <> "\n\n") s.sDesc
    <> s.sExplain
    <> maybe "" (\v -> "\n\n**${ " <> v <> " }**") s.sShowVar
    <> citationSection
  -- M2. The docassemble house pattern, copied from the canonical exhibit
  -- `docassemble_demo/…/examples/explain.yml` at 1b6678384: a Mako `% for`
  -- over `logic_explanation()`. The control line is legal here because
  -- 'blockScalar' indents every line by exactly two spaces and YAML strips
  -- that indentation, so Mako sees `% for` in column 1.
  --
  -- Rendering rather than inlining is also what makes the R9.1 escaping claim
  -- honest for citations: the citation text is interpolated into the output
  -- stream at render time and is never re-read as Mako, so a `%`-leading or
  -- `${ … }`-bearing citation reaches the screen verbatim.
  citationSection
    | s.sCites =
        "\n\nWhy this answer — the rules that actually decided it:\n\n\
        \% for citation in logic_explanation():\n\
        \* ${ citation }\n\
        \% endfor"
    | otherwise = ""

-- ---------------------------------------------------------------------------
-- Escaping (R9.1) and scalar rendering
-- ---------------------------------------------------------------------------

-- | THE escape function: every L4-derived string passes through here before
-- reaching any Mako-rendered position.
--
-- The invariant is /render-identity under both fates/: docassemble only
-- Mako-compiles a string when @match_mako@ fires (@parse.py:135@:
-- @<%|\\${|% if|% for|% while|##@ — a @TextObject@ without a match keeps the
-- text verbatim), so every escape sequence must itself be a compile trigger
-- and must render back to exactly the original text. Each Mako-significant
-- span is therefore rewritten to the Mako expression that prints it —
-- @${'…'}@ contains @${@, so an escaped string always compiles, and a string
-- we did not touch renders verbatim uncompiled:
--
--   * @${@   → @${'${'}@   (a backslash is NOT an escape in the vendored
--     @docassemble_mako@ — @\\${ x }@ still evaluates @x@; probed at 1.10.7);
--   * @<%@   → @${'<%'}@   (an unclosed @<%@ otherwise fails the WHOLE
--     interview at parse time, and a closed @<%x%>@ span is silently
--     swallowed; a bare @%>@ with no opening tag renders as plain text);
--   * @</%@  → @${'</%'}@  (a closing tag without an opening tag is a
--     @SyntaxException@ under compilation);
--   * line-leading @[ \\t]*%@ → @${'%'}@ for the @%@ (the vendored
--     control-line regex admits leading blanks; the former @%%@ doubling
--     only rendered as @%@ when something ELSE triggered compilation, and
--     otherwise reached the user verbatim as @%%@);
--   * line-leading @[ \\t]*##@ → @${'##'}@ (a compiled line-leading @##@ is
--     a Mako comment: the line would vanish from the prose).
--
-- YAML-significant leaders are neutralised by context: inline scalars go
-- through 'yamlStr' (double-quoted), prose goes through 'blockScalar' (every
-- line indented).
escapeL4 :: Text -> Text
escapeL4 t =
  Text.intercalate "\n"
    (map guardLine (Text.splitOn "\n" spans))
 where
  -- Order matters only in that the replacements must not rescan each
  -- other's output; none of the inserted texts contains a later pattern.
  spans =
      Text.replace "</%" "${'</%'}"
    . Text.replace "<%"  "${'<%'}"
    . Text.replace "${"  "${'${'}"
    $ t
  guardLine ln =
    let (ws, rest) = Text.span (\c -> c == ' ' || c == '\t') ln
    in case () of
         _ | Just rest' <- Text.stripPrefix "##" rest -> ws <> "${'##'}" <> rest'
           | Just rest' <- Text.stripPrefix "%" rest  -> ws <> "${'%'}" <> rest'
           | otherwise                                -> ln

-- | A double-quoted YAML scalar: nothing inside can be misread as YAML
-- syntax, a boolean, or a block-structure leader.
yamlStr :: Text -> Text
yamlStr t = "\"" <> Text.concatMap esc t <> "\""
 where
  esc '"'  = "\\\""
  esc '\\' = "\\\\"
  esc '\n' = "\\n"
  esc ch   = Text.singleton ch

-- | Block-scalar content, every non-empty line indented two spaces so no
-- generated prose line can match docassemble's @^--- *$@ block splitter
-- (R9.7). Empty lines stay empty (blank lines inside a block scalar are
-- legal and cannot match the splitter).
blockScalar :: Text -> [Text]
blockScalar t =
  [ if Text.null ln then "" else "  " <> ln | ln <- Text.splitOn "\n" t ]

-- ---------------------------------------------------------------------------
-- Python expression rendering
-- ---------------------------------------------------------------------------

-- | Fully parenthesised, so Python precedence can never disagree with the
-- L4 AST; operand order is preserved because operand order is question order
-- (CPython short-circuit is the pruner, spec §2).
renderPyExpr :: DAExpr -> Text
renderPyExpr = go
 where
  go = \case
    DANum r      -> renderNum r
    DAStrLit t   -> pyStr t
    DABoolLit b  -> if b then "True" else "False"
    DAVar v      -> v
    DABin op a b -> paren (go a <> " " <> binOp op <> " " <> go b)
    DACmp op a b -> paren (go a <> " " <> cmpOp op <> " " <> go b)
    DAAnd a b    -> paren (go a <> " and " <> go b)
    DAOr a b     -> paren (go a <> " or " <> go b)
    DANot a      -> paren ("not " <> go a)
    DACond c t e -> paren (go t <> " if " <> go c <> " else " <> go e)
    DAIsNone a   -> paren (go a <> " is None")
  binOp = \case
    DAAdd -> "+"; DASub -> "-"; DAMul -> "*"; DADiv -> "/"; DAMod -> "%"
  cmpOp = \case
    DALt -> "<"; DALeq -> "<="; DAGt -> ">"; DAGeq -> ">="; DAEq -> "=="; DANeq -> "!="

paren :: Text -> Text
paren t = "(" <> t <> ")"

-- | A Python single-quoted string literal with minimal escaping.
pyStr :: Text -> Text
pyStr t = "'" <> Text.concatMap esc t <> "'"
 where
  esc '\\' = "\\\\"
  esc '\'' = "\\'"
  esc '\n' = "\\n"
  esc ch   = Text.singleton ch

-- | Render a rational as a clean Python numeric literal (the OpenFisca
-- 'renderNum' discipline): integers print bare; fractions that terminate in
-- base 10 print as decimals; anything else prints as an exact division so no
-- precision is silently lost at emission time.
renderNum :: Rational -> Text
renderNum r
  | d == 1    = sign <> tshow (abs n)
  | otherwise = case terminating (abs n) d of
      Just t  -> sign <> t
      Nothing -> "(" <> tshow n <> " / " <> tshow d <> ")"
 where
  n    = numerator r
  d    = denominator r
  sign = if n < 0 then "-" else ""

terminating :: Integer -> Integer -> Maybe Text
terminating num den =
  let places = countFactors 2 den `max` countFactors 5 den
  in if stripFactors 5 (stripFactors 2 den) == 1
       then Just (format places (num * (10 ^ places) `div` den))
       else Nothing
 where
  countFactors p = goC (0 :: Integer)
    where goC acc y | y `mod` p == 0 && y /= 0 = goC (acc + 1) (y `div` p)
                    | otherwise                = acc
  stripFactors p y | y `mod` p == 0 && y /= 0 = stripFactors p (y `div` p)
                   | otherwise                = y
  format places scaled
    | places == 0 = tshow scaled
    | otherwise =
        let s             = Text.justifyRight (fromIntegral places + 1) '0' (tshow scaled)
            (whole, frac) = Text.splitAt (Text.length s - fromIntegral places) s
        in whole <> "." <> frac

tshow :: Show a => a -> Text
tshow = Text.pack . show

-- ---------------------------------------------------------------------------
-- The installable package tree (R11, M2)
-- ---------------------------------------------------------------------------

-- | The directory (and Python module) name of the generated package, minus the
-- @l4@ prefix: the source file's stem, lower-cased and reduced to ASCII
-- alphanumerics.
--
-- Both obvious sources for this string are unusable, and both were measured:
-- @DAPackage.pkgSource@ is a percent-encoded URI segment (@2024 Café Rules
-- v2.1.l4@ arrives as @2024%20Caf%C3%A9%20Rules%20v2.1.l4@) and the lowerer's
-- @pyIdent@ keeps non-ASCII letters (@café münze 2024@ sanitises to
-- @café_münze_2024@). Neither is a usable on-disk Python package name, so the
-- slug is taken from the file's own basename and hard-filtered here.
--
-- Total: an all-punctuation stem yields @module@, and the result is capped so
-- a pathological filename cannot produce a pathological directory name.
packageSlug :: Text -> Text
packageSlug base =
  let stem    = fromMaybe base (Text.stripSuffix ".l4" base)
      reduced = Text.filter (\c -> isAscii c && isAlphaNum c) (Text.map toLower stem)
  in if Text.null reduced then "module" else Text.take 48 reduced

-- | Lay out the PEP 420 package tree for a lowered interview.
--
-- The exemplar is @docassemble_demo/@ at the 1.10.7 pin: @pyproject.toml@ with
-- @[tool.setuptools.packages.find] where = [\".\"]@, a @MANIFEST.in@ that
-- @graft@s the data directory, an @__init__.py@ inside the generated package —
-- and none at @docassemble/@, because setuptools' pyproject path defaults to
-- PEP 420 namespace finding
-- (@git ls-tree -r 1b6678384 docassemble_demo/ | grep -c
-- \'docassemble_demo/docassemble/__init__.py\'@ ⇒ 0).
--
-- The first argument is the source file's basename as the user spelled it
-- (@citations.l4@), which is the provenance recorded in the generated files;
-- the on-disk copy is renamed to @\<slug\>.l4@ so no space or non-ASCII
-- character rides into a Python package.
renderPackageTree :: Text -> DAPackage -> DAPackageTree
renderPackageTree srcBase pkg = MkDAPackageTree
  { ptDistName   = distName
  , ptFiles =
      [ MkDAFile ["pyproject.toml"] (Text.unlines (pyprojectLines srcBase distName inner))
      , MkDAFile ["MANIFEST.in"]    (Text.unlines (manifestLines inner fidelityName))
      , MkDAFile (inner <> ["__init__.py"]) (Text.unlines initLines)
      , MkDAFile (inner <> ["l4runtime.py"])
          (Text.unlines (runtimeLines srcBase distName slug))
      , MkDAFile (inner <> ["data", "questions", slug <> ".yml"])
          (renderInterview [modulesLines] pkg)
      ]
  , ptSourceCopy = inner <> ["data", "sources", slug <> ".l4"]
  -- The fidelity report sits at the package root under the `-o FILE` sidecar
  -- convention (same stem, `.fidelity.txt`) rather than inside `data/`:
  -- `data/sources` holds the encoding, and the report is documentation OF the
  -- compilation, not interview data. `MANIFEST.in` includes it so it ships.
  , ptFidelity   = [fidelityName]
  }
 where
  slug         = packageSlug srcBase
  distName     = "docassemble.l4" <> slug
  inner        = ["docassemble", "l4" <> slug]
  fidelityName = slug <> ".fidelity.txt"

-- | R11: the runtime module is a /sibling/ of @data\/@, loaded as
-- @.l4runtime@. The leading dot is package-name concatenation, one level only:
-- docassemble execs @from \<question.package\>.l4runtime import *@
-- (@parse.py:8569-8573@ at 1b6678384).
--
-- This block is emitted into the packaged interview ONLY. Naming
-- @docassemble.base.util@ or @docassemble.base.legal@ here would suppress the
-- automatic @from docassemble.base.util import *@ (@parse.py:2765-2767@ read
-- at @:8523@) and take @explain@, @DAObject@ and every other builtin with it —
-- which is why the module list holds exactly one relative name.
modulesLines :: [Text]
modulesLines =
  [ "id: modules_main"
  , "modules:"
  , "  - .l4runtime"
  ]

pyprojectLines :: Text -> Text -> [Text] -> [Text]
pyprojectLines srcBase distName inner =
  [ "# Generated by `l4 docassemble --package` from `" <> srcBase <> "`."
  , "# Do not edit by hand; regenerate from the L4 source instead."
  , "# Shape: the modern PEP 420 package, exemplar docassemble_demo/pyproject.toml"
  , "# at docassemble 1.10.7 (checkout commit 1b6678384)."
  , ""
  , "[build-system]"
  , "requires = [\"setuptools >= 61.0\"]"
  , "build-backend = \"setuptools.build_meta\""
  , ""
  , "[project]"
  , "name = " <> tomlStr distName
  , "version = \"0.0.1\""
  , "description = " <> tomlStr ("docassemble interview compiled from the L4 module `" <> srcBase <> "`")
  -- PEP 639 wants an SPDX expression, and docassemble has required one of
  -- Playground packages since 1.8.0. This package carries the USER's rules,
  -- whose licence the compiler cannot know, so it emits a LicenseRef- custom
  -- identifier — valid SPDX, and unmistakably a placeholder — rather than
  -- asserting a licence over someone else's law.
  , "# Replace this with the SPDX expression that governs your own rules."
  , "license = \"LicenseRef-UNSPECIFIED\""
  , "requires-python = \">= 3.12\"   # docassemble_base/pyproject.toml:14 at 1b6678384"
  , "dependencies = ["
  , "  \"docassemble.base >= 1.10.0\","
  , "]"
  , ""
  , "[tool.setuptools.packages.find]"
  , "where = [\".\"]"
  , "# No docassemble/__init__.py is emitted: with this pyproject shape"
  , "# setuptools uses PEP 420 namespace finding, and a namespace __init__.py"
  , "# would shadow the installed docassemble.base."
  , "# Generated package directory: " <> Text.intercalate "/" inner
  ]

manifestLines :: [Text] -> Text -> [Text]
manifestLines inner fidelityName =
  [ "# Generated by `l4 docassemble --package`; do not edit by hand."
  , "graft " <> Text.intercalate "/" inner <> "/data"
  , "include " <> fidelityName
  , "recursive-exclude * __pycache__"
  , "recursive-exclude * *.py[co]"
  ]

-- | Copied in shape from @docassemble_demo/docassemble/demo/__init__.py@ at
-- 1b6678384, whose entire contents are the comment and the version.
initLines :: [Text]
initLines =
  [ "# do not pre-load"
  , "__version__ = \"0.0.1\""
  ]

-- | The generated runtime module. It deliberately defines no interview
-- variable and no helper the emitted @code:@ blocks call: the bare artifact and
-- the packaged artifact must mean the same thing, so anything the interview
-- /needs/ would have to work bare too. What it does carry is provenance the
-- interview can show about itself, under an explicit @__all__@ so
-- @modules:@' @import *@ cannot collide with an interview variable.
runtimeLines :: Text -> Text -> Text -> [Text]
runtimeLines srcBase distName slug =
  [ "\"\"\"Runtime module for " <> distName <> ", generated by `l4 docassemble --package`."
  , ""
  , "Loaded by the interview's `modules:` block as `.l4runtime`, which"
  , "docassemble execs as `from " <> distName <> ".l4runtime import *`"
  , "(parse.py:8569-8573 at 1b6678384)."
  , ""
  , "Do not edit by hand; regenerate from the L4 source instead."
  , "\"\"\""
  , ""
  , "import os"
  , ""
  , "__all__ = ["
  , "    'L4_SOURCE_NAME',"
  , "    'L4_PACKAGE_NAME',"
  , "    'L4_GENERATOR',"
  , "    'L4_DOCASSEMBLE_PIN',"
  , "    'l4_source_path',"
  , "    'l4_source_text',"
  , "]"
  , ""
  , "#: the L4 source file this interview was compiled from, as the author spelled it"
  , "L4_SOURCE_NAME = " <> pyStr srcBase
  , "L4_PACKAGE_NAME = " <> pyStr distName
  , "L4_GENERATOR = 'l4 docassemble --package'"
  , "L4_DOCASSEMBLE_PIN = '1.10.7'"
  , ""
  , ""
  , "def l4_source_path():"
  , "    \"\"\"Absolute path of the embedded L4 source (provenance travels with the package).\"\"\""
  , "    return os.path.join(os.path.dirname(os.path.abspath(__file__)),"
  , "                        'data', 'sources', " <> pyStr (slug <> ".l4") <> ")"
  , ""
  , ""
  , "def l4_source_text():"
  , "    \"\"\"The embedded L4 source, verbatim.\"\"\""
  , "    with open(l4_source_path(), encoding='utf-8') as handle:"
  , "        return handle.read()"
  ]

-- | A TOML basic string.
tomlStr :: Text -> Text
tomlStr t = "\"" <> Text.concatMap esc t <> "\""
 where
  esc '"'  = "\\\""
  esc '\\' = "\\\\"
  esc '\n' = "\\n"
  esc ch   = Text.singleton ch

-- ---------------------------------------------------------------------------
-- Vocabulary self-validation (R9.5)
-- ---------------------------------------------------------------------------

-- | Every YAML key this emitter can write: the top-level block keys plus the
-- per-field modifiers. A golden/unit check asserts this is a subset of
-- 'daRecognisedKeys', because docassemble /silently ignores/ an unknown
-- top-level key (logged only under debug) and silently turns an unknown
-- field modifier into the field's label.
emitterKeyVocabulary :: [Text]
emitterKeyVocabulary =
  -- top-level block keys
  [ "auto terms", "code", "depends on", "event", "features", "fields", "id"
  , "mandatory", "metadata", "modules", "objects", "question", "sets"
  , "subquestion"
  -- field modifiers
  , "choices", "datatype", "default", "help", "required"
  ]

-- | The recognised-key whitelist, vendored verbatim from docassemble 1.10.7:
-- the tuple tested at @docassemble_base/docassemble/base/parse.py:1947@
-- (checkout commit @1b6678384@, read 2026-08-16), deduplicated. No runtime
-- dependency on the docassemble tree: local evidence, never a build dep.
daRecognisedKeys :: Set Text
daRecognisedKeys = Set.fromList
  [ "features", "scan for variables", "only sets", "question", "code", "event"
  , "translations", "default language", "on change", "sections", "progressive"
  , "auto open", "section", "machine learning storage", "language"
  , "prevent going back", "back button", "usedefs", "continue button label"
  , "continue button color", "resume button label", "resume button color"
  , "back button label", "corner back button label", "skip undefined"
  , "list collect", "mandatory", "attachment options", "script", "css"
  , "initial", "default role", "command", "objects from file", "use objects"
  , "data", "variable name", "data from code", "objects", "id", "ga id"
  , "segment id", "segment", "supersedes", "order", "image sets", "images"
  , "def", "mako", "interview help", "default screen parts"
  , "default validation messages", "generic object", "generic list object"
  , "comment", "metadata", "modules", "reset", "imports", "terms", "auto terms"
  , "role", "include", "action buttons", "if", "validation code", "require"
  , "orelse", "attachment", "attachments", "attachment code", "attachments code"
  , "allow emailing", "allow downloading", "email subject", "email body"
  , "email template", "email address default", "progress", "zip filename"
  , "action", "backgroundresponse", "response", "binaryresponse"
  , "all_variables", "response filename", "content type", "redirect url"
  , "null response", "sleep", "include_internal", "css class"
  , "table css class", "response code", "subquestion", "reload", "help"
  , "audio", "video", "decoration", "signature", "under", "pre", "post"
  , "right", "submit", "check in", "yesno", "noyes", "yesnomaybe", "noyesmaybe"
  , "sets", "choices", "buttons", "dropdown", "combobox", "field", "shuffle"
  , "review", "need", "depends on", "target", "table", "rows", "columns"
  , "require gathered", "allow reordering", "edit", "delete buttons", "confirm"
  , "read only", "edit header", "show if empty", "template", "content file"
  , "content", "subject", "reconsider", "undefine", "continue button field"
  , "fields", "indent", "url", "default", "datatype", "extras"
  , "allowed to set", "show incomplete", "not available label", "required"
  , "always include editable files", "question metadata"
  , "include attachment notice", "include download tab", "describe file types"
  , "manual attachment list", "breadcrumb", "tabular", "hide continue button"
  , "disable continue button", "pen color", "gathered", "sort key"
  , "sort reverse", "filter", "flattened checkbox label"
  , "flattened checkbox unselected label"
  ]

-- | Keys the emitter writes that docassemble 1.10.7 would silently ignore.
-- Must be empty; asserted by the vocabulary check in the test suite.
emitterVocabularyViolations :: [Text]
emitterVocabularyViolations =
  [ k | k <- emitterKeyVocabulary, not (k `Set.member` daRecognisedKeys) ]
