-- | Render a 'DAPackage' to a single self-contained docassemble interview
-- (YAML). Output is built as plain @[Text]@ + 'Text.unlines' (never a @Doc@)
-- so indentation is exact and golden-stable — doubly binding here, because
-- YAML is indentation-sensitive and docassemble splits the file into blocks
-- with a whole-line regex /before/ YAML parsing.
--
-- Emission hygiene (spec R9), all enforced by construction in this module:
--
--   1. Every L4-derived string passes through the one escape function
--      'escapeL4' (Mako @${@ and line-leading @%@), and inline YAML scalars
--      are additionally double-quoted via 'yamlStr'.
--   2. Prose lands only inside block scalars whose every line is indented two
--      spaces ('blockScalar'), so no generated line can ever match
--      docassemble's block-splitting regex @^--- *$@ (@parse.py:138@).
--   3. Top-level keys are lower-case only and drawn from the vendored
--      whitelist 'daRecognisedKeys' — docassemble silently ignores unknown
--      keys, so 'emitterVocabularyViolations' exists for a test to assert
--      empty.
--   4. Every @code:@ block carries a deterministic @id:@, explicit @sets:@,
--      and @depends on:@ over its direct inputs (docassemble variables are
--      otherwise stale-by-default).
--   5. Emitted Python contains no @all([…])@/@any([…])@ list forms (v1 emits
--      no @any@/@all@ at all — @and@/@or@ chains short-circuit natively).
--   6. The mandatory driver is idempotent — pure references and conditionals
--      — and never wraps exceptions; @mandatory:@ is never mixed with
--      @initial:@; every directive block carries @question:@.
module L4.Docassemble.Emit
  ( renderPackage
  , escapeL4
  , emitterKeyVocabulary
  , daRecognisedKeys
  , emitterVocabularyViolations
  ) where

import Base
import Data.Ratio (denominator, numerator)
import qualified Data.Set as Set
import qualified Data.Text as Text

import L4.Docassemble.IR

renderPackage :: DAPackage -> Text
renderPackage pkg =
  Text.unlines (intercalate ["---"] (firstBlock : featuresBlocks <> map blockLines pkg.pkgBlocks))
 where
  firstBlock = headerLines pkg <> metadataLines pkg
  -- R9.10: emit interview-scale guards when the generated graph could
  -- plausibly approach docassemble's defaults of 500 (parse.py:7942).
  featuresBlocks
    | length pkg.pkgBlocks > 200 =
        [ [ "features:"
          , "  loop limit: " <> tshow guardLimit
          , "  recursion limit: " <> tshow guardLimit
          ] ]
    | otherwise = []
  guardLimit = max 500 (4 * length pkg.pkgBlocks) :: Int

headerLines :: DAPackage -> [Text]
headerLines pkg =
  [ "# Generated by `l4 docassemble` from " <> pkg.pkgSource <> "."
  , "# Do not edit by hand; regenerate from the L4 source instead."
  , "# Emitted against the docassemble 1.10.7 block-key vocabulary"
  , "# (docassemble_base/docassemble/base/parse.py:1947 at commit 1b6678384)."
  ]

metadataLines :: DAPackage -> [Text]
metadataLines pkg =
  [ "metadata:"
  , "  title: " <> yamlStr (escapeL4 pkg.pkgTitle)
  ]

blockLines :: DABlock -> [Text]
blockLines = \case
  DAObjectsBlock entries ->
    "objects:" : [ "  - " <> var <> ": " <> cls | (var, cls) <- entries ]
  DAQuestionBlock q -> questionLines q
  DACodeBlock c     -> codeLines c
  DADriverBlock d   -> driverLines d
  DAScreenBlock s   -> screenLines s

-- ---------------------------------------------------------------------------
-- Question blocks (one field per question, R2)
-- ---------------------------------------------------------------------------

questionLines :: DAQuestion -> [Text]
questionLines q =
     [ "id: " <> q.qId
     , "question: |"
     ]
  <> blockScalar (escapeL4 q.qText)
  <> [ "fields:"
     , "  - " <> yamlStr (escapeL4 q.qLabel) <> ": " <> q.qVar
     ]
  <> controlLines q.qControl
  <> [ "    default: " <> defaultScalar d | Just d <- [q.qDefault] ]
  <> [ "    help: " <> yamlStr (escapeL4 h) | Just h <- [q.qHelp] ]

controlLines :: DAFieldControl -> [Text]
controlLines = \case
  CtlYesNoRadio   -> ["    datatype: yesnoradio"]
  CtlYesNoMaybe   -> ["    datatype: yesnomaybe"]
  CtlNumber       -> ["    datatype: number"]
  CtlText         -> ["    datatype: text"]
  CtlTextOptional -> ["    datatype: text", "    required: False"]
  CtlDate         -> ["    datatype: date"]
  CtlRadio choices ->
       [ "    datatype: radio"
       , "    choices:"
       ]
    -- Constructor names ride as verbatim, type-homogeneous strings: a choice
    -- list whose keys were all YAML booleans would be silently retyped
    -- boolean (parse.py:7725), and quoting forecloses that.
    <> [ "      - " <> yamlStr (escapeL4 c) | c <- choices ]

-- | @default:@ is only ever emitted alongside @datatype:@ (a bare default
-- would make docassemble infer the field type from the default's Python
-- type, parse.py:4107).
defaultScalar :: DAExpr -> Text
defaultScalar = \case
  DABoolLit b -> if b then "True" else "False"
  DANum r     -> renderNum r
  DAStrLit t  -> yamlStr (escapeL4 t)
  other       -> yamlStr (renderPyExpr other)  -- unreachable: Lower admits literals only

-- ---------------------------------------------------------------------------
-- Code blocks (R3 survival)
-- ---------------------------------------------------------------------------

codeLines :: DACode -> [Text]
codeLines c =
     [ "id: " <> c.cId
     , "code: |"
     ]
  <> map ("  " <>) (commentL <> pyBody)
  <> depsLines
  <> [ "sets:"
     , "  - " <> c.cVar
     ]
 where
  commentL = [ "# L4: `" <> escapeL4 l4 <> "`" | Just l4 <- [c.cL4] ]
  pyBody = case c.cBody of
    DAAssign e -> [ c.cVar <> " = " <> renderPyExpr e ]
    DAIfChain arms d -> chainLines c.cVar arms d
    DAInstantiate cls ->
      -- instanceName passed explicitly: docassemble otherwise sniffs the
      -- caller's bytecode to recover it, which generated code defeats (R2).
      [ c.cVar <> " = " <> cls <> "(" <> pyStr c.cVar <> ")" ]
  depsLines
    | null c.cDeps = []
    | otherwise    = "depends on:" : [ "  - " <> dep | dep <- c.cDeps ]

chainLines :: Text -> [(DAExpr, DAExpr)] -> DAExpr -> [Text]
chainLines var arms d =
     concat
       [ [ kw <> renderPyExpr cond <> ":"
         , "    " <> var <> " = " <> renderPyExpr val
         ]
       | (kw, (cond, val)) <- zip ("if " : repeat "elif ") arms
       ]
  <> [ "else:"
     , "    " <> var <> " = " <> renderPyExpr d
     ]

-- ---------------------------------------------------------------------------
-- The mandatory driver and terminal screens (R4)
-- ---------------------------------------------------------------------------

driverLines :: DADriver -> [Text]
driverLines = \case
  DASeamDriver did goalL4 scopeV reqV verdictV evC evI evN ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# verdict driver for @export `" <> escapeL4 goalL4 <> "` — scope-first (R4)."
       , "# Never `not scope or requirement`: NotApplicable is not Complies."
       , "if " <> scopeV <> ":"
       , "    if " <> reqV <> ":"
       , "        " <> verdictV <> " = 'Complies'"
       , "        " <> evC
       , "    else:"
       , "        " <> verdictV <> " = 'InBreach'"
       , "        " <> evI
       , "else:"
       , "    " <> verdictV <> " = 'NotApplicable'"
       , "    " <> evN
       ]
    <> [ "sets:"
       , "  - " <> verdictV
       ]
  DABoolDriver did goalL4 goalV evH evF ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# driver for @export `" <> escapeL4 goalL4 <> "`"
       , "if " <> goalV <> ":"
       , "    " <> evH
       , "else:"
       , "    " <> evF
       ]
  DAValueDriver did goalL4 goalV evR ->
       [ "id: " <> did
       , "mandatory: True"
       , "code: |"
       ]
    <> map ("  " <>)
       [ "# driver for @export `" <> escapeL4 goalL4 <> "`"
       , goalV
       , evR
       ]

screenLines :: DAScreen -> [Text]
screenLines s =
     [ "id: " <> s.sId
     , "event: " <> s.sEvent
     , "question: |"
     ]
  <> blockScalar (escapeL4 s.sGoalL4 <> ": " <> s.sVerdict)
  <> [ "subquestion: |" ]
  <> blockScalar subBody
 where
  subBody =
       maybe "" (\d -> escapeL4 d <> "\n\n") s.sDesc
    <> s.sExplain
    <> maybe "" (\v -> "\n\n**${ " <> v <> " }**") s.sShowVar

-- ---------------------------------------------------------------------------
-- Escaping (R9.1) and scalar rendering
-- ---------------------------------------------------------------------------

-- | THE escape function: every L4-derived string passes through here before
-- reaching any Mako-rendered position. @${@ becomes @${'${'}@ — the Mako
-- expression that renders a literal @${@; a backslash (@\\${@) is NOT an
-- escape in the vendored @docassemble_mako@ and still evaluates the
-- expression (probed against 1.10.7 in this repo's round-trip venv). A
-- line-leading @%@ is doubled (the control-line escape, which does render
-- a literal @%@). YAML-significant leaders are neutralised by context:
-- inline scalars go through 'yamlStr' (double-quoted), prose goes through
-- 'blockScalar' (every line indented).
escapeL4 :: Text -> Text
escapeL4 t =
  Text.intercalate "\n"
    (map guardLine (Text.splitOn "\n" (Text.replace "${" "${'${'}" t)))
 where
  guardLine ln
    | "%" `Text.isPrefixOf` ln = "%" <> ln
    | otherwise                = ln

-- | A double-quoted YAML scalar: nothing inside can be misread as YAML
-- syntax, a boolean, or a block-structure leader.
yamlStr :: Text -> Text
yamlStr t = "\"" <> Text.concatMap esc t <> "\""
 where
  esc '"'  = "\\\""
  esc '\\' = "\\\\"
  esc '\n' = "\\n"
  esc ch   = Text.singleton ch

-- | Block-scalar content, every non-empty line indented two spaces so no
-- generated prose line can match docassemble's @^--- *$@ block splitter
-- (R9.7). Empty lines stay empty (blank lines inside a block scalar are
-- legal and cannot match the splitter).
blockScalar :: Text -> [Text]
blockScalar t =
  [ if Text.null ln then "" else "  " <> ln | ln <- Text.splitOn "\n" t ]

-- ---------------------------------------------------------------------------
-- Python expression rendering
-- ---------------------------------------------------------------------------

-- | Fully parenthesised, so Python precedence can never disagree with the
-- L4 AST; operand order is preserved because operand order is question order
-- (CPython short-circuit is the pruner, spec §2).
renderPyExpr :: DAExpr -> Text
renderPyExpr = go
 where
  go = \case
    DANum r      -> renderNum r
    DAStrLit t   -> pyStr t
    DABoolLit b  -> if b then "True" else "False"
    DAVar v      -> v
    DABin op a b -> paren (go a <> " " <> binOp op <> " " <> go b)
    DACmp op a b -> paren (go a <> " " <> cmpOp op <> " " <> go b)
    DAAnd a b    -> paren (go a <> " and " <> go b)
    DAOr a b     -> paren (go a <> " or " <> go b)
    DANot a      -> paren ("not " <> go a)
    DACond c t e -> paren (go t <> " if " <> go c <> " else " <> go e)
    DAIsNone a   -> paren (go a <> " is None")
  binOp = \case
    DAAdd -> "+"; DASub -> "-"; DAMul -> "*"; DADiv -> "/"; DAMod -> "%"
  cmpOp = \case
    DALt -> "<"; DALeq -> "<="; DAGt -> ">"; DAGeq -> ">="; DAEq -> "=="; DANeq -> "!="

paren :: Text -> Text
paren t = "(" <> t <> ")"

-- | A Python single-quoted string literal with minimal escaping.
pyStr :: Text -> Text
pyStr t = "'" <> Text.concatMap esc t <> "'"
 where
  esc '\\' = "\\\\"
  esc '\'' = "\\'"
  esc '\n' = "\\n"
  esc ch   = Text.singleton ch

-- | Render a rational as a clean Python numeric literal (the OpenFisca
-- 'renderNum' discipline): integers print bare; fractions that terminate in
-- base 10 print as decimals; anything else prints as an exact division so no
-- precision is silently lost at emission time.
renderNum :: Rational -> Text
renderNum r
  | d == 1    = sign <> tshow (abs n)
  | otherwise = case terminating (abs n) d of
      Just t  -> sign <> t
      Nothing -> "(" <> tshow n <> " / " <> tshow d <> ")"
 where
  n    = numerator r
  d    = denominator r
  sign = if n < 0 then "-" else ""

terminating :: Integer -> Integer -> Maybe Text
terminating num den =
  let places = countFactors 2 den `max` countFactors 5 den
  in if stripFactors 5 (stripFactors 2 den) == 1
       then Just (format places (num * (10 ^ places) `div` den))
       else Nothing
 where
  countFactors p = goC (0 :: Integer)
    where goC acc y | y `mod` p == 0 && y /= 0 = goC (acc + 1) (y `div` p)
                    | otherwise                = acc
  stripFactors p y | y `mod` p == 0 && y /= 0 = stripFactors p (y `div` p)
                   | otherwise                = y
  format places scaled
    | places == 0 = tshow scaled
    | otherwise =
        let s             = Text.justifyRight (fromIntegral places + 1) '0' (tshow scaled)
            (whole, frac) = Text.splitAt (Text.length s - fromIntegral places) s
        in whole <> "." <> frac

tshow :: Show a => a -> Text
tshow = Text.pack . show

-- ---------------------------------------------------------------------------
-- Vocabulary self-validation (R9.5)
-- ---------------------------------------------------------------------------

-- | Every YAML key this emitter can write: the top-level block keys plus the
-- per-field modifiers. A golden/unit check asserts this is a subset of
-- 'daRecognisedKeys', because docassemble /silently ignores/ an unknown
-- top-level key (logged only under debug) and silently turns an unknown
-- field modifier into the field's label.
emitterKeyVocabulary :: [Text]
emitterKeyVocabulary =
  -- top-level block keys
  [ "code", "depends on", "event", "features", "fields", "id", "mandatory"
  , "metadata", "objects", "question", "sets", "subquestion"
  -- field modifiers
  , "choices", "datatype", "default", "help", "required"
  ]

-- | The recognised-key whitelist, vendored verbatim from docassemble 1.10.7:
-- the tuple tested at @docassemble_base/docassemble/base/parse.py:1947@
-- (checkout commit @1b6678384@, read 2026-08-16), deduplicated. No runtime
-- dependency on the docassemble tree: local evidence, never a build dep.
daRecognisedKeys :: Set Text
daRecognisedKeys = Set.fromList
  [ "features", "scan for variables", "only sets", "question", "code", "event"
  , "translations", "default language", "on change", "sections", "progressive"
  , "auto open", "section", "machine learning storage", "language"
  , "prevent going back", "back button", "usedefs", "continue button label"
  , "continue button color", "resume button label", "resume button color"
  , "back button label", "corner back button label", "skip undefined"
  , "list collect", "mandatory", "attachment options", "script", "css"
  , "initial", "default role", "command", "objects from file", "use objects"
  , "data", "variable name", "data from code", "objects", "id", "ga id"
  , "segment id", "segment", "supersedes", "order", "image sets", "images"
  , "def", "mako", "interview help", "default screen parts"
  , "default validation messages", "generic object", "generic list object"
  , "comment", "metadata", "modules", "reset", "imports", "terms", "auto terms"
  , "role", "include", "action buttons", "if", "validation code", "require"
  , "orelse", "attachment", "attachments", "attachment code", "attachments code"
  , "allow emailing", "allow downloading", "email subject", "email body"
  , "email template", "email address default", "progress", "zip filename"
  , "action", "backgroundresponse", "response", "binaryresponse"
  , "all_variables", "response filename", "content type", "redirect url"
  , "null response", "sleep", "include_internal", "css class"
  , "table css class", "response code", "subquestion", "reload", "help"
  , "audio", "video", "decoration", "signature", "under", "pre", "post"
  , "right", "submit", "check in", "yesno", "noyes", "yesnomaybe", "noyesmaybe"
  , "sets", "choices", "buttons", "dropdown", "combobox", "field", "shuffle"
  , "review", "need", "depends on", "target", "table", "rows", "columns"
  , "require gathered", "allow reordering", "edit", "delete buttons", "confirm"
  , "read only", "edit header", "show if empty", "template", "content file"
  , "content", "subject", "reconsider", "undefine", "continue button field"
  , "fields", "indent", "url", "default", "datatype", "extras"
  , "allowed to set", "show incomplete", "not available label", "required"
  , "always include editable files", "question metadata"
  , "include attachment notice", "include download tab", "describe file types"
  , "manual attachment list", "breadcrumb", "tabular", "hide continue button"
  , "disable continue button", "pen color", "gathered", "sort key"
  , "sort reverse", "filter", "flattened checkbox label"
  , "flattened checkbox unselected label"
  ]

-- | Keys the emitter writes that docassemble 1.10.7 would silently ignore.
-- Must be empty; asserted by the vocabulary check in the test suite.
emitterVocabularyViolations :: [Text]
emitterVocabularyViolations =
  [ k | k <- emitterKeyVocabulary, not (k `Set.member` daRecognisedKeys) ]
