% generated by l4 blawx from benefit.l4 — raw concatenated s(CASP); tests live in the .blawx / tier-1 harness
% epistemics (R5): an input that is neither asserted, denied, nor abducible yields NO MODEL (loud), never a silent false

blawx_category(applicant).
blawx_category_nlg(applicant,"","is an applicant").
:- dynamic applicant/1.
#pred applicant(X) :: '@(X) is an applicant'.
#pred holds(user,applicant,X) :: 'it is provided as a fact that @(X) is an applicant'.
#pred holds(user,-applicant,X) :: 'it is provided as a fact that it is not the case that @(X) is an applicant'.
#pred holds(Z,applicant,X) :: 'the conclusion in @(Z) that @(X) is an applicant holds'.
#pred holds(Z,-applicant,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is an applicant holds'.
#pred according_to(Z,applicant,X) :: 'according to @(Z), @(X) is an applicant'.
#pred according_to(Z,-applicant,X) :: 'according to @(Z), it is not the case that @(X) is an applicant'.
#pred blawx_defeated(Z,applicant,X) :: 'the conclusion in @(Z) that @(X) is an applicant is defeated'.
#pred blawx_defeated(Z,-applicant,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is an applicant is defeated'.
#pred blawx_initially(applicant(X)) :: 'that @(X) is an applicant holds initially'.
#pred blawx_initially(-applicant(X)) :: 'that it is not the case that @(X) is an applicant holds initially'.
#pred blawx_ultimately(applicant(X)) :: 'that @(X) is an applicant holds ultimately'.
#pred blawx_ultimately(-applicant(X)) :: 'that it is not the case that @(X) is an applicant holds ultimately'.
#pred blawx_as_of(applicant(X),T) :: 'that @(X) is an applicant holds at @(T)'.
#pred blawx_as_of(-applicant(X),T) :: 'that it is not the case that @(X) is an applicant holds at @(T)'.
#pred blawx_during(T1,applicant(X),T2) :: 'that @(X) is an applicant held between @(T1) and @(T2)'.
#pred blawx_during(T1,-applicant(X),T2) :: 'that it is not the case that @(X) is an applicant held between @(T1) and @(T2)'.
#pred blawx_becomes(applicant(X),T) :: 'that @(X) is an applicant became true at @(T)'.
#pred blawx_becomes(-applicant(X),T) :: 'that it is not the case that @(X) is an applicant became true at @(T)'.
#pred blawx_not_interrupted(Start,applicant(X),End) :: '@(X) is an applicant remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-applicant(X),End) :: 'it is not the case that @(X) is an applicant remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),applicant(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-applicant(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-applicant(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(applicant(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),applicant(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-applicant(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-applicant(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(applicant(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),applicant(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-applicant(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-applicant(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(applicant(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),applicant(X),datetime(eot)) :- blawx_initially(applicant(X)), blawx_ultimately(applicant(X)), findall(Time,blawx_becomes(-applicant(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-applicant(X),datetime(eot)) :- blawx_initially(-applicant(X)), blawx_ultimately(-applicant(X)), findall(Time,blawx_becomes(applicant(X),datetime(Time)),[]).
blawx_as_of(applicant(X),datetime(Time)) :- blawx_initially(applicant(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),applicant(X),datetime(BeforeT)).
blawx_as_of(applicant(X),datetime(Time)) :- blawx_becomes(applicant(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),applicant(X),datetime(Time)).
blawx_as_of(-applicant(X),datetime(Time)) :- blawx_initially(-applicant(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-applicant(X),datetime(BeforeT)).
blawx_as_of(-applicant(X),datetime(Time)) :- blawx_becomes(-applicant(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-applicant(X),datetime(Time)).
blawx_during(datetime(Start),applicant(X),datetime(End)) :- blawx_becomes(applicant(X),datetime(Start)), blawx_becomes(-applicant(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),applicant(X),datetime(End)).
blawx_during(datetime(bot),applicant(X),datetime(End)) :- blawx_initially(applicant(X)), blawx_becomes(-applicant(X),datetime(End)), blawx_not_interrupted(datetime(bot),applicant(X),datetime(End)).
blawx_during(datetime(Start),applicant(X),datetime(eot)) :- blawx_ultimately(applicant(X)), blawx_becomes(-applicant(X),datetime(Start)), blawx_not_interrupted(datetime(Start),applicant(X),datetime(eot)).
blawx_during(datetime(bot),applicant(X),datetime(eot)) :- blawx_initially(applicant(X)), blawx_ultimately(applicant(X)), blawx_becomes(-applicant(X),datetime(Start)), blawx_not_interrupted(datetime(bot),applicant(X),datetime(eot)).
blawx_during(datetime(Start),-applicant(X),datetime(End)) :- blawx_becomes(-applicant(X),datetime(Start)), blawx_becomes(applicant(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-applicant(X),datetime(End)).
blawx_during(datetime(bot),-applicant(X),datetime(End)) :- blawx_initially(-applicant(X)), blawx_becomes(applicant(X),datetime(End)), blawx_not_interrupted(datetime(bot),-applicant(X),datetime(End)).
blawx_during(datetime(Start),-applicant(X),datetime(eot)) :- blawx_ultimately(-applicant(X)), blawx_becomes(applicant(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-applicant(X),datetime(eot)).
blawx_during(datetime(bot),-applicant(X),datetime(eot)) :- blawx_initially(-applicant(X)), blawx_ultimately(-applicant(X)), blawx_becomes(-applicant(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-applicant(X),datetime(eot)).
blawx_attribute(applicant,age,number).
blawx_attribute_nlg(age,ov,"","has age of","").
:- dynamic age/2.
#pred age(X,Y) :: '@(X) has age of @(Y)'.
#pred holds(user,age,X,Y) :: 'it is provided as a fact that @(X) has age of @(Y)'.
#pred holds(user,-age,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has age of @(Y)'.
#pred holds(Z,age,X,Y) :: 'the conclusion in @(Z) that @(X) has age of @(Y) holds'.
#pred holds(Z,-age,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has age of @(Y) holds'.
#pred according_to(Z,age,X,Y) :: 'according to @(Z), @(X) has age of @(Y)'.
#pred according_to(Z,-age,X,Y) :: 'according to @(Z), it is not the case that @(X) has age of @(Y)'.
#pred blawx_defeated(Z,age,X,Y) :: 'the conclusion in @(Z) that @(X) has age of @(Y) is defeated'.
#pred blawx_defeated(Z,-age,X,Y) :: 'the conclusion in @(Z) that @(X) has age of @(Y) is defeated'.
#pred blawx_initially(age(X,Y)) :: 'that @(X) has age of @(Y) holds initially'.
#pred blawx_initially(-age(X,Y)) :: 'that it is not the case that @(X) has age of @(Y) holds initially'.
#pred blawx_ultimately(age(X,Y)) :: 'that @(X) has age of @(Y) holds ultimately'.
#pred blawx_ultimately(-age(X,Y)) :: 'that it is not the case that @(X) has age of @(Y) holds ultimately'.
#pred blawx_as_of(age(X,Y),T) :: 'that @(X) has age of @(Y) holds at @(T)'.
#pred blawx_as_of(-age(X,Y),T) :: 'that it is not the case that @(X) has age of @(Y) holds at @(T)'.
#pred blawx_during(T1,age(X,Y),T2) :: 'that @(X) has age of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-age(X,Y),T2) :: 'that it is not the case that @(X) has age of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(age(X,Y),T) :: 'that @(X) has age of @(Y) became true at @(T)'.
#pred blawx_becomes(-age(X,Y),T) :: 'that it is not the case that @(X) has age of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,age(X,Y),End) :: '@(X) has age of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-age(X,Y),End) :: 'it is not the case that @(X) has age of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),age(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-age(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-age(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(age(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),age(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-age(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-age(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(age(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),age(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-age(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-age(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(age(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),age(X,Y),datetime(eot)) :- blawx_initially(age(X,Y)), blawx_ultimately(age(X,Y)), findall(Time,blawx_becomes(-age(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-age(X,Y),datetime(eot)) :- blawx_initially(-age(X,Y)), blawx_ultimately(-age(X,Y)), findall(Time,blawx_becomes(age(X,Y),datetime(Time)),[]).
blawx_as_of(age(X,Y),datetime(Time)) :- blawx_initially(age(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),age(X,Y),datetime(BeforeT)).
blawx_as_of(age(X,Y),datetime(Time)) :- blawx_becomes(age(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),age(X,Y),datetime(Time)).
blawx_as_of(-age(X,Y),datetime(Time)) :- blawx_initially(-age(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-age(X,Y),datetime(BeforeT)).
blawx_as_of(-age(X,Y),datetime(Time)) :- blawx_becomes(-age(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-age(X,Y),datetime(Time)).
blawx_during(datetime(Start),age(X,Y),datetime(End)) :- blawx_becomes(age(X,Y),datetime(Start)), blawx_becomes(-age(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),age(X,Y),datetime(End)).
blawx_during(datetime(bot),age(X,Y),datetime(End)) :- blawx_initially(age(X,Y)), blawx_becomes(-age(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),age(X,Y),datetime(End)).
blawx_during(datetime(Start),age(X,Y),datetime(eot)) :- blawx_ultimately(age(X,Y)), blawx_becomes(-age(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),age(X,Y),datetime(eot)).
blawx_during(datetime(bot),age(X,Y),datetime(eot)) :- blawx_initially(age(X,Y)), blawx_ultimately(age(X,Y)), blawx_becomes(-age(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),age(X,Y),datetime(eot)).
blawx_during(datetime(Start),-age(X,Y),datetime(End)) :- blawx_becomes(-age(X,Y),datetime(Start)), blawx_becomes(age(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-age(X,Y),datetime(End)).
blawx_during(datetime(bot),-age(X,Y),datetime(End)) :- blawx_initially(-age(X,Y)), blawx_becomes(age(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-age(X,Y),datetime(End)).
blawx_during(datetime(Start),-age(X,Y),datetime(eot)) :- blawx_ultimately(-age(X,Y)), blawx_becomes(age(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-age(X,Y),datetime(eot)).
blawx_during(datetime(bot),-age(X,Y),datetime(eot)) :- blawx_initially(-age(X,Y)), blawx_ultimately(-age(X,Y)), blawx_becomes(-age(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-age(X,Y),datetime(eot)).
blawx_attribute(applicant,income,number).
blawx_attribute_nlg(income,ov,"","has income of","").
:- dynamic income/2.
#pred income(X,Y) :: '@(X) has income of @(Y)'.
#pred holds(user,income,X,Y) :: 'it is provided as a fact that @(X) has income of @(Y)'.
#pred holds(user,-income,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has income of @(Y)'.
#pred holds(Z,income,X,Y) :: 'the conclusion in @(Z) that @(X) has income of @(Y) holds'.
#pred holds(Z,-income,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has income of @(Y) holds'.
#pred according_to(Z,income,X,Y) :: 'according to @(Z), @(X) has income of @(Y)'.
#pred according_to(Z,-income,X,Y) :: 'according to @(Z), it is not the case that @(X) has income of @(Y)'.
#pred blawx_defeated(Z,income,X,Y) :: 'the conclusion in @(Z) that @(X) has income of @(Y) is defeated'.
#pred blawx_defeated(Z,-income,X,Y) :: 'the conclusion in @(Z) that @(X) has income of @(Y) is defeated'.
#pred blawx_initially(income(X,Y)) :: 'that @(X) has income of @(Y) holds initially'.
#pred blawx_initially(-income(X,Y)) :: 'that it is not the case that @(X) has income of @(Y) holds initially'.
#pred blawx_ultimately(income(X,Y)) :: 'that @(X) has income of @(Y) holds ultimately'.
#pred blawx_ultimately(-income(X,Y)) :: 'that it is not the case that @(X) has income of @(Y) holds ultimately'.
#pred blawx_as_of(income(X,Y),T) :: 'that @(X) has income of @(Y) holds at @(T)'.
#pred blawx_as_of(-income(X,Y),T) :: 'that it is not the case that @(X) has income of @(Y) holds at @(T)'.
#pred blawx_during(T1,income(X,Y),T2) :: 'that @(X) has income of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-income(X,Y),T2) :: 'that it is not the case that @(X) has income of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(income(X,Y),T) :: 'that @(X) has income of @(Y) became true at @(T)'.
#pred blawx_becomes(-income(X,Y),T) :: 'that it is not the case that @(X) has income of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,income(X,Y),End) :: '@(X) has income of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-income(X,Y),End) :: 'it is not the case that @(X) has income of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),income(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-income(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-income(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(income(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),income(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-income(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-income(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(income(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),income(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-income(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-income(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(income(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),income(X,Y),datetime(eot)) :- blawx_initially(income(X,Y)), blawx_ultimately(income(X,Y)), findall(Time,blawx_becomes(-income(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-income(X,Y),datetime(eot)) :- blawx_initially(-income(X,Y)), blawx_ultimately(-income(X,Y)), findall(Time,blawx_becomes(income(X,Y),datetime(Time)),[]).
blawx_as_of(income(X,Y),datetime(Time)) :- blawx_initially(income(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),income(X,Y),datetime(BeforeT)).
blawx_as_of(income(X,Y),datetime(Time)) :- blawx_becomes(income(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),income(X,Y),datetime(Time)).
blawx_as_of(-income(X,Y),datetime(Time)) :- blawx_initially(-income(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-income(X,Y),datetime(BeforeT)).
blawx_as_of(-income(X,Y),datetime(Time)) :- blawx_becomes(-income(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-income(X,Y),datetime(Time)).
blawx_during(datetime(Start),income(X,Y),datetime(End)) :- blawx_becomes(income(X,Y),datetime(Start)), blawx_becomes(-income(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),income(X,Y),datetime(End)).
blawx_during(datetime(bot),income(X,Y),datetime(End)) :- blawx_initially(income(X,Y)), blawx_becomes(-income(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),income(X,Y),datetime(End)).
blawx_during(datetime(Start),income(X,Y),datetime(eot)) :- blawx_ultimately(income(X,Y)), blawx_becomes(-income(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),income(X,Y),datetime(eot)).
blawx_during(datetime(bot),income(X,Y),datetime(eot)) :- blawx_initially(income(X,Y)), blawx_ultimately(income(X,Y)), blawx_becomes(-income(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),income(X,Y),datetime(eot)).
blawx_during(datetime(Start),-income(X,Y),datetime(End)) :- blawx_becomes(-income(X,Y),datetime(Start)), blawx_becomes(income(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-income(X,Y),datetime(End)).
blawx_during(datetime(bot),-income(X,Y),datetime(End)) :- blawx_initially(-income(X,Y)), blawx_becomes(income(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-income(X,Y),datetime(End)).
blawx_during(datetime(Start),-income(X,Y),datetime(eot)) :- blawx_ultimately(-income(X,Y)), blawx_becomes(income(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-income(X,Y),datetime(eot)).
blawx_during(datetime(bot),-income(X,Y),datetime(eot)) :- blawx_initially(-income(X,Y)), blawx_ultimately(-income(X,Y)), blawx_becomes(-income(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-income(X,Y),datetime(eot)).
blawx_attribute(applicant,is_veteran,boolean).
blawx_attribute_nlg(is_veteran,not_applicable,"",not_applicable,"is veteran").
:- dynamic is_veteran/1.
#pred is_veteran(X) :: '@(X) is veteran'.
#pred holds(user,is_veteran,X) :: 'it is provided as a fact that @(X) is veteran'.
#pred holds(user,-is_veteran,X) :: 'it is provided as a fact that it is not the case that @(X) is veteran'.
#pred holds(Z,is_veteran,X) :: 'the conclusion in @(Z) that @(X) is veteran holds'.
#pred holds(Z,-is_veteran,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is veteran holds'.
#pred according_to(Z,is_veteran,X) :: 'according to @(Z), @(X) is veteran'.
#pred according_to(Z,-is_veteran,X) :: 'according to @(Z), it is not the case that @(X) is veteran'.
#pred blawx_defeated(Z,is_veteran,X) :: 'the conclusion in @(Z) that @(X) is veteran is defeated'.
#pred blawx_defeated(Z,-is_veteran,X) :: 'the conclusion in @(Z) that @(X) is veteran is defeated'.
#pred blawx_initially(is_veteran(X)) :: 'that @(X) is veteran holds initially'.
#pred blawx_initially(-is_veteran(X)) :: 'that it is not the case that @(X) is veteran holds initially'.
#pred blawx_ultimately(is_veteran(X)) :: 'that @(X) is veteran holds ultimately'.
#pred blawx_ultimately(-is_veteran(X)) :: 'that it is not the case that @(X) is veteran holds ultimately'.
#pred blawx_as_of(is_veteran(X),T) :: 'that @(X) is veteran holds at @(T)'.
#pred blawx_as_of(-is_veteran(X),T) :: 'that it is not the case that @(X) is veteran holds at @(T)'.
#pred blawx_during(T1,is_veteran(X),T2) :: 'that @(X) is veteran held between @(T1) and @(T2)'.
#pred blawx_during(T1,-is_veteran(X),T2) :: 'that it is not the case that @(X) is veteran held between @(T1) and @(T2)'.
#pred blawx_becomes(is_veteran(X),T) :: 'that @(X) is veteran became true at @(T)'.
#pred blawx_becomes(-is_veteran(X),T) :: 'that it is not the case that @(X) is veteran became true at @(T)'.
#pred blawx_not_interrupted(Start,is_veteran(X),End) :: '@(X) is veteran remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-is_veteran(X),End) :: 'it is not the case that @(X) is veteran remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),is_veteran(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-is_veteran(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-is_veteran(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(is_veteran(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),is_veteran(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-is_veteran(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-is_veteran(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(is_veteran(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),is_veteran(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-is_veteran(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-is_veteran(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(is_veteran(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),is_veteran(X),datetime(eot)) :- blawx_initially(is_veteran(X)), blawx_ultimately(is_veteran(X)), findall(Time,blawx_becomes(-is_veteran(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-is_veteran(X),datetime(eot)) :- blawx_initially(-is_veteran(X)), blawx_ultimately(-is_veteran(X)), findall(Time,blawx_becomes(is_veteran(X),datetime(Time)),[]).
blawx_as_of(is_veteran(X),datetime(Time)) :- blawx_initially(is_veteran(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),is_veteran(X),datetime(BeforeT)).
blawx_as_of(is_veteran(X),datetime(Time)) :- blawx_becomes(is_veteran(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),is_veteran(X),datetime(Time)).
blawx_as_of(-is_veteran(X),datetime(Time)) :- blawx_initially(-is_veteran(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-is_veteran(X),datetime(BeforeT)).
blawx_as_of(-is_veteran(X),datetime(Time)) :- blawx_becomes(-is_veteran(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-is_veteran(X),datetime(Time)).
blawx_during(datetime(Start),is_veteran(X),datetime(End)) :- blawx_becomes(is_veteran(X),datetime(Start)), blawx_becomes(-is_veteran(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),is_veteran(X),datetime(End)).
blawx_during(datetime(bot),is_veteran(X),datetime(End)) :- blawx_initially(is_veteran(X)), blawx_becomes(-is_veteran(X),datetime(End)), blawx_not_interrupted(datetime(bot),is_veteran(X),datetime(End)).
blawx_during(datetime(Start),is_veteran(X),datetime(eot)) :- blawx_ultimately(is_veteran(X)), blawx_becomes(-is_veteran(X),datetime(Start)), blawx_not_interrupted(datetime(Start),is_veteran(X),datetime(eot)).
blawx_during(datetime(bot),is_veteran(X),datetime(eot)) :- blawx_initially(is_veteran(X)), blawx_ultimately(is_veteran(X)), blawx_becomes(-is_veteran(X),datetime(Start)), blawx_not_interrupted(datetime(bot),is_veteran(X),datetime(eot)).
blawx_during(datetime(Start),-is_veteran(X),datetime(End)) :- blawx_becomes(-is_veteran(X),datetime(Start)), blawx_becomes(is_veteran(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-is_veteran(X),datetime(End)).
blawx_during(datetime(bot),-is_veteran(X),datetime(End)) :- blawx_initially(-is_veteran(X)), blawx_becomes(is_veteran(X),datetime(End)), blawx_not_interrupted(datetime(bot),-is_veteran(X),datetime(End)).
blawx_during(datetime(Start),-is_veteran(X),datetime(eot)) :- blawx_ultimately(-is_veteran(X)), blawx_becomes(is_veteran(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-is_veteran(X),datetime(eot)).
blawx_during(datetime(bot),-is_veteran(X),datetime(eot)) :- blawx_initially(-is_veteran(X)), blawx_ultimately(-is_veteran(X)), blawx_becomes(-is_veteran(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-is_veteran(X),datetime(eot)).
blawx_attribute(applicant,eligible_for_benefit,boolean).
blawx_attribute_nlg(eligible_for_benefit,not_applicable,"",not_applicable,"eligible for benefit").
:- dynamic eligible_for_benefit/1.
#pred eligible_for_benefit(X) :: '@(X) eligible for benefit'.
#pred holds(user,eligible_for_benefit,X) :: 'it is provided as a fact that @(X) eligible for benefit'.
#pred holds(user,-eligible_for_benefit,X) :: 'it is provided as a fact that it is not the case that @(X) eligible for benefit'.
#pred holds(Z,eligible_for_benefit,X) :: 'the conclusion in @(Z) that @(X) eligible for benefit holds'.
#pred holds(Z,-eligible_for_benefit,X) :: 'the conclusion in @(Z) that it is not the case that @(X) eligible for benefit holds'.
#pred according_to(Z,eligible_for_benefit,X) :: 'according to @(Z), @(X) eligible for benefit'.
#pred according_to(Z,-eligible_for_benefit,X) :: 'according to @(Z), it is not the case that @(X) eligible for benefit'.
#pred blawx_defeated(Z,eligible_for_benefit,X) :: 'the conclusion in @(Z) that @(X) eligible for benefit is defeated'.
#pred blawx_defeated(Z,-eligible_for_benefit,X) :: 'the conclusion in @(Z) that @(X) eligible for benefit is defeated'.
#pred blawx_initially(eligible_for_benefit(X)) :: 'that @(X) eligible for benefit holds initially'.
#pred blawx_initially(-eligible_for_benefit(X)) :: 'that it is not the case that @(X) eligible for benefit holds initially'.
#pred blawx_ultimately(eligible_for_benefit(X)) :: 'that @(X) eligible for benefit holds ultimately'.
#pred blawx_ultimately(-eligible_for_benefit(X)) :: 'that it is not the case that @(X) eligible for benefit holds ultimately'.
#pred blawx_as_of(eligible_for_benefit(X),T) :: 'that @(X) eligible for benefit holds at @(T)'.
#pred blawx_as_of(-eligible_for_benefit(X),T) :: 'that it is not the case that @(X) eligible for benefit holds at @(T)'.
#pred blawx_during(T1,eligible_for_benefit(X),T2) :: 'that @(X) eligible for benefit held between @(T1) and @(T2)'.
#pred blawx_during(T1,-eligible_for_benefit(X),T2) :: 'that it is not the case that @(X) eligible for benefit held between @(T1) and @(T2)'.
#pred blawx_becomes(eligible_for_benefit(X),T) :: 'that @(X) eligible for benefit became true at @(T)'.
#pred blawx_becomes(-eligible_for_benefit(X),T) :: 'that it is not the case that @(X) eligible for benefit became true at @(T)'.
#pred blawx_not_interrupted(Start,eligible_for_benefit(X),End) :: '@(X) eligible for benefit remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-eligible_for_benefit(X),End) :: 'it is not the case that @(X) eligible for benefit remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),eligible_for_benefit(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-eligible_for_benefit(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),eligible_for_benefit(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-eligible_for_benefit(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),eligible_for_benefit(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-eligible_for_benefit(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(eligible_for_benefit(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),eligible_for_benefit(X),datetime(eot)) :- blawx_initially(eligible_for_benefit(X)), blawx_ultimately(eligible_for_benefit(X)), findall(Time,blawx_becomes(-eligible_for_benefit(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-eligible_for_benefit(X),datetime(eot)) :- blawx_initially(-eligible_for_benefit(X)), blawx_ultimately(-eligible_for_benefit(X)), findall(Time,blawx_becomes(eligible_for_benefit(X),datetime(Time)),[]).
blawx_as_of(eligible_for_benefit(X),datetime(Time)) :- blawx_initially(eligible_for_benefit(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),eligible_for_benefit(X),datetime(BeforeT)).
blawx_as_of(eligible_for_benefit(X),datetime(Time)) :- blawx_becomes(eligible_for_benefit(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),eligible_for_benefit(X),datetime(Time)).
blawx_as_of(-eligible_for_benefit(X),datetime(Time)) :- blawx_initially(-eligible_for_benefit(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-eligible_for_benefit(X),datetime(BeforeT)).
blawx_as_of(-eligible_for_benefit(X),datetime(Time)) :- blawx_becomes(-eligible_for_benefit(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-eligible_for_benefit(X),datetime(Time)).
blawx_during(datetime(Start),eligible_for_benefit(X),datetime(End)) :- blawx_becomes(eligible_for_benefit(X),datetime(Start)), blawx_becomes(-eligible_for_benefit(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),eligible_for_benefit(X),datetime(End)).
blawx_during(datetime(bot),eligible_for_benefit(X),datetime(End)) :- blawx_initially(eligible_for_benefit(X)), blawx_becomes(-eligible_for_benefit(X),datetime(End)), blawx_not_interrupted(datetime(bot),eligible_for_benefit(X),datetime(End)).
blawx_during(datetime(Start),eligible_for_benefit(X),datetime(eot)) :- blawx_ultimately(eligible_for_benefit(X)), blawx_becomes(-eligible_for_benefit(X),datetime(Start)), blawx_not_interrupted(datetime(Start),eligible_for_benefit(X),datetime(eot)).
blawx_during(datetime(bot),eligible_for_benefit(X),datetime(eot)) :- blawx_initially(eligible_for_benefit(X)), blawx_ultimately(eligible_for_benefit(X)), blawx_becomes(-eligible_for_benefit(X),datetime(Start)), blawx_not_interrupted(datetime(bot),eligible_for_benefit(X),datetime(eot)).
blawx_during(datetime(Start),-eligible_for_benefit(X),datetime(End)) :- blawx_becomes(-eligible_for_benefit(X),datetime(Start)), blawx_becomes(eligible_for_benefit(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-eligible_for_benefit(X),datetime(End)).
blawx_during(datetime(bot),-eligible_for_benefit(X),datetime(End)) :- blawx_initially(-eligible_for_benefit(X)), blawx_becomes(eligible_for_benefit(X),datetime(End)), blawx_not_interrupted(datetime(bot),-eligible_for_benefit(X),datetime(End)).
blawx_during(datetime(Start),-eligible_for_benefit(X),datetime(eot)) :- blawx_ultimately(-eligible_for_benefit(X)), blawx_becomes(eligible_for_benefit(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-eligible_for_benefit(X),datetime(eot)).
blawx_during(datetime(bot),-eligible_for_benefit(X),datetime(eot)) :- blawx_initially(-eligible_for_benefit(X)), blawx_ultimately(-eligible_for_benefit(X)), blawx_becomes(-eligible_for_benefit(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-eligible_for_benefit(X),datetime(eot)).
blawx_attribute(applicant,benefit_amount,number).
blawx_attribute_nlg(benefit_amount,ov,"","has benefit amount of","").
:- dynamic benefit_amount/2.
#pred benefit_amount(X,Y) :: '@(X) has benefit amount of @(Y)'.
#pred holds(user,benefit_amount,X,Y) :: 'it is provided as a fact that @(X) has benefit amount of @(Y)'.
#pred holds(user,-benefit_amount,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has benefit amount of @(Y)'.
#pred holds(Z,benefit_amount,X,Y) :: 'the conclusion in @(Z) that @(X) has benefit amount of @(Y) holds'.
#pred holds(Z,-benefit_amount,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has benefit amount of @(Y) holds'.
#pred according_to(Z,benefit_amount,X,Y) :: 'according to @(Z), @(X) has benefit amount of @(Y)'.
#pred according_to(Z,-benefit_amount,X,Y) :: 'according to @(Z), it is not the case that @(X) has benefit amount of @(Y)'.
#pred blawx_defeated(Z,benefit_amount,X,Y) :: 'the conclusion in @(Z) that @(X) has benefit amount of @(Y) is defeated'.
#pred blawx_defeated(Z,-benefit_amount,X,Y) :: 'the conclusion in @(Z) that @(X) has benefit amount of @(Y) is defeated'.
#pred blawx_initially(benefit_amount(X,Y)) :: 'that @(X) has benefit amount of @(Y) holds initially'.
#pred blawx_initially(-benefit_amount(X,Y)) :: 'that it is not the case that @(X) has benefit amount of @(Y) holds initially'.
#pred blawx_ultimately(benefit_amount(X,Y)) :: 'that @(X) has benefit amount of @(Y) holds ultimately'.
#pred blawx_ultimately(-benefit_amount(X,Y)) :: 'that it is not the case that @(X) has benefit amount of @(Y) holds ultimately'.
#pred blawx_as_of(benefit_amount(X,Y),T) :: 'that @(X) has benefit amount of @(Y) holds at @(T)'.
#pred blawx_as_of(-benefit_amount(X,Y),T) :: 'that it is not the case that @(X) has benefit amount of @(Y) holds at @(T)'.
#pred blawx_during(T1,benefit_amount(X,Y),T2) :: 'that @(X) has benefit amount of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-benefit_amount(X,Y),T2) :: 'that it is not the case that @(X) has benefit amount of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(benefit_amount(X,Y),T) :: 'that @(X) has benefit amount of @(Y) became true at @(T)'.
#pred blawx_becomes(-benefit_amount(X,Y),T) :: 'that it is not the case that @(X) has benefit amount of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,benefit_amount(X,Y),End) :: '@(X) has benefit amount of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-benefit_amount(X,Y),End) :: 'it is not the case that @(X) has benefit amount of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),benefit_amount(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-benefit_amount(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),benefit_amount(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-benefit_amount(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),benefit_amount(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-benefit_amount(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(benefit_amount(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),benefit_amount(X,Y),datetime(eot)) :- blawx_initially(benefit_amount(X,Y)), blawx_ultimately(benefit_amount(X,Y)), findall(Time,blawx_becomes(-benefit_amount(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-benefit_amount(X,Y),datetime(eot)) :- blawx_initially(-benefit_amount(X,Y)), blawx_ultimately(-benefit_amount(X,Y)), findall(Time,blawx_becomes(benefit_amount(X,Y),datetime(Time)),[]).
blawx_as_of(benefit_amount(X,Y),datetime(Time)) :- blawx_initially(benefit_amount(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),benefit_amount(X,Y),datetime(BeforeT)).
blawx_as_of(benefit_amount(X,Y),datetime(Time)) :- blawx_becomes(benefit_amount(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),benefit_amount(X,Y),datetime(Time)).
blawx_as_of(-benefit_amount(X,Y),datetime(Time)) :- blawx_initially(-benefit_amount(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-benefit_amount(X,Y),datetime(BeforeT)).
blawx_as_of(-benefit_amount(X,Y),datetime(Time)) :- blawx_becomes(-benefit_amount(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-benefit_amount(X,Y),datetime(Time)).
blawx_during(datetime(Start),benefit_amount(X,Y),datetime(End)) :- blawx_becomes(benefit_amount(X,Y),datetime(Start)), blawx_becomes(-benefit_amount(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),benefit_amount(X,Y),datetime(End)).
blawx_during(datetime(bot),benefit_amount(X,Y),datetime(End)) :- blawx_initially(benefit_amount(X,Y)), blawx_becomes(-benefit_amount(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),benefit_amount(X,Y),datetime(End)).
blawx_during(datetime(Start),benefit_amount(X,Y),datetime(eot)) :- blawx_ultimately(benefit_amount(X,Y)), blawx_becomes(-benefit_amount(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),benefit_amount(X,Y),datetime(eot)).
blawx_during(datetime(bot),benefit_amount(X,Y),datetime(eot)) :- blawx_initially(benefit_amount(X,Y)), blawx_ultimately(benefit_amount(X,Y)), blawx_becomes(-benefit_amount(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),benefit_amount(X,Y),datetime(eot)).
blawx_during(datetime(Start),-benefit_amount(X,Y),datetime(End)) :- blawx_becomes(-benefit_amount(X,Y),datetime(Start)), blawx_becomes(benefit_amount(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-benefit_amount(X,Y),datetime(End)).
blawx_during(datetime(bot),-benefit_amount(X,Y),datetime(End)) :- blawx_initially(-benefit_amount(X,Y)), blawx_becomes(benefit_amount(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-benefit_amount(X,Y),datetime(End)).
blawx_during(datetime(Start),-benefit_amount(X,Y),datetime(eot)) :- blawx_ultimately(-benefit_amount(X,Y)), blawx_becomes(benefit_amount(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-benefit_amount(X,Y),datetime(eot)).
blawx_during(datetime(bot),-benefit_amount(X,Y),datetime(eot)) :- blawx_initially(-benefit_amount(X,Y)), blawx_ultimately(-benefit_amount(X,Y)), blawx_becomes(-benefit_amount(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-benefit_amount(X,Y),datetime(eot)).
blawx_attribute(applicant,bonus,number).
blawx_attribute_nlg(bonus,ov,"","has bonus of","").
:- dynamic bonus/2.
#pred bonus(X,Y) :: '@(X) has bonus of @(Y)'.
#pred holds(user,bonus,X,Y) :: 'it is provided as a fact that @(X) has bonus of @(Y)'.
#pred holds(user,-bonus,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has bonus of @(Y)'.
#pred holds(Z,bonus,X,Y) :: 'the conclusion in @(Z) that @(X) has bonus of @(Y) holds'.
#pred holds(Z,-bonus,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has bonus of @(Y) holds'.
#pred according_to(Z,bonus,X,Y) :: 'according to @(Z), @(X) has bonus of @(Y)'.
#pred according_to(Z,-bonus,X,Y) :: 'according to @(Z), it is not the case that @(X) has bonus of @(Y)'.
#pred blawx_defeated(Z,bonus,X,Y) :: 'the conclusion in @(Z) that @(X) has bonus of @(Y) is defeated'.
#pred blawx_defeated(Z,-bonus,X,Y) :: 'the conclusion in @(Z) that @(X) has bonus of @(Y) is defeated'.
#pred blawx_initially(bonus(X,Y)) :: 'that @(X) has bonus of @(Y) holds initially'.
#pred blawx_initially(-bonus(X,Y)) :: 'that it is not the case that @(X) has bonus of @(Y) holds initially'.
#pred blawx_ultimately(bonus(X,Y)) :: 'that @(X) has bonus of @(Y) holds ultimately'.
#pred blawx_ultimately(-bonus(X,Y)) :: 'that it is not the case that @(X) has bonus of @(Y) holds ultimately'.
#pred blawx_as_of(bonus(X,Y),T) :: 'that @(X) has bonus of @(Y) holds at @(T)'.
#pred blawx_as_of(-bonus(X,Y),T) :: 'that it is not the case that @(X) has bonus of @(Y) holds at @(T)'.
#pred blawx_during(T1,bonus(X,Y),T2) :: 'that @(X) has bonus of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-bonus(X,Y),T2) :: 'that it is not the case that @(X) has bonus of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(bonus(X,Y),T) :: 'that @(X) has bonus of @(Y) became true at @(T)'.
#pred blawx_becomes(-bonus(X,Y),T) :: 'that it is not the case that @(X) has bonus of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,bonus(X,Y),End) :: '@(X) has bonus of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-bonus(X,Y),End) :: 'it is not the case that @(X) has bonus of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),bonus(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-bonus(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-bonus(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(bonus(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),bonus(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-bonus(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-bonus(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(bonus(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),bonus(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-bonus(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-bonus(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(bonus(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),bonus(X,Y),datetime(eot)) :- blawx_initially(bonus(X,Y)), blawx_ultimately(bonus(X,Y)), findall(Time,blawx_becomes(-bonus(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-bonus(X,Y),datetime(eot)) :- blawx_initially(-bonus(X,Y)), blawx_ultimately(-bonus(X,Y)), findall(Time,blawx_becomes(bonus(X,Y),datetime(Time)),[]).
blawx_as_of(bonus(X,Y),datetime(Time)) :- blawx_initially(bonus(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),bonus(X,Y),datetime(BeforeT)).
blawx_as_of(bonus(X,Y),datetime(Time)) :- blawx_becomes(bonus(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),bonus(X,Y),datetime(Time)).
blawx_as_of(-bonus(X,Y),datetime(Time)) :- blawx_initially(-bonus(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-bonus(X,Y),datetime(BeforeT)).
blawx_as_of(-bonus(X,Y),datetime(Time)) :- blawx_becomes(-bonus(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-bonus(X,Y),datetime(Time)).
blawx_during(datetime(Start),bonus(X,Y),datetime(End)) :- blawx_becomes(bonus(X,Y),datetime(Start)), blawx_becomes(-bonus(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),bonus(X,Y),datetime(End)).
blawx_during(datetime(bot),bonus(X,Y),datetime(End)) :- blawx_initially(bonus(X,Y)), blawx_becomes(-bonus(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),bonus(X,Y),datetime(End)).
blawx_during(datetime(Start),bonus(X,Y),datetime(eot)) :- blawx_ultimately(bonus(X,Y)), blawx_becomes(-bonus(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),bonus(X,Y),datetime(eot)).
blawx_during(datetime(bot),bonus(X,Y),datetime(eot)) :- blawx_initially(bonus(X,Y)), blawx_ultimately(bonus(X,Y)), blawx_becomes(-bonus(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),bonus(X,Y),datetime(eot)).
blawx_during(datetime(Start),-bonus(X,Y),datetime(End)) :- blawx_becomes(-bonus(X,Y),datetime(Start)), blawx_becomes(bonus(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-bonus(X,Y),datetime(End)).
blawx_during(datetime(bot),-bonus(X,Y),datetime(End)) :- blawx_initially(-bonus(X,Y)), blawx_becomes(bonus(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-bonus(X,Y),datetime(End)).
blawx_during(datetime(Start),-bonus(X,Y),datetime(eot)) :- blawx_ultimately(-bonus(X,Y)), blawx_becomes(bonus(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-bonus(X,Y),datetime(eot)).
blawx_during(datetime(bot),-bonus(X,Y),datetime(eot)) :- blawx_initially(-bonus(X,Y)), blawx_ultimately(-bonus(X,Y)), blawx_becomes(-bonus(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-bonus(X,Y),datetime(eot)).

according_to(sec_1_section,eligible_for_benefit,A) :- applicant(A),
age(A,Age),
blawx_comparison(Age,gte,65),
income(A,Income),
blawx_comparison(Income,lte,100000).

% BLAWX CHECK DUPLICATES
holds(sec_1_section,eligible_for_benefit,A) :- according_to(sec_1_section,eligible_for_benefit,A).

% BLAWX CHECK DUPLICATES
  eligible_for_benefit(A) :- holds(sec_1_section,eligible_for_benefit,A).

according_to(sec_1_section,eligible_for_benefit,A) :- applicant(A),
is_veteran(A),
income(A,Income),
blawx_comparison(Income,lte,100000).

% BLAWX CHECK DUPLICATES
holds(sec_1_section,eligible_for_benefit,A) :- according_to(sec_1_section,eligible_for_benefit,A).

% BLAWX CHECK DUPLICATES
  eligible_for_benefit(A) :- holds(sec_1_section,eligible_for_benefit,A).

according_to(sec_2_section,benefit_amount,A,Tmp) :- applicant(A),
eligible_for_benefit(A),
bonus(A,Bonus),
Tmp is ( 1000 + Bonus ).

% BLAWX CHECK DUPLICATES
holds(sec_2_section,benefit_amount,A,Tmp) :- according_to(sec_2_section,benefit_amount,A,Tmp).

% BLAWX CHECK DUPLICATES
  benefit_amount(A,Tmp) :- holds(sec_2_section,benefit_amount,A,Tmp).

according_to(sec_2_section,benefit_amount,A,0) :- applicant(A),
not eligible_for_benefit(A).

% BLAWX CHECK DUPLICATES
holds(sec_2_section,benefit_amount,A,0) :- according_to(sec_2_section,benefit_amount,A,0).

% BLAWX CHECK DUPLICATES
  benefit_amount(A,0) :- holds(sec_2_section,benefit_amount,A,0).

according_to(sec_2_section,bonus,A,250) :- applicant(A),
is_veteran(A).

% BLAWX CHECK DUPLICATES
holds(sec_2_section,bonus,A,250) :- according_to(sec_2_section,bonus,A,250).

% BLAWX CHECK DUPLICATES
  bonus(A,250) :- holds(sec_2_section,bonus,A,250).

according_to(sec_2_section,bonus,A,0) :- applicant(A),
-is_veteran(A).

% BLAWX CHECK DUPLICATES
holds(sec_2_section,bonus,A,0) :- according_to(sec_2_section,bonus,A,0).

% BLAWX CHECK DUPLICATES
  bonus(A,0) :- holds(sec_2_section,bonus,A,0).
