% generated by l4 export blawx from defaults.l4 — raw concatenated s(CASP); tests live in the .blawx / tier-1 harness
% epistemics (R5): an input that is neither asserted, denied, nor abducible yields NO MODEL (loud), never a silent false
% lossy R-TYPICALLY — timeout: the field `timeout` of `Config` carries TYPICALLY 30, which is dropped: a Blawx attribute is a fact asserted about an object, or left out; it has no default
% lossy R-TYPICALLY — rate: the GIVEN `rate` of `budget` carries TYPICALLY 3, which is dropped: a rule's inputs are arguments of its predicate, which the caller always supplies, so nothing applies the default

blawx_category(config).
blawx_category_nlg(config,"","is a config").
:- dynamic config/1.
#pred config(X) :: '@(X) is a config'.
#pred holds(user,config,X) :: 'it is provided as a fact that @(X) is a config'.
#pred holds(user,-config,X) :: 'it is provided as a fact that it is not the case that @(X) is a config'.
#pred holds(Z,config,X) :: 'the conclusion in @(Z) that @(X) is a config holds'.
#pred holds(Z,-config,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is a config holds'.
#pred according_to(Z,config,X) :: 'according to @(Z), @(X) is a config'.
#pred according_to(Z,-config,X) :: 'according to @(Z), it is not the case that @(X) is a config'.
#pred blawx_defeated(Z,config,X) :: 'the conclusion in @(Z) that @(X) is a config is defeated'.
#pred blawx_defeated(Z,-config,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is a config is defeated'.
#pred blawx_initially(config(X)) :: 'that @(X) is a config holds initially'.
#pred blawx_initially(-config(X)) :: 'that it is not the case that @(X) is a config holds initially'.
#pred blawx_ultimately(config(X)) :: 'that @(X) is a config holds ultimately'.
#pred blawx_ultimately(-config(X)) :: 'that it is not the case that @(X) is a config holds ultimately'.
#pred blawx_as_of(config(X),T) :: 'that @(X) is a config holds at @(T)'.
#pred blawx_as_of(-config(X),T) :: 'that it is not the case that @(X) is a config holds at @(T)'.
#pred blawx_during(T1,config(X),T2) :: 'that @(X) is a config held between @(T1) and @(T2)'.
#pred blawx_during(T1,-config(X),T2) :: 'that it is not the case that @(X) is a config held between @(T1) and @(T2)'.
#pred blawx_becomes(config(X),T) :: 'that @(X) is a config became true at @(T)'.
#pred blawx_becomes(-config(X),T) :: 'that it is not the case that @(X) is a config became true at @(T)'.
#pred blawx_not_interrupted(Start,config(X),End) :: '@(X) is a config remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-config(X),End) :: 'it is not the case that @(X) is a config remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),config(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-config(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-config(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(config(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),config(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-config(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-config(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(config(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),config(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-config(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-config(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(config(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),config(X),datetime(eot)) :- blawx_initially(config(X)), blawx_ultimately(config(X)), findall(Time,blawx_becomes(-config(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-config(X),datetime(eot)) :- blawx_initially(-config(X)), blawx_ultimately(-config(X)), findall(Time,blawx_becomes(config(X),datetime(Time)),[]).
blawx_as_of(config(X),datetime(Time)) :- blawx_initially(config(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),config(X),datetime(BeforeT)).
blawx_as_of(config(X),datetime(Time)) :- blawx_becomes(config(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),config(X),datetime(Time)).
blawx_as_of(-config(X),datetime(Time)) :- blawx_initially(-config(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-config(X),datetime(BeforeT)).
blawx_as_of(-config(X),datetime(Time)) :- blawx_becomes(-config(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-config(X),datetime(Time)).
blawx_during(datetime(Start),config(X),datetime(End)) :- blawx_becomes(config(X),datetime(Start)), blawx_becomes(-config(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),config(X),datetime(End)).
blawx_during(datetime(bot),config(X),datetime(End)) :- blawx_initially(config(X)), blawx_becomes(-config(X),datetime(End)), blawx_not_interrupted(datetime(bot),config(X),datetime(End)).
blawx_during(datetime(Start),config(X),datetime(eot)) :- blawx_ultimately(config(X)), blawx_becomes(-config(X),datetime(Start)), blawx_not_interrupted(datetime(Start),config(X),datetime(eot)).
blawx_during(datetime(bot),config(X),datetime(eot)) :- blawx_initially(config(X)), blawx_ultimately(config(X)), blawx_becomes(-config(X),datetime(Start)), blawx_not_interrupted(datetime(bot),config(X),datetime(eot)).
blawx_during(datetime(Start),-config(X),datetime(End)) :- blawx_becomes(-config(X),datetime(Start)), blawx_becomes(config(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-config(X),datetime(End)).
blawx_during(datetime(bot),-config(X),datetime(End)) :- blawx_initially(-config(X)), blawx_becomes(config(X),datetime(End)), blawx_not_interrupted(datetime(bot),-config(X),datetime(End)).
blawx_during(datetime(Start),-config(X),datetime(eot)) :- blawx_ultimately(-config(X)), blawx_becomes(config(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-config(X),datetime(eot)).
blawx_during(datetime(bot),-config(X),datetime(eot)) :- blawx_initially(-config(X)), blawx_ultimately(-config(X)), blawx_becomes(-config(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-config(X),datetime(eot)).
blawx_attribute(config,timeout,number).
blawx_attribute_nlg(timeout,ov,"","has timeout of","").
:- dynamic timeout/2.
#pred timeout(X,Y) :: '@(X) has timeout of @(Y)'.
#pred holds(user,timeout,X,Y) :: 'it is provided as a fact that @(X) has timeout of @(Y)'.
#pred holds(user,-timeout,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has timeout of @(Y)'.
#pred holds(Z,timeout,X,Y) :: 'the conclusion in @(Z) that @(X) has timeout of @(Y) holds'.
#pred holds(Z,-timeout,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has timeout of @(Y) holds'.
#pred according_to(Z,timeout,X,Y) :: 'according to @(Z), @(X) has timeout of @(Y)'.
#pred according_to(Z,-timeout,X,Y) :: 'according to @(Z), it is not the case that @(X) has timeout of @(Y)'.
#pred blawx_defeated(Z,timeout,X,Y) :: 'the conclusion in @(Z) that @(X) has timeout of @(Y) is defeated'.
#pred blawx_defeated(Z,-timeout,X,Y) :: 'the conclusion in @(Z) that @(X) has timeout of @(Y) is defeated'.
#pred blawx_initially(timeout(X,Y)) :: 'that @(X) has timeout of @(Y) holds initially'.
#pred blawx_initially(-timeout(X,Y)) :: 'that it is not the case that @(X) has timeout of @(Y) holds initially'.
#pred blawx_ultimately(timeout(X,Y)) :: 'that @(X) has timeout of @(Y) holds ultimately'.
#pred blawx_ultimately(-timeout(X,Y)) :: 'that it is not the case that @(X) has timeout of @(Y) holds ultimately'.
#pred blawx_as_of(timeout(X,Y),T) :: 'that @(X) has timeout of @(Y) holds at @(T)'.
#pred blawx_as_of(-timeout(X,Y),T) :: 'that it is not the case that @(X) has timeout of @(Y) holds at @(T)'.
#pred blawx_during(T1,timeout(X,Y),T2) :: 'that @(X) has timeout of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-timeout(X,Y),T2) :: 'that it is not the case that @(X) has timeout of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(timeout(X,Y),T) :: 'that @(X) has timeout of @(Y) became true at @(T)'.
#pred blawx_becomes(-timeout(X,Y),T) :: 'that it is not the case that @(X) has timeout of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,timeout(X,Y),End) :: '@(X) has timeout of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-timeout(X,Y),End) :: 'it is not the case that @(X) has timeout of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),timeout(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-timeout(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-timeout(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(timeout(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),timeout(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-timeout(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-timeout(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(timeout(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),timeout(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-timeout(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-timeout(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(timeout(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),timeout(X,Y),datetime(eot)) :- blawx_initially(timeout(X,Y)), blawx_ultimately(timeout(X,Y)), findall(Time,blawx_becomes(-timeout(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-timeout(X,Y),datetime(eot)) :- blawx_initially(-timeout(X,Y)), blawx_ultimately(-timeout(X,Y)), findall(Time,blawx_becomes(timeout(X,Y),datetime(Time)),[]).
blawx_as_of(timeout(X,Y),datetime(Time)) :- blawx_initially(timeout(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),timeout(X,Y),datetime(BeforeT)).
blawx_as_of(timeout(X,Y),datetime(Time)) :- blawx_becomes(timeout(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),timeout(X,Y),datetime(Time)).
blawx_as_of(-timeout(X,Y),datetime(Time)) :- blawx_initially(-timeout(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-timeout(X,Y),datetime(BeforeT)).
blawx_as_of(-timeout(X,Y),datetime(Time)) :- blawx_becomes(-timeout(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-timeout(X,Y),datetime(Time)).
blawx_during(datetime(Start),timeout(X,Y),datetime(End)) :- blawx_becomes(timeout(X,Y),datetime(Start)), blawx_becomes(-timeout(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),timeout(X,Y),datetime(End)).
blawx_during(datetime(bot),timeout(X,Y),datetime(End)) :- blawx_initially(timeout(X,Y)), blawx_becomes(-timeout(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),timeout(X,Y),datetime(End)).
blawx_during(datetime(Start),timeout(X,Y),datetime(eot)) :- blawx_ultimately(timeout(X,Y)), blawx_becomes(-timeout(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),timeout(X,Y),datetime(eot)).
blawx_during(datetime(bot),timeout(X,Y),datetime(eot)) :- blawx_initially(timeout(X,Y)), blawx_ultimately(timeout(X,Y)), blawx_becomes(-timeout(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),timeout(X,Y),datetime(eot)).
blawx_during(datetime(Start),-timeout(X,Y),datetime(End)) :- blawx_becomes(-timeout(X,Y),datetime(Start)), blawx_becomes(timeout(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-timeout(X,Y),datetime(End)).
blawx_during(datetime(bot),-timeout(X,Y),datetime(End)) :- blawx_initially(-timeout(X,Y)), blawx_becomes(timeout(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-timeout(X,Y),datetime(End)).
blawx_during(datetime(Start),-timeout(X,Y),datetime(eot)) :- blawx_ultimately(-timeout(X,Y)), blawx_becomes(timeout(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-timeout(X,Y),datetime(eot)).
blawx_during(datetime(bot),-timeout(X,Y),datetime(eot)) :- blawx_initially(-timeout(X,Y)), blawx_ultimately(-timeout(X,Y)), blawx_becomes(-timeout(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-timeout(X,Y),datetime(eot)).
blawx_attribute(config,retries,number).
blawx_attribute_nlg(retries,ov,"","has retries of","").
:- dynamic retries/2.
#pred retries(X,Y) :: '@(X) has retries of @(Y)'.
#pred holds(user,retries,X,Y) :: 'it is provided as a fact that @(X) has retries of @(Y)'.
#pred holds(user,-retries,X,Y) :: 'it is provided as a fact that it is not the case that @(X) has retries of @(Y)'.
#pred holds(Z,retries,X,Y) :: 'the conclusion in @(Z) that @(X) has retries of @(Y) holds'.
#pred holds(Z,-retries,X,Y) :: 'the conclusion in @(Z) that it is not the case that @(X) has retries of @(Y) holds'.
#pred according_to(Z,retries,X,Y) :: 'according to @(Z), @(X) has retries of @(Y)'.
#pred according_to(Z,-retries,X,Y) :: 'according to @(Z), it is not the case that @(X) has retries of @(Y)'.
#pred blawx_defeated(Z,retries,X,Y) :: 'the conclusion in @(Z) that @(X) has retries of @(Y) is defeated'.
#pred blawx_defeated(Z,-retries,X,Y) :: 'the conclusion in @(Z) that @(X) has retries of @(Y) is defeated'.
#pred blawx_initially(retries(X,Y)) :: 'that @(X) has retries of @(Y) holds initially'.
#pred blawx_initially(-retries(X,Y)) :: 'that it is not the case that @(X) has retries of @(Y) holds initially'.
#pred blawx_ultimately(retries(X,Y)) :: 'that @(X) has retries of @(Y) holds ultimately'.
#pred blawx_ultimately(-retries(X,Y)) :: 'that it is not the case that @(X) has retries of @(Y) holds ultimately'.
#pred blawx_as_of(retries(X,Y),T) :: 'that @(X) has retries of @(Y) holds at @(T)'.
#pred blawx_as_of(-retries(X,Y),T) :: 'that it is not the case that @(X) has retries of @(Y) holds at @(T)'.
#pred blawx_during(T1,retries(X,Y),T2) :: 'that @(X) has retries of @(Y) held between @(T1) and @(T2)'.
#pred blawx_during(T1,-retries(X,Y),T2) :: 'that it is not the case that @(X) has retries of @(Y) held between @(T1) and @(T2)'.
#pred blawx_becomes(retries(X,Y),T) :: 'that @(X) has retries of @(Y) became true at @(T)'.
#pred blawx_becomes(-retries(X,Y),T) :: 'that it is not the case that @(X) has retries of @(Y) became true at @(T)'.
#pred blawx_not_interrupted(Start,retries(X,Y),End) :: '@(X) has retries of @(Y) remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-retries(X,Y),End) :: 'it is not the case that @(X) has retries of @(Y) remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),retries(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-retries(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-retries(X,Y),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(retries(X,Y),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),retries(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-retries(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-retries(X,Y),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(retries(X,Y),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),retries(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-retries(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-retries(X,Y),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(retries(X,Y),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),retries(X,Y),datetime(eot)) :- blawx_initially(retries(X,Y)), blawx_ultimately(retries(X,Y)), findall(Time,blawx_becomes(-retries(X,Y),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-retries(X,Y),datetime(eot)) :- blawx_initially(-retries(X,Y)), blawx_ultimately(-retries(X,Y)), findall(Time,blawx_becomes(retries(X,Y),datetime(Time)),[]).
blawx_as_of(retries(X,Y),datetime(Time)) :- blawx_initially(retries(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),retries(X,Y),datetime(BeforeT)).
blawx_as_of(retries(X,Y),datetime(Time)) :- blawx_becomes(retries(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),retries(X,Y),datetime(Time)).
blawx_as_of(-retries(X,Y),datetime(Time)) :- blawx_initially(-retries(X,Y)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-retries(X,Y),datetime(BeforeT)).
blawx_as_of(-retries(X,Y),datetime(Time)) :- blawx_becomes(-retries(X,Y),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-retries(X,Y),datetime(Time)).
blawx_during(datetime(Start),retries(X,Y),datetime(End)) :- blawx_becomes(retries(X,Y),datetime(Start)), blawx_becomes(-retries(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),retries(X,Y),datetime(End)).
blawx_during(datetime(bot),retries(X,Y),datetime(End)) :- blawx_initially(retries(X,Y)), blawx_becomes(-retries(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),retries(X,Y),datetime(End)).
blawx_during(datetime(Start),retries(X,Y),datetime(eot)) :- blawx_ultimately(retries(X,Y)), blawx_becomes(-retries(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),retries(X,Y),datetime(eot)).
blawx_during(datetime(bot),retries(X,Y),datetime(eot)) :- blawx_initially(retries(X,Y)), blawx_ultimately(retries(X,Y)), blawx_becomes(-retries(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),retries(X,Y),datetime(eot)).
blawx_during(datetime(Start),-retries(X,Y),datetime(End)) :- blawx_becomes(-retries(X,Y),datetime(Start)), blawx_becomes(retries(X,Y),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-retries(X,Y),datetime(End)).
blawx_during(datetime(bot),-retries(X,Y),datetime(End)) :- blawx_initially(-retries(X,Y)), blawx_becomes(retries(X,Y),datetime(End)), blawx_not_interrupted(datetime(bot),-retries(X,Y),datetime(End)).
blawx_during(datetime(Start),-retries(X,Y),datetime(eot)) :- blawx_ultimately(-retries(X,Y)), blawx_becomes(retries(X,Y),datetime(Start)), blawx_not_interrupted(datetime(Start),-retries(X,Y),datetime(eot)).
blawx_during(datetime(bot),-retries(X,Y),datetime(eot)) :- blawx_initially(-retries(X,Y)), blawx_ultimately(-retries(X,Y)), blawx_becomes(-retries(X,Y),datetime(Start)), blawx_not_interrupted(datetime(bot),-retries(X,Y),datetime(eot)).
blawx_relationship(budget,config,number,number).
blawx_relationship_nlg(budget,"","and","and","are related as budget").
:- dynamic budget/3.
#pred budget(A,B,C) :: '@(A) and @(B) and @(C) are related as budget'.
#pred holds(user,budget,A,B,C) :: 'it is provided as a fact that @(A) and @(B) and @(C) are related as budget'.
#pred holds(user,-budget,A,B,C) :: 'it is provided as a fact that it is not the case that @(A) and @(B) and @(C) are related as budget'.
#pred holds(Z,budget,A,B,C) :: 'the conclusion in @(Z) that @(A) and @(B) and @(C) are related as budget holds'.
#pred holds(Z,-budget,A,B,C) :: 'the conclusion in @(Z) that it is not the case that @(A) and @(B) and @(C) are related as budget holds'.
#pred according_to(Z,budget,A,B,C) :: 'according to @(Z), @(A) and @(B) and @(C) are related as budget'.
#pred according_to(Z,-budget,A,B,C) :: 'according to @(Z), it is not the case that @(A) and @(B) and @(C) are related as budget'.
#pred blawx_defeated(Z,budget,A,B,C) :: 'the conclusion in @(Z) that @(A) and @(B) and @(C) are related as budget is defeated'.
#pred blawx_defeated(Z,-budget,A,B,C) :: 'the conclusion in @(Z) that @(A) and @(B) and @(C) are related as budget is defeated'.
#pred blawx_initially(budget(A,B,C)) :: 'that @(A) and @(B) and @(C) are related as budget holds initially'.
#pred blawx_initially(-budget(A,B,C)) :: 'that it is not the case that @(A) and @(B) and @(C) are related as budget holds initially'.
#pred blawx_ultimately(budget(A,B,C)) :: 'that @(A) and @(B) and @(C) are related as budget holds ultimately'.
#pred blawx_ultimately(-budget(A,B,C)) :: 'that it is not the case that @(A) and @(B) and @(C) are related as budget holds ultimately'.
#pred blawx_as_of(budget(A,B,C),T) :: 'that @(A) and @(B) and @(C) are related as budget holds at @(T)'.
#pred blawx_as_of(-budget(A,B,C),T) :: 'that it is not the case that @(A) and @(B) and @(C) are related as budget holds at @(T)'.
#pred blawx_during(T1,budget(A,B,C),T2) :: 'that @(A) and @(B) and @(C) are related as budget held between @(T1) and @(T2)'.
#pred blawx_during(T1,-budget(A,B,C),T2) :: 'that it is not the case that @(A) and @(B) and @(C) are related as budget held between @(T1) and @(T2)'.
#pred blawx_becomes(budget(A,B,C),T) :: 'that @(A) and @(B) and @(C) are related as budget became true at @(T)'.
#pred blawx_becomes(-budget(A,B,C),T) :: 'that it is not the case that @(A) and @(B) and @(C) are related as budget became true at @(T)'.
#pred blawx_not_interrupted(Start,budget(A,B,C),End) :: '@(A) and @(B) and @(C) are related as budget remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-budget(A,B,C),End) :: 'it is not the case that @(A) and @(B) and @(C) are related as budget remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),budget(A,B,C),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-budget(A,B,C),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-budget(A,B,C),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(budget(A,B,C),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),budget(A,B,C),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-budget(A,B,C),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-budget(A,B,C),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(budget(A,B,C),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),budget(A,B,C),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-budget(A,B,C),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-budget(A,B,C),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(budget(A,B,C),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),budget(A,B,C),datetime(eot)) :- blawx_initially(budget(A,B,C)), blawx_ultimately(budget(A,B,C)), findall(Time,blawx_becomes(-budget(A,B,C),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-budget(A,B,C),datetime(eot)) :- blawx_initially(-budget(A,B,C)), blawx_ultimately(-budget(A,B,C)), findall(Time,blawx_becomes(budget(A,B,C),datetime(Time)),[]).
blawx_as_of(budget(A,B,C),datetime(Time)) :- blawx_initially(budget(A,B,C)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),budget(A,B,C),datetime(BeforeT)).
blawx_as_of(budget(A,B,C),datetime(Time)) :- blawx_becomes(budget(A,B,C),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),budget(A,B,C),datetime(Time)).
blawx_as_of(-budget(A,B,C),datetime(Time)) :- blawx_initially(-budget(A,B,C)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-budget(A,B,C),datetime(BeforeT)).
blawx_as_of(-budget(A,B,C),datetime(Time)) :- blawx_becomes(-budget(A,B,C),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-budget(A,B,C),datetime(Time)).
blawx_during(datetime(Start),budget(A,B,C),datetime(End)) :- blawx_becomes(budget(A,B,C),datetime(Start)), blawx_becomes(-budget(A,B,C),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),budget(A,B,C),datetime(End)).
blawx_during(datetime(bot),budget(A,B,C),datetime(End)) :- blawx_initially(budget(A,B,C)), blawx_becomes(-budget(A,B,C),datetime(End)), blawx_not_interrupted(datetime(bot),budget(A,B,C),datetime(End)).
blawx_during(datetime(Start),budget(A,B,C),datetime(eot)) :- blawx_ultimately(budget(A,B,C)), blawx_becomes(-budget(A,B,C),datetime(Start)), blawx_not_interrupted(datetime(Start),budget(A,B,C),datetime(eot)).
blawx_during(datetime(bot),budget(A,B,C),datetime(eot)) :- blawx_initially(budget(A,B,C)), blawx_ultimately(budget(A,B,C)), blawx_becomes(-budget(A,B,C),datetime(Start)), blawx_not_interrupted(datetime(bot),budget(A,B,C),datetime(eot)).
blawx_during(datetime(Start),-budget(A,B,C),datetime(End)) :- blawx_becomes(-budget(A,B,C),datetime(Start)), blawx_becomes(budget(A,B,C),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-budget(A,B,C),datetime(End)).
blawx_during(datetime(bot),-budget(A,B,C),datetime(End)) :- blawx_initially(-budget(A,B,C)), blawx_becomes(budget(A,B,C),datetime(End)), blawx_not_interrupted(datetime(bot),-budget(A,B,C),datetime(End)).
blawx_during(datetime(Start),-budget(A,B,C),datetime(eot)) :- blawx_ultimately(-budget(A,B,C)), blawx_becomes(budget(A,B,C),datetime(Start)), blawx_not_interrupted(datetime(Start),-budget(A,B,C),datetime(eot)).
blawx_during(datetime(bot),-budget(A,B,C),datetime(eot)) :- blawx_initially(-budget(A,B,C)), blawx_ultimately(-budget(A,B,C)), blawx_becomes(-budget(A,B,C),datetime(Start)), blawx_not_interrupted(datetime(bot),-budget(A,B,C),datetime(eot)).

according_to(sec_1_section,budget,C,Rate,Tmp) :- config(C),
timeout(C,Timeout),
retries(C,Retries),
Tmp is ( ( Timeout * Retries ) * Rate ).

% BLAWX CHECK DUPLICATES
holds(sec_1_section,budget,C,Rate,Tmp) :- according_to(sec_1_section,budget,C,Rate,Tmp).

% BLAWX CHECK DUPLICATES
  budget(C,Rate,Tmp) :- holds(sec_1_section,budget,C,Rate,Tmp).
