% generated by l4 blawx from mortality.l4 — raw concatenated s(CASP); tests live in the .blawx / tier-1 harness
% epistemics (R5): an input that is neither asserted, denied, nor abducible yields NO MODEL (loud), never a silent false

blawx_category(person).
blawx_category_nlg(person,"","is a person").
:- dynamic person/1.
#pred person(X) :: '@(X) is a person'.
#pred holds(user,person,X) :: 'it is provided as a fact that @(X) is a person'.
#pred holds(user,-person,X) :: 'it is provided as a fact that it is not the case that @(X) is a person'.
#pred holds(Z,person,X) :: 'the conclusion in @(Z) that @(X) is a person holds'.
#pred holds(Z,-person,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is a person holds'.
#pred according_to(Z,person,X) :: 'according to @(Z), @(X) is a person'.
#pred according_to(Z,-person,X) :: 'according to @(Z), it is not the case that @(X) is a person'.
#pred blawx_defeated(Z,person,X) :: 'the conclusion in @(Z) that @(X) is a person is defeated'.
#pred blawx_defeated(Z,-person,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is a person is defeated'.
#pred blawx_initially(person(X)) :: 'that @(X) is a person holds initially'.
#pred blawx_initially(-person(X)) :: 'that it is not the case that @(X) is a person holds initially'.
#pred blawx_ultimately(person(X)) :: 'that @(X) is a person holds ultimately'.
#pred blawx_ultimately(-person(X)) :: 'that it is not the case that @(X) is a person holds ultimately'.
#pred blawx_as_of(person(X),T) :: 'that @(X) is a person holds at @(T)'.
#pred blawx_as_of(-person(X),T) :: 'that it is not the case that @(X) is a person holds at @(T)'.
#pred blawx_during(T1,person(X),T2) :: 'that @(X) is a person held between @(T1) and @(T2)'.
#pred blawx_during(T1,-person(X),T2) :: 'that it is not the case that @(X) is a person held between @(T1) and @(T2)'.
#pred blawx_becomes(person(X),T) :: 'that @(X) is a person became true at @(T)'.
#pred blawx_becomes(-person(X),T) :: 'that it is not the case that @(X) is a person became true at @(T)'.
#pred blawx_not_interrupted(Start,person(X),End) :: '@(X) is a person remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-person(X),End) :: 'it is not the case that @(X) is a person remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),person(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-person(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-person(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(person(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),person(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-person(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-person(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(person(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),person(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-person(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-person(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(person(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),person(X),datetime(eot)) :- blawx_initially(person(X)), blawx_ultimately(person(X)), findall(Time,blawx_becomes(-person(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-person(X),datetime(eot)) :- blawx_initially(-person(X)), blawx_ultimately(-person(X)), findall(Time,blawx_becomes(person(X),datetime(Time)),[]).
blawx_as_of(person(X),datetime(Time)) :- blawx_initially(person(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),person(X),datetime(BeforeT)).
blawx_as_of(person(X),datetime(Time)) :- blawx_becomes(person(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),person(X),datetime(Time)).
blawx_as_of(-person(X),datetime(Time)) :- blawx_initially(-person(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-person(X),datetime(BeforeT)).
blawx_as_of(-person(X),datetime(Time)) :- blawx_becomes(-person(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-person(X),datetime(Time)).
blawx_during(datetime(Start),person(X),datetime(End)) :- blawx_becomes(person(X),datetime(Start)), blawx_becomes(-person(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),person(X),datetime(End)).
blawx_during(datetime(bot),person(X),datetime(End)) :- blawx_initially(person(X)), blawx_becomes(-person(X),datetime(End)), blawx_not_interrupted(datetime(bot),person(X),datetime(End)).
blawx_during(datetime(Start),person(X),datetime(eot)) :- blawx_ultimately(person(X)), blawx_becomes(-person(X),datetime(Start)), blawx_not_interrupted(datetime(Start),person(X),datetime(eot)).
blawx_during(datetime(bot),person(X),datetime(eot)) :- blawx_initially(person(X)), blawx_ultimately(person(X)), blawx_becomes(-person(X),datetime(Start)), blawx_not_interrupted(datetime(bot),person(X),datetime(eot)).
blawx_during(datetime(Start),-person(X),datetime(End)) :- blawx_becomes(-person(X),datetime(Start)), blawx_becomes(person(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-person(X),datetime(End)).
blawx_during(datetime(bot),-person(X),datetime(End)) :- blawx_initially(-person(X)), blawx_becomes(person(X),datetime(End)), blawx_not_interrupted(datetime(bot),-person(X),datetime(End)).
blawx_during(datetime(Start),-person(X),datetime(eot)) :- blawx_ultimately(-person(X)), blawx_becomes(person(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-person(X),datetime(eot)).
blawx_during(datetime(bot),-person(X),datetime(eot)) :- blawx_initially(-person(X)), blawx_ultimately(-person(X)), blawx_becomes(-person(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-person(X),datetime(eot)).
blawx_attribute(person,is_human,boolean).
blawx_attribute_nlg(is_human,not_applicable,"",not_applicable,"is human").
:- dynamic is_human/1.
#pred is_human(X) :: '@(X) is human'.
#pred holds(user,is_human,X) :: 'it is provided as a fact that @(X) is human'.
#pred holds(user,-is_human,X) :: 'it is provided as a fact that it is not the case that @(X) is human'.
#pred holds(Z,is_human,X) :: 'the conclusion in @(Z) that @(X) is human holds'.
#pred holds(Z,-is_human,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is human holds'.
#pred according_to(Z,is_human,X) :: 'according to @(Z), @(X) is human'.
#pred according_to(Z,-is_human,X) :: 'according to @(Z), it is not the case that @(X) is human'.
#pred blawx_defeated(Z,is_human,X) :: 'the conclusion in @(Z) that @(X) is human is defeated'.
#pred blawx_defeated(Z,-is_human,X) :: 'the conclusion in @(Z) that @(X) is human is defeated'.
#pred blawx_initially(is_human(X)) :: 'that @(X) is human holds initially'.
#pred blawx_initially(-is_human(X)) :: 'that it is not the case that @(X) is human holds initially'.
#pred blawx_ultimately(is_human(X)) :: 'that @(X) is human holds ultimately'.
#pred blawx_ultimately(-is_human(X)) :: 'that it is not the case that @(X) is human holds ultimately'.
#pred blawx_as_of(is_human(X),T) :: 'that @(X) is human holds at @(T)'.
#pred blawx_as_of(-is_human(X),T) :: 'that it is not the case that @(X) is human holds at @(T)'.
#pred blawx_during(T1,is_human(X),T2) :: 'that @(X) is human held between @(T1) and @(T2)'.
#pred blawx_during(T1,-is_human(X),T2) :: 'that it is not the case that @(X) is human held between @(T1) and @(T2)'.
#pred blawx_becomes(is_human(X),T) :: 'that @(X) is human became true at @(T)'.
#pred blawx_becomes(-is_human(X),T) :: 'that it is not the case that @(X) is human became true at @(T)'.
#pred blawx_not_interrupted(Start,is_human(X),End) :: '@(X) is human remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-is_human(X),End) :: 'it is not the case that @(X) is human remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),is_human(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-is_human(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-is_human(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(is_human(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),is_human(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-is_human(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-is_human(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(is_human(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),is_human(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-is_human(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-is_human(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(is_human(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),is_human(X),datetime(eot)) :- blawx_initially(is_human(X)), blawx_ultimately(is_human(X)), findall(Time,blawx_becomes(-is_human(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-is_human(X),datetime(eot)) :- blawx_initially(-is_human(X)), blawx_ultimately(-is_human(X)), findall(Time,blawx_becomes(is_human(X),datetime(Time)),[]).
blawx_as_of(is_human(X),datetime(Time)) :- blawx_initially(is_human(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),is_human(X),datetime(BeforeT)).
blawx_as_of(is_human(X),datetime(Time)) :- blawx_becomes(is_human(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),is_human(X),datetime(Time)).
blawx_as_of(-is_human(X),datetime(Time)) :- blawx_initially(-is_human(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-is_human(X),datetime(BeforeT)).
blawx_as_of(-is_human(X),datetime(Time)) :- blawx_becomes(-is_human(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-is_human(X),datetime(Time)).
blawx_during(datetime(Start),is_human(X),datetime(End)) :- blawx_becomes(is_human(X),datetime(Start)), blawx_becomes(-is_human(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),is_human(X),datetime(End)).
blawx_during(datetime(bot),is_human(X),datetime(End)) :- blawx_initially(is_human(X)), blawx_becomes(-is_human(X),datetime(End)), blawx_not_interrupted(datetime(bot),is_human(X),datetime(End)).
blawx_during(datetime(Start),is_human(X),datetime(eot)) :- blawx_ultimately(is_human(X)), blawx_becomes(-is_human(X),datetime(Start)), blawx_not_interrupted(datetime(Start),is_human(X),datetime(eot)).
blawx_during(datetime(bot),is_human(X),datetime(eot)) :- blawx_initially(is_human(X)), blawx_ultimately(is_human(X)), blawx_becomes(-is_human(X),datetime(Start)), blawx_not_interrupted(datetime(bot),is_human(X),datetime(eot)).
blawx_during(datetime(Start),-is_human(X),datetime(End)) :- blawx_becomes(-is_human(X),datetime(Start)), blawx_becomes(is_human(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-is_human(X),datetime(End)).
blawx_during(datetime(bot),-is_human(X),datetime(End)) :- blawx_initially(-is_human(X)), blawx_becomes(is_human(X),datetime(End)), blawx_not_interrupted(datetime(bot),-is_human(X),datetime(End)).
blawx_during(datetime(Start),-is_human(X),datetime(eot)) :- blawx_ultimately(-is_human(X)), blawx_becomes(is_human(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-is_human(X),datetime(eot)).
blawx_during(datetime(bot),-is_human(X),datetime(eot)) :- blawx_initially(-is_human(X)), blawx_ultimately(-is_human(X)), blawx_becomes(-is_human(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-is_human(X),datetime(eot)).
blawx_attribute(person,is_mortal,boolean).
blawx_attribute_nlg(is_mortal,not_applicable,"",not_applicable,"is mortal").
:- dynamic is_mortal/1.
#pred is_mortal(X) :: '@(X) is mortal'.
#pred holds(user,is_mortal,X) :: 'it is provided as a fact that @(X) is mortal'.
#pred holds(user,-is_mortal,X) :: 'it is provided as a fact that it is not the case that @(X) is mortal'.
#pred holds(Z,is_mortal,X) :: 'the conclusion in @(Z) that @(X) is mortal holds'.
#pred holds(Z,-is_mortal,X) :: 'the conclusion in @(Z) that it is not the case that @(X) is mortal holds'.
#pred according_to(Z,is_mortal,X) :: 'according to @(Z), @(X) is mortal'.
#pred according_to(Z,-is_mortal,X) :: 'according to @(Z), it is not the case that @(X) is mortal'.
#pred blawx_defeated(Z,is_mortal,X) :: 'the conclusion in @(Z) that @(X) is mortal is defeated'.
#pred blawx_defeated(Z,-is_mortal,X) :: 'the conclusion in @(Z) that @(X) is mortal is defeated'.
#pred blawx_initially(is_mortal(X)) :: 'that @(X) is mortal holds initially'.
#pred blawx_initially(-is_mortal(X)) :: 'that it is not the case that @(X) is mortal holds initially'.
#pred blawx_ultimately(is_mortal(X)) :: 'that @(X) is mortal holds ultimately'.
#pred blawx_ultimately(-is_mortal(X)) :: 'that it is not the case that @(X) is mortal holds ultimately'.
#pred blawx_as_of(is_mortal(X),T) :: 'that @(X) is mortal holds at @(T)'.
#pred blawx_as_of(-is_mortal(X),T) :: 'that it is not the case that @(X) is mortal holds at @(T)'.
#pred blawx_during(T1,is_mortal(X),T2) :: 'that @(X) is mortal held between @(T1) and @(T2)'.
#pred blawx_during(T1,-is_mortal(X),T2) :: 'that it is not the case that @(X) is mortal held between @(T1) and @(T2)'.
#pred blawx_becomes(is_mortal(X),T) :: 'that @(X) is mortal became true at @(T)'.
#pred blawx_becomes(-is_mortal(X),T) :: 'that it is not the case that @(X) is mortal became true at @(T)'.
#pred blawx_not_interrupted(Start,is_mortal(X),End) :: '@(X) is mortal remained the case between @(Start) and @(End)'.
#pred blawx_not_interrupted(Start,-is_mortal(X),End) :: 'it is not the case that @(X) is mortal remained the case between @(Start) and @(End)'.
blawx_not_interrupted(datetime(Start),is_mortal(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(-is_mortal(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(Start),-is_mortal(X),datetime(End)) :- Start \= bot, End \= eot, findall(Time,blawx_becomes(is_mortal(X),datetime(Time)),Times),blawx_list_not_between(Times,Start,End).
blawx_not_interrupted(datetime(bot),is_mortal(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(-is_mortal(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(bot),-is_mortal(X),datetime(End)) :- End \= eot, findall(Time,blawx_becomes(is_mortal(X),datetime(Time)),Times),blawx_list_not_before(Times,End).
blawx_not_interrupted(datetime(Start),is_mortal(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(-is_mortal(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(Start),-is_mortal(X),datetime(eot)) :- Start \= bot, findall(Time,blawx_becomes(is_mortal(X),datetime(Time)),Times),blawx_list_not_after(Times,Start).
blawx_not_interrupted(datetime(bot),is_mortal(X),datetime(eot)) :- blawx_initially(is_mortal(X)), blawx_ultimately(is_mortal(X)), findall(Time,blawx_becomes(-is_mortal(X),datetime(Time)),[]).
blawx_not_interrupted(datetime(bot),-is_mortal(X),datetime(eot)) :- blawx_initially(-is_mortal(X)), blawx_ultimately(-is_mortal(X)), findall(Time,blawx_becomes(is_mortal(X),datetime(Time)),[]).
blawx_as_of(is_mortal(X),datetime(Time)) :- blawx_initially(is_mortal(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),is_mortal(X),datetime(BeforeT)).
blawx_as_of(is_mortal(X),datetime(Time)) :- blawx_becomes(is_mortal(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),is_mortal(X),datetime(Time)).
blawx_as_of(-is_mortal(X),datetime(Time)) :- blawx_initially(-is_mortal(X)), BeforeT #< Time,blawx_not_interrupted(datetime(bot),-is_mortal(X),datetime(BeforeT)).
blawx_as_of(-is_mortal(X),datetime(Time)) :- blawx_becomes(-is_mortal(X),datetime(BeforeT)),BeforeT #< Time,blawx_not_interrupted(datetime(BeforeT),-is_mortal(X),datetime(Time)).
blawx_during(datetime(Start),is_mortal(X),datetime(End)) :- blawx_becomes(is_mortal(X),datetime(Start)), blawx_becomes(-is_mortal(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),is_mortal(X),datetime(End)).
blawx_during(datetime(bot),is_mortal(X),datetime(End)) :- blawx_initially(is_mortal(X)), blawx_becomes(-is_mortal(X),datetime(End)), blawx_not_interrupted(datetime(bot),is_mortal(X),datetime(End)).
blawx_during(datetime(Start),is_mortal(X),datetime(eot)) :- blawx_ultimately(is_mortal(X)), blawx_becomes(-is_mortal(X),datetime(Start)), blawx_not_interrupted(datetime(Start),is_mortal(X),datetime(eot)).
blawx_during(datetime(bot),is_mortal(X),datetime(eot)) :- blawx_initially(is_mortal(X)), blawx_ultimately(is_mortal(X)), blawx_becomes(-is_mortal(X),datetime(Start)), blawx_not_interrupted(datetime(bot),is_mortal(X),datetime(eot)).
blawx_during(datetime(Start),-is_mortal(X),datetime(End)) :- blawx_becomes(-is_mortal(X),datetime(Start)), blawx_becomes(is_mortal(X),datetime(End)), Start #< End, blawx_not_interrupted(datetime(Start),-is_mortal(X),datetime(End)).
blawx_during(datetime(bot),-is_mortal(X),datetime(End)) :- blawx_initially(-is_mortal(X)), blawx_becomes(is_mortal(X),datetime(End)), blawx_not_interrupted(datetime(bot),-is_mortal(X),datetime(End)).
blawx_during(datetime(Start),-is_mortal(X),datetime(eot)) :- blawx_ultimately(-is_mortal(X)), blawx_becomes(is_mortal(X),datetime(Start)), blawx_not_interrupted(datetime(Start),-is_mortal(X),datetime(eot)).
blawx_during(datetime(bot),-is_mortal(X),datetime(eot)) :- blawx_initially(-is_mortal(X)), blawx_ultimately(-is_mortal(X)), blawx_becomes(-is_mortal(X),datetime(Start)), blawx_not_interrupted(datetime(bot),-is_mortal(X),datetime(eot)).

according_to(sec_1_section,is_mortal,P) :- person(P),
is_human(P).

% BLAWX CHECK DUPLICATES
holds(sec_1_section,is_mortal,P) :- according_to(sec_1_section,is_mortal,P).

% BLAWX CHECK DUPLICATES
  is_mortal(P) :- holds(sec_1_section,is_mortal,P).
