-- | Render a 'BlawxDoc' to the Blockly XML that pairs with "L4.Blawx.Emit"'s
-- s(CASP) — the @xml_content@ side of every @blawx.workspace@ and
-- @blawx.blawxtest@ row (BLAWX-EXPORT-SPEC R12, phase P3).
--
-- __The fixpoint is the contract, and it runs the other way round.__
-- 'L4.Blawx.Emit.renderScasp' reproduces what @scasp_generator.js@ /would/
-- emit; this module emits the blocks that /make/ it emit that. The Blawx
-- editor regenerates @scasp_encoding@ from the deserialised blocks on every
-- save, so the chain that has to hold is
-- @textToDom → domToWorkspace → sCASP.workspaceToCode@ (@buttons.js:444-447@,
-- @:24@) landing back on the same bytes. Everything below is derived from the
-- block definitions (@blawx-blocks.js@), the mutation restorers
-- (@mutators.js@) and the generator (@scasp_generator.js@) at Blawx commit
-- @02eded1@; the per-block templates, with line citations for every claim, are
-- in @p3-design\/xml-plan.md@, and @etc\/blawx-fixpoint-harness.mjs@ executes
-- the chain headlessly.
--
-- Six facts shape everything here:
--
-- 1. __Top-level order is decided by @y@, not by document order.__
--    @workspaceToCode@ takes @getTopBlocks(true)@, sorted by
--    @y + sin(3°)·x@. Single-column layout with a strictly increasing @y@ is
--    therefore load-bearing, not cosmetic (spec §8.12's delegated
--    sub-decision).
-- 2. __A @[BBlock]@ stack is not one Blockly stack.__ @unattributed_fact@,
--    @unattributed_constraint@, @assume@, @attributed_rule@ and @query@ have
--    no @previousStatement@: they can only be roots, and @workspaceToCode@
--    joins roots with a blank line. Where a stack becomes several roots is
--    'L4.Blawx.IR.blockRuns', which "L4.Blawx.Emit" reads too — that is the
--    only way the blank lines in the two renderings can agree.
-- 3. __A failed connection type-check is silent__ in the XML path
--    (@Connection.connect@ returns a boolean that @domToBlockHeadless@
--    ignores): an incompatible child is created but left detached, becomes a
--    top-level block, and emits a spurious extra line. So every @check@ in
--    the block definitions is honoured here, and a goal that cannot satisfy
--    one is reported as an 'XmlGap' rather than emitted as XML that would
--    regenerate different bytes.
-- 4. __The checks are not all in the block definitions, and not all in the
--    mutators.__ @attributes.js@ — loaded by both editor templates
--    (@blawx.html:168@, @test.html:164@) and registered on @demoWorkspace@
--    (@attributes.js:21@) — reinstalls the connection checks of every
--    @attribute_selector@ on every @BLOCK_CREATE@, __with no @if
--    (attributeType)@ guard__ (contrast @mutators.js:165@). An absent or
--    empty @attributetype@ therefore does not mean \"no check\": it means
--    @blawxTypeToBlocklyType(\"\") === 'OBJECT'@. Under the @ov@ order the
--    /object/ slot is pinned to @['OBJECT','VARIABLE']@ unconditionally, and
--    @Connection.setCheck@ unplugs an already-connected incompatible child.
--    Measured: with @attributetype=\"\"@ six golden rows regenerated
--    differently (@[X | Rest].@ as its own naked top-level statement, and
--    @running_total(,)@ for the clause that lost both operands).
-- 5. __@\<mutation\>@ comes first__ and carries the predicate\/category names
--    the restorers read: several generator arms read a /mutation-restored
--    property/, never a field (@this.blawxAttributeName@, @this.arity@,
--    @block.section_reference@), so a missing mutation regenerates wrong code
--    or throws.
-- 6. __Menu-cache attributes (@category_list@, @attribute_list@,
--    @type_list@) are omitted__: every restorer that reads one has an
--    explicit reverse-compatibility branch, and a Blawx-authored example
--    ships without them.
--
-- __Slots with no structural choice.__ Three inputs are pinned to
-- @[OBJECT,VARIABLE]@ no matter what we write: @attribute_selector@'s object
-- slot (fact 4 — in /either/ argument order, so swapping does not help),
-- @unary_attribute_selector@'s @first_element@ (hardcoded in the JSON,
-- @blawx-blocks.js:3041-3048@, and its mutator never calls @setCheck@,
-- @mutators.js:181-195@) and @new_object_category@'s @object@. A list-valued
-- argument in one of those — @running_total([],0)@, @all_positive([X|Rest])@
-- — therefore has no /structural/ image anywhere in the 127-block inventory
-- (@relationship_selector@ starts at arity 3).
--
-- The answer is 'objectSlot': fall back to an @object_selector@ whose label
-- is the term's own s(CASP) text. Its output is @OBJECT@, so it survives
-- every pin; its field is a @field_label_serializable@ with no validator, so
-- it round-trips verbatim; and its generator arm is
-- @this.getFieldValue('object_name')@ (@scasp_generator.js:471-474@), so the
-- regenerated bytes are exactly the ones "L4.Blawx.Emit" wrote. What is lost
-- is /editability/ of that subterm in the UI, and only that — which is
-- strictly better than the alternative, a blank canvas whose Save deletes the
-- rule. The surrogate is used ONLY where the structural image would be torn
-- off; @[X | Rest]@ in a value slot still gets real @head_tail@ blocks, via
-- an @attributetype@ derived from the operand.
--
-- __Unrepresentable constructs.__ What the surrogate cannot rescue yields an
-- 'XmlGap' and an empty @xml_content@ rather than XML that would regenerate
-- different bytes. Such a row is a data-loss trap, not a neutral omission, so
-- the gaps are carried out to the CLI (@L4.Blawx.Emit.blawxXmlGaps@) and no
-- corpus golden is allowed to contain one.
module L4.Blawx.EmitXml
  ( -- * The renderer
    renderDocXml
  , BlawxXml (..)
    -- * What has no block image
  , XmlGap (..)
  , renderXmlGap
  ) where

import Base
import qualified Base.Map as Map
import qualified Base.Text as Text
import Data.Char (isAsciiLower, isAsciiUpper, isDigit)
import Data.Ratio (denominator, numerator)
import qualified Data.Set as Set
import Numeric (showHex)

import L4.Blawx.IR

-- ---------------------------------------------------------------------------
-- The public surface
-- ---------------------------------------------------------------------------

-- | Every row's Blockly XML, in the order the @.blawx@ stream stores them:
-- the workspaces, then the tests. Block @id@s are drawn from ONE
-- document-wide counter in that order, so the whole document is stable under
-- re-emission and two rows can never share an id (they are loaded into one
-- editor session by @drawers.js@).
--
-- A row with no blocks — and a row carrying a construct with no block image —
-- is the empty string, which is what the loader's truthiness guard
-- (@buttons.js:444@) expects and what the shipped @root_section@ of the
-- evidence example contains. Every gap is listed in 'bxGaps'.
data BlawxXml = MkBlawxXml
  { bxWorkspaces :: ![Text]     -- ^ one per 'BlawxDoc.bdWorkspaces' entry
  , bxTests      :: ![Text]     -- ^ one per 'BlawxDoc.bdTests' entry
  , bxGaps       :: ![XmlGap]   -- ^ why a row is empty, in row order
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | One construct with no Blockly image, and the row it sank.
data XmlGap = MkXmlGap
  { xgRow  :: !Text   -- ^ workspace or test name (filled in by 'renderDocXml')
  , xgWhat :: !Text   -- ^ the construct, as text
  , xgWhy  :: !Text   -- ^ which block definition rules it out
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

renderXmlGap :: XmlGap -> Text
renderXmlGap g = g.xgRow <> ": " <> g.xgWhat <> " — " <> g.xgWhy

-- | The per-row @xml_content@ values. Rows are rendered in stream order with
-- a shared id counter; a gapped row consumes no ids, so ids stay stable when
-- an unrelated row gains or loses a gap.
renderDocXml :: BlawxDoc -> BlawxXml
renderDocXml doc =
  MkBlawxXml
    { bxWorkspaces = map value wsResults
    , bxTests      = map value testResults
    , bxGaps       = [g | Left g <- results]
    }
 where
  sym = documentSymbols doc
  rows =
    [ (renderSectionRef ws.bwName, ws.bwStacks) | ws <- doc.bdWorkspaces ]
      <> [ (t.btName, t.btStacks) | t <- doc.bdTests ]
  results = snd (mapAccumL step 1 rows)
  (wsResults, testResults) = splitAt (length doc.bdWorkspaces) results
  value = either (const "") id
  step :: Int -> (Text, [[BBlock]]) -> (Int, Either XmlGap Text)
  step i (name, stacks) = case build of
    Left g    -> (i, Left g {xgRow = name})
    Right rts ->
      let (i', numbered) = mapAccumL numberBlocks i rts
      in  (i', Right (rowText (layoutColumn numbered)))
   where
    build = do
      rts <- rowRoots doc sym stacks
      traverse_ representable rts
      pure rts

-- ---------------------------------------------------------------------------
-- A tiny XML tree
-- ---------------------------------------------------------------------------

-- | Built as a tree rather than as text so the id counter can be assigned in
-- one document-order pass ('numberBlocks') and the layout in another
-- ('layoutColumn'), which is also why attributes come out in Blockly's own
-- order (@type@, @id@, @x@, @y@).
data XNode
  = XElem !Text ![(Text, Text)] ![XNode]
  | XText !Text

-- | Never self-closing: @Blockly.Xml.domToText@ round-trips through
-- @XMLSerializer@, which writes @\<mutation …\>\<\/mutation\>@ and
-- @\<field name=\"prefix\"\>\<\/field\>@, and matching it keeps our XML
-- diffable against a re-save.
renderNode :: XNode -> Text
renderNode = \case
  XText t -> escapeText t
  XElem name attrs kids ->
    "<" <> name
      <> Text.concat [" " <> k <> "=\"" <> escapeAttr v <> "\"" | (k, v) <- attrs]
      <> ">"
      <> Text.concat (map renderNode kids)
      <> "</" <> name <> ">"

-- | Text content: @&@, @\<@, @\>@ — and @\\r@, which XML 1.0 end-of-line
-- normalisation rewrites to @\\n@ in element content just as it does in an
-- attribute value, so a literal CR in a @\<field\>@ would come back changed.
-- Apostrophes are NOT escaped — the NLG slots are full of them (@\'s score
-- is@) and escaping them would change the field value the generator reads
-- back. Tab and LF survive normalisation in element content and stay literal.
--
-- 'unrepresentable' characters are dropped here for totality only: they are
-- rejected up front by 'representable', which turns them into an 'XmlGap'
-- rather than a silent rewrite.
escapeText :: Text -> Text
escapeText = Text.concatMap $ \case
  '&'  -> "&amp;"
  '<'  -> "&lt;"
  '>'  -> "&gt;"
  '\r' -> "&#13;"
  c | unrepresentable c -> ""
    | otherwise -> Text.singleton c

-- | Attribute values: additionally @\"@ (the evidence ships
-- @&quot;@-escaped attributes), and the three legal whitespace controls as
-- character references — an XML parser normalises literal newlines and tabs
-- in an attribute value to spaces, which would corrupt the datum silently.
-- Nothing we put in an attribute can contain them today (every mutation
-- attribute is a Blawx atom, a section ref, a type keyword or @ov@); this is
-- the belt for the braces.
escapeAttr :: Text -> Text
escapeAttr = Text.concatMap $ \case
  '&'  -> "&amp;"
  '<'  -> "&lt;"
  '>'  -> "&gt;"
  '"'  -> "&quot;"
  '\n' -> "&#10;"
  '\r' -> "&#13;"
  '\t' -> "&#9;"
  c | unrepresentable c -> ""
    | otherwise -> Text.singleton c

-- | C0 controls other than tab\/LF\/CR cannot be represented in XML 1.0 at
-- all — not even as a character reference.
unrepresentable :: Char -> Bool
unrepresentable c = c < ' ' && c /= '\t' && c /= '\n' && c /= '\r'

-- | Reject a row whose XML would carry a character XML 1.0 cannot express.
-- Dropping it silently is the one thing this module refuses to do anywhere
-- else — 'variableNode' and 'predicateName' turn a would-be silent rewrite
-- into an 'XmlGap' for exactly this reason — and a dropped control character
-- produces XML that deserialises cleanly and regenerates /different/ text.
--
-- Unreachable in this corpus ('L4.Blawx.Lower' sanitises every NLG slot), so
-- this is the guard being consistent, not a live bug.
representable :: XNode -> Build ()
representable = \case
  XText t -> check t
  XElem _ attrs kids -> traverse_ (check . snd) attrs *> traverse_ representable kids
 where
  check t = case Text.find unrepresentable t of
    Nothing -> pure ()
    Just c ->
      gap ("field text " <> Text.textShow t)
          ( "contains U+"
              <> Text.justifyRight 4 '0' (Text.pack (showHex (fromEnum c) ""))
              <> ", which XML 1.0 cannot represent even as a character reference" )

blockE :: Text -> [XNode] -> XNode
blockE ty kids = XElem "block" [("type", ty)] kids

-- | Every @\<mutation\>@ carries the xhtml namespace, as Blockly's serialiser
-- writes it (@document.createElement@ in the restorers puts the element in
-- the HTML namespace).
mutationE :: [(Text, Text)] -> XNode
mutationE attrs =
  XElem "mutation" (("xmlns", "http://www.w3.org/1999/xhtml") : attrs) []

fieldE :: Text -> Text -> XNode
fieldE name v = XElem "field" [("name", name)] [XText v]

valueE :: Text -> XNode -> XNode
valueE name b = XElem "value" [("name", name)] [b]

-- | A statement input. Emitted only when there is a block to put in it: an
-- empty @\<statement\>@ would be a hole the loader has to guess at, and the
-- generator's @getInputTargetBlock@ returns @null@ either way.
statementE :: Text -> Maybe XNode -> [XNode]
statementE name = foldMap (\b -> [XElem "statement" [("name", name)] [b]])

-- | Chain blocks the way Blockly does: each successor is the @\<next\>@ child
-- of its predecessor, and @\<next\>@ is the last child of a block.
chainBlocks :: [XNode] -> Maybe XNode
chainBlocks = foldr step Nothing
 where
  step b acc = Just (maybe b (\rest -> appendKid b (XElem "next" [] [rest])) acc)
  appendKid (XElem n as ks) k = XElem n as (ks <> [k])
  appendKid t _ = t

-- ---------------------------------------------------------------------------
-- Ids and layout
-- ---------------------------------------------------------------------------

-- | @Block@'s constructor takes any non-empty, non-duplicate id verbatim
-- (@this.id = c && !a.getBlockById(c) ? c : genUid()@), so ids are a
-- 9-character @l4b@ + zero-padded counter: deterministic (goldens are
-- stable), in a charset that needs no XML escaping, and — being 9 characters
-- where @genUid@ produces exactly 20 — incapable of colliding with a
-- Blockly-generated id on re-save.
numberBlocks :: Int -> XNode -> (Int, XNode)
numberBlocks i = \case
  XText t -> (i, XText t)
  XElem "block" attrs kids ->
    let (i', kids') = mapAccumL numberBlocks (i + 1) kids
    in  (i', XElem "block" (attrs <> [("id", blockId i)]) kids')
  XElem n attrs kids ->
    let (i', kids') = mapAccumL numberBlocks i kids
    in  (i', XElem n attrs kids')
 where
  blockId k = "l4b" <> Text.justifyRight 6 '0' (Text.textShow k)

-- | Single-column auto-layout (the delegated R12 sub-decision). Only
-- monotonicity in @y@ is load-bearing — @workspaceToCode@ sorts the top
-- blocks by @y + sin(3°)·x@, and a constant @x@ makes the second term vanish,
-- so the regenerated order equals our emission order. The pitch is legibility
-- only: enough vertical room for the rows the root actually draws.
layoutColumn :: [XNode] -> [XNode]
layoutColumn = go 40
 where
  go _ [] = []
  go y (r : rs) = place y r : go (y + 48 + 30 * blockRows r) rs
  place y (XElem n as ks) = XElem n (as <> [("x", "40"), ("y", Text.textShow (y :: Int))]) ks
  place _ t = t

-- | How many rows a root draws, for the pitch: the multi-input declaration
-- blocks and @attributed_rule@ render three rows apiece, everything else one.
blockRows :: XNode -> Int
blockRows = \case
  XElem "block" attrs kids -> weight (lookup "type" attrs) + sum (map blockRows kids)
  XElem _ _ kids -> sum (map blockRows kids)
  XText _ -> 0
 where
  weight ty
    | ty `elem` map Just tall = 3
    | otherwise = 1
  tall =
    [ "new_category_declaration"
    , "new_attribute_declaration"
    , "relationship_declaration"
    , "attributed_rule"
    ] :: [Text]

-- | The envelope. Newlines appear only between root @\<block\>@ elements (and
-- around them): @domToWorkspace@ skips non-element children of @\<xml\>@, so
-- that whitespace is inert — but a newline anywhere below a root would land
-- in a @\<field\>@'s @textContent@ and corrupt the field value. Never
-- pretty-print inside a block.
rowText :: [XNode] -> Text
rowText [] = ""
rowText roots =
  "<xml xmlns=\"https://developers.google.com/blockly/xml\">\n"
    <> Text.intercalate "\n" (map renderNode roots)
    <> "\n</xml>"

-- ---------------------------------------------------------------------------
-- The document's own symbol table
-- ---------------------------------------------------------------------------

-- | Which block a predicate goal becomes is keyed by arity and by how the
-- document declares the predicate, so the declarations are indexed first.
--
-- Undeclared predicates are normal and unavoidable (@member\/2@,
-- @running_total\/2@, the @findall@ generators): every selector's generator
-- arm reads its predicate name from a mutation-restored property, never from
-- a declaration, so the selectors work for them — only the UI's display text
-- degrades.
data BlockSym = MkBlockSym
  { syCats  :: !(Set Text)
  , syAttrs :: !(Map Text BAttributeDecl)
  , syRels  :: !(Map Text BRelationshipDecl)
  }

documentSymbols :: BlawxDoc -> BlockSym
documentSymbols doc =
  MkBlockSym
    { syCats  = Set.fromList [bNameText d.bcName | BDeclareCategory d <- blocks]
    , syAttrs = Map.fromList [(bNameText d.baName, d) | BDeclareAttribute d <- blocks]
    , syRels  = Map.fromList [(bNameText d.brName, d) | BDeclareRelationship d <- blocks]
    }
 where
  blocks = concat (concatMap (\ws -> ws.bwStacks) doc.bdWorkspaces)

-- ---------------------------------------------------------------------------
-- Connection types
-- ---------------------------------------------------------------------------

-- | The Blockly output type of a term's block, for the connection checks that
-- decide whether a value child attaches at all (fact 3 in the module header).
termOutput :: BTerm -> Text
termOutput = \case
  BTVar _  -> "VARIABLE"
  BTNum _  -> "Number"
  BTAtom _ -> "OBJECT"
  BTNil    -> "LIST"
  BTCons{} -> "LIST"

-- | @blawxTypeToBlocklyType@ (@mutators.js:1-21@): anything unrecognised —
-- including a category atom — is @OBJECT@.
blocklyType :: BValueType -> Text
blocklyType = \case
  BVBoolean    -> "Boolean"
  BVNumber     -> "Number"
  BVDate       -> "DATE"
  BVTime       -> "TIME"
  BVDatetime   -> "DATETIME"
  BVDuration   -> "DURATION"
  BVList       -> "LIST"
  BVCategory _ -> "OBJECT"

accepts :: [Text] -> BTerm -> Bool
accepts checks t = termOutput t `elem` checks

-- | The Blawx type keyword whose 'blocklyType' matches a term, for a slot
-- with no declaration to take the type from. @object@ is unrecognised by
-- @blawxTypeToBlocklyType@ and therefore maps to @OBJECT@, which is also what
-- a variable slot wants (@VARIABLE@ is in every restored check).
inferredType :: BTerm -> Text
inferredType t = case termOutput t of
  "LIST"   -> "list"
  "Number" -> "number"
  _        -> "object"

-- ---------------------------------------------------------------------------
-- Gaps
-- ---------------------------------------------------------------------------

type Build = Either XmlGap

gap :: Text -> Text -> Build a
gap what why = Left MkXmlGap {xgRow = "", xgWhat = what, xgWhy = why}

-- ---------------------------------------------------------------------------
-- Roots: stacks, runs and wrappers
-- ---------------------------------------------------------------------------

-- | One 'BWorkspace' \/ 'BTest' body. A stack becomes one /or more/ roots:
-- the wrapper blocks have no @previousStatement@, so a maximal run of
-- declarations and facts shares one @unattributed_fact@ while every
-- constraint, abducible, rule and query is a root of its own — which is
-- exactly where @workspaceToCode@'s blank line between roots comes from.
rowRoots :: BlawxDoc -> BlockSym -> [[BBlock]] -> Build [XNode]
rowRoots doc sym stacks =
  concat
    <$> traverse
      (traverse (rootNode doc sym) . blockRuns)
      (filter (not . null) stacks)

rootNode :: BlawxDoc -> BlockSym -> BRun -> Build XNode
rootNode doc sym = \case
  BRunMembers ms -> do
    kids <- traverse (memberNode sym) ms
    pure (blockE "unattributed_fact" (statementE "statements" (chainBlocks kids)))
  BRunRoot b -> case b of
    BConstraint goals -> do
      kids <- traverse (goalNode sym) goals
      pure (blockE "unattributed_constraint" (statementE "conditions" (chainBlocks kids)))
    BAbducible p args -> do
      kid <- predicateNode sym p args
      pure (blockE "assume" (statementE "statements" (Just kid)))
    BQuery p args -> do
      kid <- predicateNode sym p args
      pure (blockE "query" (statementE "query" (Just kid)))
    BAttributedRule r -> ruleNode doc sym r
    other -> do
      kid <- memberNode sym other
      pure (blockE "unattributed_fact" (statementE "statements" (Just kid)))

-- | A statement-position member of an @unattributed_fact@ stack.
memberNode :: BlockSym -> BBlock -> Build XNode
memberNode sym = \case
  BDeclareCategory d     -> categoryDeclNode d
  BDeclareAttribute d    -> attributeDeclNode d
  BDeclareRelationship d -> relationshipDeclNode d
  BFact True p args      -> predicateNode sym p args
  BFact False p args      -> negatedNode "logical_negation" "negated_statement" <$> predicateNode sym p args
  b                      -> gap (blockLabel b) "not a statement-position block"

blockLabel :: BBlock -> Text
blockLabel = \case
  BDeclareCategory d     -> "category " <> bNameText d.bcName
  BDeclareAttribute d    -> "attribute " <> bNameText d.baName
  BDeclareRelationship d -> "relationship " <> bNameText d.brName
  BAttributedRule r      -> "rule concluding " <> bNameText r.brConclusion.bcPred
  BFact _ p _            -> "fact " <> bNameText p
  BConstraint _          -> "constraint"
  BAbducible p _         -> "abducible " <> bNameText p
  BQuery p _             -> "query " <> bNameText p

negatedNode :: Text -> Text -> XNode -> XNode
negatedNode ty slot inner = blockE ty [XElem "statement" [("name", slot)] [inner]]

-- ---------------------------------------------------------------------------
-- The attributed rule
-- ---------------------------------------------------------------------------

-- | @attributed_rule@ + its @doc_selector@. Field order is Blockly's
-- serialisation order — all fields (in @inputList@ × @fieldRow@ order) before
-- all inputs — which is why the two checkboxes precede @conditions@ even
-- though they sit on later inputs.
--
-- @inapplicable@ is always @FALSE@ (Mode A): @TRUE@ would make the generator
-- inject a @blawx_applies(…)@ goal after every category condition, which
-- 'L4.Blawx.Emit.ruleTriple' does not emit.
ruleNode :: BlawxDoc -> BlockSym -> BRule -> Build XNode
ruleNode doc sym r = do
  conds <- traverse (goalNode sym) r.brConditions
  concl <- conclusionNode sym r.brConclusion
  pure $
    blockE
      "attributed_rule"
      ( [ fieldE "defeasible" (if r.brDefeasible then "TRUE" else "FALSE")
        , fieldE "inapplicable" "FALSE"
        ]
          <> statementE "conditions" (chainBlocks conds)
          <> [ valueE "source" $
                 blockE
                   "doc_selector"
                   -- MANDATORY: sCASP['doc_selector'] reads the
                   -- mutation-restored block.section_reference and calls
                   -- .toLowerCase() on it; without the mutation that is a
                   -- TypeError on load. doc_part_name is display-only.
                   [ mutationE [("section_reference", renderSectionRef r.brSection)]
                   , fieldE "doc_part_name" (docPartLabel doc r.brSection)
                   ]
             ]
          <> statementE "conclusion" (Just concl)
      )

conclusionNode :: BlockSym -> BConclusion -> Build XNode
conclusionNode sym c
  | c.bcSign = predicateNode sym c.bcPred c.bcArgs
  | otherwise =
      negatedNode "logical_negation" "negated_statement" <$> predicateNode sym c.bcPred c.bcArgs

-- | The @doc_selector@'s visible label. Display-only (the generator reads the
-- mutation), so this is legibility: the document's initials and the section
-- number, in the shape the evidence example uses (@LA 1@ for /Life Act/
-- section 1).
docPartLabel :: BlawxDoc -> BSectionRef -> Text
docPartLabel doc = \case
  BRoot -> doc.bdName
  BSec i
    | Text.null initials -> doc.bdName <> " " <> Text.textShow i
    | otherwise -> initials <> " " <> Text.textShow i
 where
  initials = Text.pack [c | w <- Text.words doc.bdName, Just (c, _) <- [Text.uncons w], isAsciiUpper c]

-- ---------------------------------------------------------------------------
-- Goals
-- ---------------------------------------------------------------------------

goalNode :: BlockSym -> BGoal -> Build XNode
goalNode sym = \case
  BGCall True p args -> predicateNode sym p args
  BGCall False p args ->
    negatedNode "logical_negation" "negated_statement" <$> predicateNode sym p args
  BGNaf p args ->
    negatedNode "default_negation" "default_negated_statement" <$> predicateNode sym p args
  BGCompare op x y -> do
    -- numerical_constraint, not comparison: the latter emits infix `X >= Y`.
    -- Both inputs check ["VARIABLE","Number"].
    a <- comparand x
    b <- comparand y
    pure $
      blockE
        "numerical_constraint"
        [ fieldE "operator" (cmpField op)
        , valueE "first_comparator" a
        , valueE "second_comparator" b
        ]
  BGUnify x y -> do
    -- variable_assignment, not object_equality: same emitted text, but its
    -- `value` input has NO check, where object_equality would orphan a
    -- numeric or list right-hand side.
    unless (accepts ["VARIABLE"] x) $
      gap ("unification " <> termLabel x <> " = " <> termLabel y)
          "variable_assignment's `variable` input checks VARIABLE"
    a <- termNode x
    b <- termNode y
    pure (blockE "variable_assignment" [valueE "variable" a, valueE "value" b])
  BGDiseq x y -> do
    -- object_disequality's two inputs both check [VARIABLE,OBJECT], so both
    -- are 'objectSlot's.
    a <- objectSlot x
    b <- objectSlot y
    pure (blockE "object_disequality" [valueE "first_object" a, valueE "second_object" b])
  BGIs v e -> do
    -- calculation's `calculation` input checks "Number", which a bare
    -- `variable` block (output VARIABLE) does not satisfy.
    unless (arithOutput e == "Number") $
      gap ("is-goal " <> varText v <> " is " <> arithLabel e)
          "calculation's `calculation` input checks Number; a bare variable outputs VARIABLE"
    out <- variableNode v
    rhs <- arithNode e
    pure (blockE "calculation" [valueE "variable" out, valueE "calculation" rhs])
  BGFindall tmpl body out -> do
    kids <- traverse (goalNode sym) body
    l <- variableNode out
    t <- variableNode tmpl
    -- The XML argument order is inverted relative to the emitted text:
    -- list_name is the output, variable_name the template.
    pure $
      blockE
        "collect_list"
        ([valueE "list_name" l, valueE "variable_name" t] <> statementE "search" (chainBlocks kids))
  BGAggregate fn list out -> do
    o <- variableNode out
    l <- variableNode list
    pure $
      blockE
        "list_aggregation"
        [fieldE "aggregation" (aggField fn), valueE "output" o, valueE "list" l]
 where
  comparand t = do
    unless (accepts ["VARIABLE", "Number"] t) $
      gap ("comparand " <> termLabel t) "numerical_constraint's inputs check [VARIABLE,Number]"
    termNode t

-- | The dropdown /value/ is the atom the generator splices into
-- @blawx_comparison(X,op,Y)@, so this must agree with
-- 'L4.Blawx.Emit'\'s @cmpAtom@ exactly.
cmpField :: BCmpOp -> Text
cmpField = \case
  BEq  -> "eq"
  BNeq -> "neq"
  BGt  -> "gt"
  BGte -> "gte"
  BLt  -> "lt"
  BLte -> "lte"

-- | The dropdown value and the emitted predicate DIFFER here: the generator
-- maps @cnt@\/@ave@ to @count_blawx_list@\/@average_blawx_list@. These are
-- the field values, not 'L4.Blawx.Emit'\'s @aggAtom@ spellings.
aggField :: BAggFn -> Text
aggField = \case
  BCount   -> "cnt"
  BSum     -> "sum"
  BAverage -> "ave"
  BMin     -> "min"
  BMax     -> "max"

-- ---------------------------------------------------------------------------
-- Predicate goals: which selector block, and its mutation
-- ---------------------------------------------------------------------------

-- | A predicate application, dispatched by arity and by how the document
-- declares the predicate. Every arm's mutation carries the predicate name,
-- because that is where the generator reads it from.
predicateNode :: BlockSym -> BName -> [BTerm] -> Build XNode
predicateNode sym p args = case args of
  [] ->
    gap ("goal " <> n)
        "no Blawx block applies a zero-argument predicate"
  [a]
    | Set.member n sym.syCats -> do
        -- object_category + category_selector, NOT new_object_category.
        -- Both arms generate identical bytes (scasp_generator.js:311-316 vs
        -- :1161-1166, each @category(object)@), but new_object_category holds
        -- the category in a dropdown that updateLocalCategories rewrites
        -- (blawx-blocks.js:5586-5589 -> updateDropDownOptions snap-to-first).
        -- On the TEST editor page the workspace auto-load races window.onload
        -- populating knownCategories, so the dropdown is validated against an
        -- empty list and snapped, then re-snapped to the FIRST declared
        -- category — measured in the tier-2 UI drive: scores/q5 stored
        -- @student(b1)@ for our @basket(b1)@. category_selector is a
        -- field_label_serializable with no dropdown (blawx-blocks.js:752-765;
        -- restorer mutators.js:68-84), immune by construction. The race is
        -- upstream quirk #4, recorded in the spec.
        t <- objectSlot a
        pure $
          blockE
            "object_category"
            [ valueE "object" t
            , valueE "category" $
                blockE
                  "category_selector"
                  [ mutationE [("category_name", n)]
                  , fieldE "category_name" n
                  ]
            ]
    | otherwise -> do
        -- unary_attribute_selector's `first_element` hardcodes check
        -- [VARIABLE,OBJECT] (blawx-blocks.js:3041-3048) and its mutator never
        -- calls setCheck (mutators.js:181-195), so this is an objectSlot too.
        t <- objectSlot a
        let (pre, post, ty) = case Map.lookup n sym.syAttrs of
              Just d  -> (d.baPrefix, d.baPostfix, renderValueType d.baType)
              Nothing -> ("", n, "boolean")
        pure $
          blockE
            "unary_attribute_selector"
            -- attributename is MANDATORY (the generator reads
            -- this.blawxAttributeName); attributetype is inert here — the
            -- unary mutator stores it and performs no setCheck.
            [ mutationE [("attributename", n), ("attributetype", ty)]
            , fieldE "prefix" pre
            , fieldE "postfix" post
            , valueE "first_element" t
            ]
  [a, b] -> do
    -- Under attributeorder="ov" the OBJECT slot is `first_element` and the
    -- VALUE slot is `second_element`. attributes.js pins the object slot to
    -- [OBJECT,VARIABLE] whatever we write (module header fact 4), so that one
    -- is an objectSlot; the value slot's check is
    -- [blawxTypeToBlocklyType(attributetype),'VARIABLE'], which we choose to
    -- fit the operand.
    ta <- objectSlot a
    tb <- termNode b
    let decl = Map.lookup n sym.syAttrs
        -- attributetype selects the connection checks and nothing else (the
        -- generator never reads it). Prefer the declared type, but only when
        -- it admits the operand actually in the slot; otherwise derive the
        -- type from the operand. NEVER the empty string and never absent: ""
        -- is not "no check" (blawxTypeToBlocklyType("") === 'OBJECT'), and an
        -- absent attribute round-trips through mutationToDom as the literal
        -- "undefined", which is also OBJECT.
        ty = case decl of
          Just d | accepts [blocklyType d.baType, "VARIABLE"] b -> renderValueType d.baType
          _ -> inferredType b
        (pre, inf, post) = case decl of
          Just d  -> (d.baPrefix, d.baInfix, d.baPostfix)
          Nothing -> ("", n, "")
    pure $
      blockE
        "attribute_selector"
        -- attributeorder MUST be "ov": anything else (including an absent
        -- attribute, which reads as null) swaps the two operands.
        [ mutationE
            [("attributename", n), ("attributetype", ty), ("attributeorder", "ov")]
        , fieldE "prefix" pre
        , fieldE "infix" inf
        , fieldE "postfix" post
        , valueE "first_element" ta
        , valueE "second_element" tb
        ]
  _
    | arity > 10 ->
        gap (n <> "/" <> Text.textShow arity) "relationship_selector goes to arity 10"
    | otherwise -> do
        ts <- traverse termNode args
        let decl = Map.lookup n sym.syRels
            declTypes = maybe [] (\d -> d.brTypes) decl
            declPrefixes = maybe [] (\d -> d.brPrefixes) decl
            postfix = maybe "" (\d -> d.brPostfix) decl
            slotType i a = case drop (i - 1) declTypes of
              t : _ | accepts [blocklyType t, "VARIABLE"] a -> renderValueType t
              _ -> inferredType a
            prefixAt i = case drop (i - 1) declPrefixes of
              t : _ -> t
              [] | i == 1 -> n
                 | otherwise -> ""
            slots = zip [1 :: Int ..] args
        pure $
          blockE
            ("relationship_selector" <> Text.textShow arity)
            -- arity, relationship_name and type1..typeN are ALL mandatory:
            -- the restorer loops on arity, the generator reads
            -- this.relationship_name, and each typeI drives a setCheck.
            ( [ mutationE
                  ( [("arity", Text.textShow arity), ("relationship_name", n)]
                      <> [("type" <> Text.textShow i, slotType i a) | (i, a) <- slots]
                  )
              ]
                <> [fieldE ("prefix" <> Text.textShow i) (prefixAt i) | (i, _) <- slots]
                <> [fieldE "postfix" postfix]
                <> [valueE ("parameter" <> Text.textShow i) t | (i, t) <- zip [1 :: Int ..] ts]
            )
 where
  n = bNameText p
  arity = length args

-- ---------------------------------------------------------------------------
-- Declaration blocks
-- ---------------------------------------------------------------------------

-- | The declarations' name fields carry @validate_predicate@
-- (@blawx-blocks.js:5216-5232@, installed at @:5129-5149@, @:5373@,
-- @:5255@), the sibling of the @validate_variable@ guarded in 'variableNode'.
-- It returns @null@ — leaving the field at its BLOCK DEFAULT — for a name
-- ending @_\\d+@ or containing anything outside @[\\w ]@, and lowercases the
-- initial otherwise. A rewritten declaration is worse than a rewritten
-- variable: every /selector/ reads its predicate from a mutation-restored
-- property rather than a field, so the call sites keep the real name while
-- the declaration regenerates @blawx_category(category_name)@ for a functor
-- nothing calls.
--
-- 'L4.Blawx.IR.mkBName' already enforces the invariant, so this cannot fire;
-- it is here so that a future regression in Lower's mangling surfaces as a
-- named gap instead of a silent rename.
predicateName :: Text -> BName -> Build Text
predicateName what nm
  | survivesPredicateValidator t = pure t
  | otherwise =
      gap (what <> " " <> t)
          "validate_predicate would silently rewrite this name to the field's default"
 where
  t = bNameText nm
  survivesPredicateValidator x = case Text.uncons x of
    Nothing -> False
    Just (c, cs) ->
      isAsciiLower c
        && Text.all wordChar cs
        && not (endsUnderscoreDigits x)
  wordChar c = isAsciiLower c || isAsciiUpper c || isDigit c || c == '_'
  endsUnderscoreDigits x =
    let ds = Text.takeWhileEnd isDigit x
    in  not (Text.null ds) && "_" `Text.isSuffixOf` Text.dropWhileEnd isDigit x

-- | @new_category_declaration@ — the one declaration with NO mutation
-- registered. @first_element@ is a fixed display label.
categoryDeclNode :: BCategoryDecl -> Build XNode
categoryDeclNode d = do
  nm <- predicateName "category" d.bcName
  pure $
    blockE
      "new_category_declaration"
      [ fieldE "category_name" nm
      , fieldE "prefix" d.bcPrefix
      , fieldE "first_element" "object"
      , fieldE "postfix" d.bcPostfix
      ]

-- | @new_attribute_declaration@. The mutation repeats @category_name@ and
-- @attribute_type@ because both dropdowns' static option lists are
-- placeholders: @domToMutation@ widens @menuGenerator_@ to the restored
-- value, and without that the later @\<field\>@ fails dropdown validation and
-- is silently discarded (the generator would then emit
-- @blawx_attribute(none,…)@).
attributeDeclNode :: BAttributeDecl -> Build XNode
attributeDeclNode d = do
  cat <- predicateName "category" d.baCategory
  nm  <- predicateName "attribute" d.baName
  pure $
    blockE
      "new_attribute_declaration"
      [ mutationE [("category_name", cat), ("attribute_type", ty)]
      , fieldE "category_name" cat
      , fieldE "attribute_name" nm
      , fieldE "attribute_type" ty
      , fieldE "order" order
      , fieldE "prefix" d.baPrefix
      , fieldE "first_element" firstEl
      , fieldE "infix" infixText
      , fieldE "second_element" secondEl
      , fieldE "postfix" d.baPostfix
      ]
 where
  ty = renderValueType d.baType
  boolean = case d.baType of BVBoolean -> True; _ -> False
  -- The block's own setOnChange forces order=ov and hides infix/second_element
  -- for a boolean attribute, and the generator's boolean arm reads neither
  -- (it synthesises the `not_applicable` atoms itself).
  order = if boolean then "ov" else renderNlgOrder d.baOrder
  infixText = if boolean then "" else d.baInfix
  (firstEl, secondEl) = case (boolean, d.baOrder) of
    (False, BOrderVO) -> ("value", "object")
    _                 -> ("object", "value")

-- | @relationship_declaration@ (the hand-written definition; the JSON of the
-- same name is superseded via @excluded_block_types@, and names the arity
-- field @arity@ where the real one — and the generator — say
-- @relationship_arity@).
--
-- @prefixI@\/@typeI@ must appear for every slot up to the arity, even when
-- the prefix is empty: for @I ≥ 4@ the restorer /creates/ the fields only if
-- @hasAttribute('prefix'+I)@.
relationshipDeclNode :: BRelationshipDecl -> Build XNode
relationshipDeclNode d
  | arity < 3 || arity > 10 =
      gap ("relationship " <> bNameText d.brName <> "/" <> Text.textShow arity)
          "relationship_declaration covers arity 3..10"
  | otherwise = do
      nm <- predicateName "relationship" d.brName
      pure $
        blockE
          "relationship_declaration"
          ( [ mutationE
                (concat [ [ ("prefix" <> Text.textShow i, pfx)
                          , ("type" <> Text.textShow i, renderValueType t)
                          ]
                        | (i, pfx, t) <- slots
                        ])
            , fieldE "relationship_name" nm
            , fieldE "relationship_arity" (Text.textShow arity)
            ]
              <> concat
                   [ [ fieldE ("prefix" <> Text.textShow i) pfx
                     , fieldE ("type" <> Text.textShow i) (renderValueType t)
                     ]
                   | (i, pfx, t) <- slots
                   ]
              <> [fieldE "postfix" d.brPostfix]
          )
 where
  arity = length d.brTypes
  slots = zip3 [1 :: Int ..] (d.brPrefixes <> repeat "") d.brTypes

-- ---------------------------------------------------------------------------
-- Terms and arithmetic
-- ---------------------------------------------------------------------------

-- | A term in a slot whose connection check is pinned to @[OBJECT,VARIABLE]@
-- and cannot be widened from the XML: @attribute_selector@'s object slot
-- (@attributes.js:8-15@, no @attributeType@ guard, and the @vo@ branch pins
-- the other input the same way, so the pin follows the /role/, not the
-- position), @unary_attribute_selector@'s @first_element@ and
-- @new_object_category@'s @object@.
--
-- A variable or an object atom goes in structurally. Anything else — in this
-- corpus, a list — would be created, rejected by the check, and left floating
-- as its own top-level block, which the generator then emits through
-- @scrubNakedValue@ as a spurious statement while the clause that lost it
-- regenerates with an empty argument. So the term goes in as an
-- @object_selector@ carrying its own s(CASP) text instead: same bytes out,
-- and the subterm is simply not editable in the UI. See the module header for
-- why there is no third option.
objectSlot :: BTerm -> Build XNode
objectSlot t
  | accepts ["OBJECT", "VARIABLE"] t = termNode t
  | otherwise = pure (objectSurrogate t)

objectSurrogate :: BTerm -> XNode
objectSurrogate t = objectSelectorNode (renderTerm t)

-- | @object_selector@: a mutation-restored @objectname@ (@mutators.js:52,57@)
-- and a @field_label_serializable@ the generator returns verbatim
-- (@scasp_generator.js:471-474@). The field carries NO validator, so whatever
-- text goes in comes back out.
objectSelectorNode :: Text -> XNode
objectSelectorNode t =
  blockE "object_selector" [mutationE [("objectname", t)], fieldE "object_name" t]

termNode :: BTerm -> Build XNode
termNode = \case
  BTVar v  -> variableNode v
  BTNum q
    | denominator q == 1 -> pure (numberNode (numerator q))
    | otherwise ->
        gap ("number " <> renderRationalText q)
            "number_value holds one field_number, never a ratio; term position \
            \has no slot for a math_operation"
  BTAtom a -> pure (objectSelectorNode (bNameText a))
  BTNil -> pure (blockE "empty_list" [])
  BTCons h t -> do
    hd <- termNode h
    tl <- termNode t
    pure (blockE "head_tail" [valueE "head" hd, valueE "tail" tl])

-- | @variable@ carries the @validate_variable@ field validator, which runs on
-- deserialisation and — for anything that is not @^[A-Za-z][\\w ]*$@, or that
-- ends @_\\d+@ — returns @null@, silently keeping the block's default @A@. It
-- also uppercases the initial and turns spaces into underscores. So the only
-- variable text that survives a load unchanged is an uppercase-initial word
-- character run not ending in @_\\d+@; anything else is a silent rename, and
-- is reported as a gap instead.
variableNode :: BVar -> Build XNode
variableNode v
  | survivesValidator t = pure (blockE "variable" [fieldE "variable_name" t])
  | otherwise =
      gap ("variable " <> t)
          "validate_variable would silently rewrite this name to \"A\""
 where
  t = varText v
  survivesValidator x = case Text.uncons x of
    Nothing -> False
    Just (c, cs) ->
      isAsciiUpper c
        && Text.all wordChar cs
        && not (endsUnderscoreDigits x)
  wordChar c = isAsciiLower c || isAsciiUpper c || isDigit c || c == '_'
  endsUnderscoreDigits x =
    let ds = Text.takeWhileEnd isDigit x
    in  not (Text.null ds) && "_" `Text.isSuffixOf` Text.dropWhileEnd isDigit x

varText :: BVar -> Text
varText (MkBVar t) = t

-- | @number_value@'s @field_number@ has no @min@, no @max@ and no
-- @precision@, and the generator string-concatenates the JS number, so an
-- integral value prints with no decimal point and a negative sign lives
-- inside the field.
numberNode :: Integer -> XNode
numberNode i = blockE "number_value" [fieldE "value" (Text.textShow i)]

-- | Arithmetic. Structural, one @math_operation@ per binary node, matching
-- 'L4.Blawx.Emit'\'s @renderArith@ image @( l op r )@ layer for layer.
arithNode :: BArith -> Build XNode
arithNode = \case
  BANum q -> numberOrRatio q
  BAVar v -> variableNode v
  BANeg (BANum q) -> numberOrRatio (negate q)
  BANeg e -> do
    r <- arithNode e
    pure (mathOp "sub" (numberNode 0) r)
  BABin op l r -> do
    a <- arithNode l
    b <- arithNode r
    pure (mathOp (opField op) a b)
 where
  numberOrRatio q
    | denominator q == 1 = pure (numberNode (numerator q))
    -- The R7-gated non-integral arm: its only block image is a division of
    -- two number_value fields, which is exactly Emit.renderArithNum's
    -- @( num / den )@.
    | otherwise = pure (mathOp "div" (numberNode (numerator q)) (numberNode (denominator q)))
  mathOp op l r =
    blockE
      "math_operation"
      [fieldE "operator" op, valueE "left_side" l, valueE "right_side" r]
  opField = \case
    BAdd -> "add"
    BSub -> "sub"
    BMul -> "mul"
    BDiv -> "div"

-- | The Blockly output type of an arithmetic expression's block: everything
-- but a bare variable is @Number@.
arithOutput :: BArith -> Text
arithOutput = \case
  BAVar _ -> "VARIABLE"
  _       -> "Number"

-- ---------------------------------------------------------------------------
-- Labels for gap messages
-- ---------------------------------------------------------------------------

termLabel :: BTerm -> Text
termLabel = \case
  BTVar v    -> varText v
  BTNum q    -> renderRationalText q
  BTAtom a   -> bNameText a
  BTNil      -> "[]"
  BTCons h t -> "[" <> termLabel h <> " | " <> termLabel t <> "]"

arithLabel :: BArith -> Text
arithLabel = \case
  BANum q      -> renderRationalText q
  BAVar v      -> varText v
  BANeg e      -> "-" <> arithLabel e
  BABin _ l r  -> "(" <> arithLabel l <> " . " <> arithLabel r <> ")"

renderRationalText :: Rational -> Text
renderRationalText q
  | denominator q == 1 = Text.textShow (numerator q)
  | otherwise = Text.textShow (numerator q) <> "/" <> Text.textShow (denominator q)
