-- | The __block-level__ intermediate representation of a Blawx project: one
-- 'BlawxDoc' per L4 module, modelling Blawx's /block/ inventory — categories,
-- attributes, relationships, attributed rules, facts, constraints, abducibles,
-- queries — and never s(CASP) text. Blocks are the pivot because they are the
-- only representation from which __both__ wire formats derive
-- (BLAWX-EXPORT-SPEC R12): the server stores @scasp_encoding@ and
-- @xml_content@ verbatim and derives neither from the other; only the block
-- structure determines both.
--
-- __The two-renderer contract.__ Both renderers consume this IR and nothing
-- else:
--
--   * @L4.Blawx.Emit.renderScasp :: BlawxDoc -> Text@ — P1; byte-exact
--     against @scasp_generator.js@ at Blawx commit @02eded1@, quirks included
--     (R10), because the fidelity gate is the re-save fixpoint: the Blawx
--     editor regenerates @scasp_encoding@ from blocks on every save, and the
--     stored text must not change (R12).
--   * @L4.Blawx.EmitXml.renderDocXml :: BlawxDoc -> BlawxXml@ — P3; the
--     paired Blockly XML, i.e. the blocks that make that regeneration land on
--     those bytes. Its per-row texts are what @renderBlawxYaml@ stores as
--     @xml_content@, and its @bxGaps@ are the rows it could not image.
--
-- The two are written against the same evidence from opposite ends, so a
-- change to either without the other breaks the fixpoint silently. The
-- structural names they must spell identically ('renderSectionRef',
-- 'renderValueType', 'renderNlgOrder', 'renderTerm') therefore live here
-- rather than in either emitter — as does 'blockRuns', which decides where a
-- stack becomes two Blockly roots and so where @renderScasp@ must put a blank
-- line.
--
-- Anything expressible in this IR must therefore be expressible as /blocks/:
-- a constructor with no block image (e.g. a raw Prolog escape hatch) must not
-- be added, because @renderScasp@ could print it but the XML could not, and
-- the first UI save would destroy it.
--
-- __That is necessary, not sufficient__: an image can also be missing for a
-- /combination/ of constructor and argument sort that each have images
-- separately. The witness is a binary predicate whose first argument is a
-- list: @attribute_selector@'s object slot is pinned to @[OBJECT,VARIABLE]@
-- by @attributes.js@ in /both/ argument orders, so @running_total([],0)@ has
-- no structural image even though @BFact@, @BTNil@ and @BTNum@ all do.
-- "L4.Blawx.EmitXml" answers such a slot with a verbatim @object_selector@
-- surrogate where it can (the generated bytes are then exact and the subterm
-- is merely not editable in the UI) and with an @XmlGap@ where it cannot.
--
-- __The P5 import-pivot role.__ The import direction (R14, @l4 blawx
-- --import@) parses @xml_content@ into /this same IR/ (@L4.Blawx.Parse@) and
-- lifts it to L4 (@L4.Blawx.Lift@); @scasp_encoding@ is only a cross-check —
-- regenerate via @renderScasp@ and diff to detect stale or hand-edited
-- encodings before lifting. The round-trip property @lift . emit = id@
-- (modulo formatting) on the v1 export fragment is stated against this type.
-- Consequently the IR must stay faithful to what blocks /store/ (e.g. NLG
-- prefix\/infix\/postfix as three separate fields, not a fused sentence),
-- or the fixpoint and the import both lose information.
--
-- __Names are already target-lexical here.__ "L4.Blawx.Lower" mangles
-- 'L4.Relational.IR.RName's into 'BName's (@^[a-z]\\w*$@, not ending
-- @_\\d+@ — the UI validator silently rewrites violations) and runs the
-- injective collision check /before/ building the 'BlawxDoc'; the emitters
-- never mangle. Provenance for citations rides along as the original
-- 'Unique'\/'SrcRange' so P4's justification story and the goldens' error
-- messages can still point at L4 source.
module L4.Blawx.IR
  ( -- * The document
    BlawxDoc (..)
  , BRuleText (..)
  , BSection (..)
  , BSectionRef (..)
  , BStep -- abstract: see 'mkBStep'
  , mkBStep
  , bStepKind
  , bStepLabel
  , bSec
    -- * Workspaces and blocks
  , BWorkspace (..)
  , BBlock (..)
  , BRun (..)
  , BChain (..)
  , chainKind
  , blockRuns
  , runBlocks
    -- * Ontology declaration blocks
  , BCategoryDecl (..)
  , BAttributeDecl (..)
  , BRelationshipDecl (..)
  , BObjectDecl (..)
  , BValueType (..)
  , BNlgOrder (..)
    -- * Rules and goals
  , BRule (..)
  , BConclusion (..)
  , BOverrule (..)
  , BURule (..)
  , BGoal (..)
  , BNegKind (..)
  , mkBGNegated
  , mkBAssertGoal
  , BCmpOp (..)
  , BAggFn (..)
  , BArith (..)
  , BArithOp (..)
    -- * Terms and names
  , BTerm (..)
  , BVar (..)
  , BName -- abstract: see 'mkBName'
  , bNameText
  , mkBName
    -- * Structural renderers, shared by both emitters
  , renderSectionRef
  , renderDocAtom
  , renderValueType
  , renderNlgOrder
  , renderTerm
  , renderRational
  , deconstructTerm
    -- * Tests
  , BTest (..)
  ) where

import Base
import qualified Base.Text as Text
import Data.Char (isAsciiLower, isAsciiUpper, isDigit)
import Data.Ratio (denominator, numerator)

import L4.Parser.SrcSpan (SrcRange)
import L4.Syntax (Unique)

-- ---------------------------------------------------------------------------
-- Names
-- ---------------------------------------------------------------------------

-- | A Blawx-conforming atom: matches @^[a-z]\w*$@ and does not end @_\d+@.
--
-- Abstract on purpose: the only constructor is 'mkBName', which checks the
-- regex-and-suffix invariant, so an emitter printing a 'BName' verbatim can
-- never emit an atom the UI validator would rewrite (breaking the R12
-- fixpoint). The original L4 identity ('Unique') is carried for provenance
-- joins; equality is on the /text/, because in the target the atom text IS
-- the identity (two distinct L4 names mangling to one atom are a collision
-- "L4.Blawx.Lower" must have rejected already).
data BName = MkBName
  { bnText   :: !Text
  , bnUnique :: !(Maybe Unique)  -- ^ 'Nothing' for synthesised names (skolems, aux)
  }
  deriving stock (Show, Generic)
  deriving anyclass (NFData)

instance Eq  BName where a == b = a.bnText == b.bnText
instance Ord BName where compare a b = compare a.bnText b.bnText

bNameText :: BName -> Text
bNameText n = n.bnText

-- | Smart constructor; 'Nothing' when the text violates the atom invariant.
-- "L4.Blawx.Lower"'s mangler is supposed to produce only valid atoms, so a
-- 'Nothing' at a Lower call site is a mangler bug surfacing as a diagnostic,
-- never a silent rewrite (the UI validator's failure mode this type exists to
-- prevent).
mkBName :: Maybe Unique -> Text -> Maybe BName
mkBName u t
  | validAtom, not endsUnderscoreDigits = Just (MkBName t u)
  | otherwise = Nothing
 where
  validAtom = case Text.uncons t of
    Nothing      -> False
    Just (c, cs) -> isAsciiLower c && Text.all wordChar cs
  wordChar c = isAsciiLower c || isAsciiUpper c || isDigit c || c == '_'
  -- @_\d+$@: a nonempty digit suffix immediately preceded by an underscore.
  endsUnderscoreDigits =
    let ds = Text.takeWhileEnd isDigit t
    in  not (Text.null ds) && "_" `Text.isSuffixOf` Text.dropWhileEnd isDigit t

-- | A Blawx variable: capitalised text, unique within its clause. Rendering
-- of unused head variables as @_@\/@_Name@ is the emitter's job.
newtype BVar = MkBVar Text
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- The document
-- ---------------------------------------------------------------------------

-- | One Blawx project: exactly what one @.blawx@ file (and its sibling @.pl@
-- dump) serialises. Workspaces are ordered: @root_section@ first, then the
-- numbered sections ascending — the emission order of the YAML stream and of
-- the concatenated s(CASP). \"Ascending\" is by section NUMBER, which since
-- §11 W3 the author may pin and which therefore need not be 1..n.
data BlawxDoc = MkBlawxDoc
  { bdName         :: !Text        -- ^ @ruledoc_name@
  , bdRuleText     :: !BRuleText   -- ^ structured CLEAN source; rendered by Emit
  , bdWorkspaces   :: ![BWorkspace]
  , bdTests        :: ![BTest]
  , bdDocPartNames :: !(Map BSectionRef Text)
    -- ^ __Import only.__ The @doc_selector@ labels a parsed document actually
    -- stores, by the section they point at. @\<field name=\"doc_part_name\"\>@
    -- is display-only — the generator reads the /mutation/
    -- (@scasp_generator.js:264-270@) — but it is stored bytes, and a
    -- re-emission that invents @NBA 5@ where bird wrote @NBA 5pingu@ fails the
    -- XML fixpoint even though the s(CASP) matches.
    --
    -- "L4.Blawx.Lower" sets 'mempty' and
    -- "L4.Blawx.EmitXml"\'s @docPartLabel@ then falls through to its computed
    -- label, so every P1\/P3 golden is unchanged by this field's existence.
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | The CLEAN @rule_text@, kept structured so eIds are predictable (R4): the
-- rendered form is @title\n\n1. …\n2. …@ with flat numbered sections only —
-- section /n/ yields AKN eId @sec_n@, hence workspace @sec_n_section@.
--
-- __The numbers need not be 1..n and need not be contiguous__ (spec §11 W3,
-- 2026-09-02). clean-law 0.0.4 builds the eId from the numeral it reads, never
-- from the section's position (@clean\/clean.py@, @generate_section@:
-- @prefix = \"sec_\" + node['section index'][0]@), so an author who writes the
-- Act's own numbering gets it — @rps.l4@ emits sections 3 and 4 only.
-- "L4.Blawx.Lower"\'s @sectionNumbers@ is what assigns them; a module that pins
-- nothing still gets 1..n in export order.
data BRuleText = MkBRuleText
  { brTitle    :: !Text
  , brSections :: ![BSection]
    -- ^ ascending by 'bsNumber', one entry per DISTINCT number
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BSection = MkBSection
  { bsNumber :: !Int
    -- ^ the CLEAN section index, ≥ 1. Ascending across 'brSections' and
    -- unique within it, but NOT necessarily its position + 1.
  , bsText   :: !Text
    -- ^ one paragraph, no newlines, and __never opening on a digit__: the
    -- @rule_text@ line is @\"\<n\>. \<text\>\"@ and clean-law reads that period
    -- plus a digit as an @insert_index@, which would name the canvas after a
    -- section the Act does not have (see @L4.Blawx.Lower.sectionTexts@, spec
    -- §11 W3). An imported document is not held to this — 'parseRuleText' is
    -- deliberately total over prose a human may have edited.
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | A workspace name, structurally: never a free-form string, so a typo like
-- @sec1_section@ cannot be constructed.
--
-- Blawx derives the name as @\<AKN eId\> \<\> \"_section\"@
-- (@blawx\/parse_an.py:53,62@), so the shape is the eId's: @__@-separated
-- components, each a kind and a label. Measured over the 110 workspaces of the
-- 15 shipped examples the kinds are @sec@, @subsec@, @para@, @subpara@ and
-- @span@ — but a kind is stored as 'Text', not an enum, because CLEAN\/AKN can
-- mint others (@art@, @sched@, @chp@) and an unknown kind must round-trip
-- rather than crash. Rendered @root_section@ \/ @sec_5_section@ \/
-- @sec_5__span_pingu_section@ \/ @sec_34__subsec_1__para_b__subpara_i_section@.
--
-- __One spelling per name.__ 'BPath' is the only non-root form and 'bSec'
-- builds the flat case Mode-A export uses; there is deliberately no @BSec Int@
-- constructor beside it, because two ways to spell @sec_5_section@ would make
-- the P5 @lift . emit = id@ property fail on structural equality for documents
-- that are byte-identical.
data BSectionRef
  = BRoot
  | BPath !(NonEmpty BStep)
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- | One @__@-separated component of a section path: a kind and a label —
-- @sec@ + @5@, @span@ + @pingu@, @subpara@ + @i@.
--
-- Abstract: the only constructor is 'mkBStep', which rejects a label
-- containing @__@ (it would re-split into two components on the way back in),
-- a label bounded by @_@ (same reason, one underscore short) and a kind
-- containing @_@ (the kind\/label split is at the FIRST underscore, so a kind
-- with one is not recoverable). Same discipline as 'BName', for the same
-- reason: a value that cannot be written back cannot break the round trip.
data BStep = MkBStep
  { bstKind  :: !Text  -- ^ @sec@, @subsec@, @para@, @subpara@, @span@, …
  , bstLabel :: !Text
  }
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

bStepKind :: BStep -> Text
bStepKind s = s.bstKind

bStepLabel :: BStep -> Text
bStepLabel s = s.bstLabel

-- | Smart constructor; 'Nothing' when the pair could not be recovered from the
-- rendered name. A 'Nothing' at an import call site is a named diagnostic,
-- never a section ref that renders back to a different workspace.
mkBStep :: Text -> Text -> Maybe BStep
mkBStep kind label
  | okKind, okLabel = Just (MkBStep kind label)
  | otherwise       = Nothing
 where
  okKind =
    not (Text.null kind) && Text.all wordChar kind && not (Text.any (== '_') kind)
  okLabel =
    not (Text.null label)
      && Text.all wordChar label
      && not ("__" `Text.isInfixOf` label)
      && not ("_" `Text.isPrefixOf` label)
      && not ("_" `Text.isSuffixOf` label)
  wordChar c = isAsciiLower c || isAsciiUpper c || isDigit c || c == '_'

-- | The flat case, @sec_\<n\>_section@ — what Mode-A export builds and the
-- only 'BSectionRef' shape "L4.Blawx.Lower" ever constructs.
bSec :: Int -> BSectionRef
bSec i = BPath (MkBStep "sec" (Text.textShow i) :| [])

data BWorkspace = MkBWorkspace
  { bwName   :: !BSectionRef
  , bwStacks :: ![[BBlock]]
    -- ^ __Top-level block stacks__, mirroring the Blockly canvas: separate
    -- stacks are separated by one blank line, and so are the 'blockRuns' of
    -- a single stack — a stack that mixes chainable and root-only blocks
    -- draws as more than one root. This nesting is byte-load-bearing for
    -- @renderScasp@ (see @p1-design\/emit-plan.md@ §1) and is what
    -- "L4.Blawx.EmitXml" turns into @\<block\>@ roots with @x@\/@y@
    -- placement. Convention from the evidence pair: declarations form ONE
    -- stack; each attributed rule is its OWN stack.
  , bwComment :: !(Maybe Text)
    -- ^ __Import only__ (ruling P5-4), and the exact twin of 'btComment' —
    -- same provenance, same non-imaging, same reason. It exists separately
    -- because __6 of the corpus's 18 @\<comment\>@ elements sit on
    -- @blawx.workspace@ rows__, not on tests (`oasa` ×3, `r34` ×3), and those
    -- six are the drafter's rationale — /\"This is hopelessly circular, but it
    -- is what the law says.\"/ Reading only 'btComment' honoured P5-4 for two
    -- thirds of the corpus and dropped the rest with no diagnostic.
    --
    -- "L4.Blawx.Lower" sets 'Nothing' and neither renderer images it, so
    -- every P1\/P3 golden is unchanged by this field's existence.
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Blocks
-- ---------------------------------------------------------------------------

-- | One block (or one statement-position block tree). Each constructor
-- corresponds to a block type in @blawx-blocks.js@; nothing here is "raw
-- s(CASP)" — see the module header for why.
data BBlock
  = BDeclareCategory !BCategoryDecl
    -- ^ @new_category_declaration@ — a 44-line s(CASP) image
  | BDeclareAttribute !BAttributeDecl
    -- ^ @new_attribute_declaration@ — a 44-line s(CASP) image
  | BDeclareRelationship !BRelationshipDecl
    -- ^ @relationship_declaration@ (arity 3–10) — a 44-line s(CASP) image
  | BAttributedRule !BRule
    -- ^ @attributed_rule@ — the defeasibility triple with dedup markers
  | BFact !Bool !BName ![BTerm]
    -- ^ a ground assertion; the 'Bool' is the sign (@False@ = classical
    -- @-p(…)@). Used for enum-constructor membership facts in
    -- @root_section@ and for test-scenario facts (NEVER @fact_scenario@,
    -- R11).
  | BConstraint ![BGoal]
    -- ^ @false :- goals.@ — the @#ASSERT@-as-constraint emission (R11)
  | BAbducible !BName ![BTerm]
    -- ^ @#abducible p(…).@ — the interview test's input declarations
  | BQuery ![BGoal]
    -- ^ the test query, rendered as the LAST line @?- g1, g2.@ (reasoner scan
    -- contract). Only valid inside a 'BTest' body; Lower never puts one in a
    -- workspace.
    --
    -- A /list/ because the block's @query@ input is an @input_statement@ whose
    -- members the generator joins with @\", \"@
    -- (@scasp_generator.js:191-205@), and because 3 of bird's 4 tests query
    -- @?- not flies(pingu).@, which a bare @!BName ![BTerm]@ could not say. A
    -- singleton @'BGCall' 'True'@ reproduces the old rendering byte for byte.
    -- ---------------------------------------------------------------------
    -- The P5 import extension (spec §10 P5, ruling P5-1). Everything below is
    -- reachable only from "L4.Blawx.Parse": the Mode-A export "L4.Blawx.Lower"
    -- constructs NONE of it, which is what keeps every P1\/P3 golden
    -- byte-identical through the extension. Each arm still owes BOTH images —
    -- @renderScasp@ and @renderXml@ — per the module header's two-renderer
    -- contract.
  | BDeclareObject !BObjectDecl
    -- ^ @object_declaration@ — 44 occurrences across the 15 shipped examples,
    -- always in fact position. __Mode-A export never constructs it__:
    -- enum-constructor membership is a 'BFact'.
  | BOverrules !BOverrule
    -- ^ @overrules@ — 21 occurrences, always in fact position, always
    -- __terminal__ (@previousStatement@ @\"OUTER\"@ and no @nextStatement@,
    -- @blawx-blocks.js:386-425@). __Mode-A export never constructs it__ (R6:
    -- Mode A has no defeat rules, so nothing generates a priority edge).
  | BUnattributedRule !BURule
    -- ^ @unattributed_rule@ — 4 occurrences, always a canvas root. __Mode-A
    -- export never constructs it__: R4 anchors every emitted decision to a
    -- section, so every emitted rule is attributed.
  | BAssertGoal !BGoal
    -- ^ a statement-position goal asserted as a fact: the
    -- @holds@\/@according_to@\/@applies@ blocks, which are goals everywhere
    -- else. Build ONLY via 'mkBAssertGoal', which rejects every goal that
    -- already has a block spelling — @'BGCall'@ is 'BFact', and admitting it
    -- here would give one byte-image two IR spellings and break
    -- @lift . emit = id@ on structural equality. __Mode-A export never
    -- constructs it.__
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | The single admission gate for 'BAssertGoal'. 'Nothing' for a goal that has
-- another statement-position spelling ('BGCall' → 'BFact') or none at all
-- ('BGCompare', 'BGUnify', 'BGDiseq', 'BGIs', 'BGFindall', 'BGAggregate' are
-- condition-position blocks; 'BGNaf' and 'BGNewObjectCategory' are held back
-- deliberately — the first is spelled by no fact block and the second by
-- 'BFact', and neither occurs in fact position anywhere in the measured
-- corpus, so admitting them would be inventing a shape). A 'Nothing' at an
-- import call site is a diagnostic, never a silent rewrite.
mkBAssertGoal :: BGoal -> Maybe BBlock
mkBAssertGoal = \case
  g@BGHolds{}       -> Just (BAssertGoal g)
  g@BGAccordingTo{} -> Just (BAssertGoal g)
  g@BGApplies{}     -> Just (BAssertGoal g)
  g@BGNegated{}     -> Just (BAssertGoal g)   -- a negated one of the above
  _                 -> Nothing

-- | __One @'bwStacks'@ entry is not one Blockly stack.__ Only the declaration
-- and fact blocks have a @previousStatement@ and can therefore chain;
-- @unattributed_constraint@, @assume@, @attributed_rule@ and @query@ have
-- none (@blawx-blocks.js:565-581, 1907-1923, 3107-3146, 235-250@) and can
-- only be canvas roots. A 'BRun' is what /does/ become one root.
--
-- This is byte-load-bearing for @renderScasp@, not only for the XML:
-- @Generator.workspaceToCode@ joins the code of separate top blocks with a
-- newline while each root's own code already ends in one, so __every run
-- boundary is a blank line__. Both emitters read the boundary from here so
-- they cannot disagree — which they did until 2026-08-19, when a test's
-- @[facts…, BConstraint]@ stack round-tripped one blank line richer than the
-- text we had stored (harness @benefit blawxtest/q2@, @q3@).
data BRun
  = BRunMembers ![BBlock]  -- ^ a maximal chain of statement-position blocks
  | BRunRoot !BBlock       -- ^ a block that can only be a root
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | How a block may sit in a Blockly stack, read off @previousStatement@ \/
-- @nextStatement@ in @blawx-blocks.js@ block by block.
--
-- 'BChainLast' exists for exactly one block: @overrules@ declares
-- @\"previousStatement\": \"OUTER\"@ and NO @nextStatement@
-- (@blawx-blocks.js:386-425@), so it may be chained /to/ and never /from/. The
-- old two-valued predicate could not say that, and XML that puts a block after
-- an @overrules@ is XML Blockly rejects on load.
data BChain
  = BChainNone  -- ^ neither connection: a canvas root and nothing else
  | BChainMid   -- ^ both: may be followed
  | BChainLast  -- ^ @previousStatement@ only: may be chained to, never from
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

chainKind :: BBlock -> BChain
chainKind = \case
  BDeclareCategory{}     -> BChainMid
  BDeclareAttribute{}    -> BChainMid
  BDeclareRelationship{} -> BChainMid
  BFact{}                -> BChainMid
  BAttributedRule{}      -> BChainNone
  BConstraint{}          -> BChainNone
  BAbducible{}           -> BChainNone
  BQuery{}               -> BChainNone
  -- P5 import extension; see the per-constructor haddocks for the citations.
  BDeclareObject{}       -> BChainMid   -- prev ["OUTER","STATEMENT"], next "STATEMENT"
  BAssertGoal{}          -> BChainMid   -- holds / according_to / applies: same
  BOverrules{}           -> BChainLast  -- prev "OUTER", NO next
  BUnattributedRule{}    -> BChainNone  -- neither (blawx-blocks.js:277-300)

-- | A maximal chain of 'BChainMid' blocks, optionally terminated by ONE
-- 'BChainLast'; a 'BChainNone' is a root of its own.
--
-- __Byte-stability__ (the P1\/P3 regression gate): on the eight pre-extension
-- constructors 'chainKind' returns 'BChainMid' exactly where the old @chains@
-- predicate returned 'True', and 'BChainLast' is unreachable from
-- "L4.Blawx.Lower", so the run partition — which decides blank lines in
-- @renderScasp@ and root @\<block\>@ boundaries in @renderDocXml@ — is
-- unchanged.
blockRuns :: [BBlock] -> [BRun]
blockRuns = go
 where
  go [] = []
  go (b : bs) = case chainKind b of
    BChainNone -> BRunRoot b : go bs
    BChainLast -> BRunMembers [b] : go bs
    BChainMid ->
      let (mid, rest) = span ((== BChainMid) . chainKind) bs
      in  case rest of
            t : rest' | chainKind t == BChainLast ->
              BRunMembers (b : mid <> [t]) : go rest'
            _ -> BRunMembers (b : mid) : go rest

runBlocks :: BRun -> [BBlock]
runBlocks = \case
  BRunMembers bs -> bs
  BRunRoot b     -> [b]

-- | Blawx attribute\/relationship value types (@scasp_generator.js@ value-type
-- vocabulary; the dropdown options in @blawx-blocks.js@ are @boolean@,
-- @number@, @date@, @time@, @datetime@, @duration@, @list@ plus every declared
-- category). M1\/v1 never constructs the date\/time\/duration members
-- (dates are rejected upstream), but the type names them so P5 import can
-- represent every shipped example.
data BValueType
  = BVBoolean | BVNumber | BVDate | BVTime | BVDatetime | BVDuration
  | BVList
  | BVCategory !BName
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | Argument order of a binary attribute's NLG sentence: @ov@ (object then
-- value → args @X,Y@) or @vo@ (args @Y,X@). v1 always emits 'BOrderOV';
-- carried so the import can read either.
data BNlgOrder = BOrderOV | BOrderVO
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @new_category_declaration@ fields. NLG slots are stored exactly as the
-- block stores them (prefix\/postfix around @(X)@) — fusing them would break
-- the R12 fixpoint and the P5 lift.
data BCategoryDecl = MkBCategoryDecl
  { bcName    :: !BName
  , bcPrefix  :: !Text
  , bcPostfix :: !Text
  , bcProv    :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @new_attribute_declaration@ fields. A 'BVBoolean' attribute is a UNARY
-- predicate and its infix\/order fields render as the bare atom
-- @not_applicable@ in @blawx_attribute_nlg@ — the emitter, not this type,
-- owns that quirk.
data BAttributeDecl = MkBAttributeDecl
  { baCategory :: !BName        -- ^ the owning category
  , baName     :: !BName        -- ^ the attribute = the global predicate name
  , baType     :: !BValueType
  , baOrder    :: !BNlgOrder
  , baPrefix   :: !Text
  , baInfix    :: !Text         -- ^ ignored (→ @not_applicable@) when boolean
  , baPostfix  :: !Text
  , baProv     :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @relationship_declaration@ fields; arity = @length brTypes@, 3–10
-- (checked in Lower with a named diagnostic — the ceiling is the emitter's
-- to enforce, per "L4.Relational.IR"'s module haddock).
data BRelationshipDecl = MkBRelationshipDecl
  { brName     :: !BName
  , brTypes    :: ![BValueType]
  , brPrefixes :: ![Text]        -- ^ one per argument, same length as 'brTypes'
  , brPostfix  :: !Text
  , brProv     :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @object_declaration@ (@blawx-blocks.js:781-808@; generator @:476-481@;
-- mutation restorer @mutators.js:23-45@). Declares an object AND asserts its
-- category membership: the s(CASP) image is @\<category\>(\<object_name\>)@.
--
-- __Which side each datum comes from.__ The generator reads the category from
-- @block.blawxCategoryName@, which only @domToMutation@ ever sets — so
-- @\<mutation category_name\>@ is MANDATORY, exactly as @doc_selector@'s
-- @section_reference@ is. The NLG comes from the FIELDS ('bodPrefix',
-- 'bodPostfix'); the mutation's own @prefix@\/@postfix@ attributes are
-- write-only for code generation and are stale in the wild (bird stores the
-- literal string @\"null\"@ for both while its @postfix@ field reads
-- @is a penguin@). They are carried verbatim in 'bodMutNlg' so a re-emission
-- is byte-faithful; 'Nothing' renders as @null@\/@null@, which is what the
-- evidence shows and what @getAttribute@ returning @null@ round-trips to.
--
-- __Mode-A export never constructs this__ (P5-1): "L4.Blawx.Lower" has no
-- object declarations — enum-constructor membership is a 'BFact'.
data BObjectDecl = MkBObjectDecl
  { bodName     :: !BName
  , bodCategory :: !BName
  , bodPrefix   :: !Text                  -- ^ @\<field name=\"prefix\"\>@
  , bodPostfix  :: !Text                  -- ^ @\<field name=\"postfix\"\>@
  , bodMutNlg   :: !(Maybe (Text, Text))  -- ^ verbatim mutation @prefix@\/@postfix@
  , bodProv     :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Rules
-- ---------------------------------------------------------------------------

-- | One @attributed_rule@ block. The section is carried on the rule (not
-- inferred from the enclosing workspace) because the @doc_selector@ block
-- stores it, and P5 import must detect a rule filed in the wrong workspace.
--
-- Mode A (v1): 'brDefeasible' is always 'False' — the checkbox states the
-- truth, no defeat rules exist. Negative conclusions ('bcSign' = 'False')
-- are never constructed in v1 (no CWA bridges yet, R5 "yes-later").
data BRule = MkBRule
  { brSection    :: !BSectionRef
  , brConclusion :: !BConclusion
  , brConditions :: ![BGoal]     -- ^ ordered; order is semantics (inherited from RClause)
  , brDefeasible :: !Bool
  , brInapplicable :: !Bool
    -- ^ the @subject to applicability@ checkbox (@blawx-blocks.js:3107-3146@,
    -- field @inapplicable@). 'True' makes the generator append
    -- @\",\\nblawx_applies(\<source\>,\<obj\>)\"@ after every condition
    -- __whose block image is literally @new_object_category@__
    -- (@scasp_generator.js:1188-1194@) — i.e. after every
    -- 'BGNewObjectCategory' and after nothing else. The trigger is the block
    -- image, not the semantic category: "L4.Blawx.EmitXml" images our own
    -- category goals as @object_category@ on purpose (upstream quirk #4, the
    -- test-page dropdown race), and the generator does not treat that as a
    -- trigger.
    --
    -- __Mode-A export always sets 'False'__: "L4.Blawx.Lower" has no
    -- applicability layer and never builds a 'BGNewObjectCategory', so a
    -- 'True' here would be a rule whose two images agree only by accident.
  , brProvenance :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BConclusion = MkBConclusion
  { bcSign :: !Bool              -- ^ 'False' = classical negative conclusion @-p@
  , bcPred :: !BName
  , bcArgs :: ![BTerm]
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @overrules@ (@blawx-blocks.js:386-425@; generator @:272-295@). One
-- priority edge: /the conclusion in A that P overrules the conclusion in B
-- that Q/, imaged as
-- @blawx_defeated(B,Q…) :- holds(A,P…)@.
--
-- __The statement slots are conclusion-shaped, not goal-shaped.__ Both are fed
-- through @deconstruct_term@, a functor-and-args regex
-- (@scasp_generator.js:1542-1554@, mirrored here as 'deconstructTerm'): a
-- comparison, a unification or a NAF goal in that slot is silently mangled
-- rather than rejected. Typing them 'BConclusion' states that restriction
-- where it cannot be forgotten.
--
-- __Mode-A export never constructs this__ (R6).
data BOverrule = MkBOverrule
  { bovDefeating     :: !BSectionRef
  , bovDefeatingStmt :: !BConclusion
  , bovDefeated      :: !BSectionRef
  , bovDefeatedStmt  :: !BConclusion
  , bovProv          :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @unattributed_rule@ (@blawx-blocks.js:277-300@; generator @:217-241@): a
-- clause with no section attribution, hence no @according_to@\/@holds@ bridge
-- and no defeat hook. bird's @sec_5@ uses one for the closed-world
-- applicability default
-- (@blawx_applies(sec_5_section,A) :-\\nnot -blawx_applies(sec_5_section,A).@).
--
-- The head is a statement /chain/, not a single goal, because the block's
-- @conclusion@ input is an @input_statement@ whose members the generator joins
-- with @\",\\n\"@ — a shape that is nonsense in s(CASP) but constructible in
-- the editor, so the IR keeps it and "L4.Blawx.Lift" refuses a head longer
-- than one with a named diagnostic.
--
-- __Mode-A export never constructs this__ (R4).
data BURule = MkBURule
  { burConclusion :: ![BGoal]
  , burConditions :: ![BGoal]
  , burProv       :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | One condition-position goal. Each constructor is a block in the
-- condition drawer; the mapping from 'L4.Relational.IR.RGoal' is
-- "L4.Blawx.Lower"'s classification step (see @p1-design\/emit-plan.md@ §4
-- for the goal-by-goal table and @p1-design\/risks.md@ for where it can go
-- wrong).
data BGoal
  = BGCall !Bool !BName ![BTerm]
    -- ^ signed predicate goal: @True@ → @p(…)@, @False@ → classical @-p(…)@
    -- (image of 'L4.Relational.IR.RNotCall' on an input predicate, and of
    -- the boolean-projection-@FALSE@ peephole)
  | BGNaf !BName ![BTerm]
    -- ^ negation as failure @not p(…)@ (image of 'L4.Relational.IR.RNotCall'
    -- on a computed\/auxiliary predicate — R5)
  | BGCompare !BCmpOp !BTerm !BTerm
    -- ^ @blawx_comparison(X,op,Y)@ — numeric operands only (REq dispatch
    -- happens in Lower, by sort)
  | BGUnify !BTerm !BTerm
    -- ^ @X = Y@ — generic equality on atoms\/objects (non-numeric @REq@,
    -- and @RMatch@ discrimination)
  | BGDiseq !BTerm !BTerm
    -- ^ @blawx_diseq(X,Y)@ — non-numeric @RNeq@
  | BGIs !BVar !BArith
    -- ^ @Var is Expr@ (image of @REval@)
  | BGFindall !BVar ![BGoal] !BVar
    -- ^ @findall(Template ,   Goal , List)@ — template var, single-goal body
    -- in v1 (a multi-goal body is factored through an auxiliary predicate by
    -- Lower; see @p1-design\/risks.md@ R7), output list var
  | BGAggregate !BAggFn !BVar !BVar
    -- ^ @\<fn\>_blawx_list(List , Out)@ — list first, out second, matching
    -- 'L4.Relational.IR.RAggregate''s stated order
    -- ---------------------------------------------------------------------
    -- The P5 import extension (ruling P5-1). "L4.Blawx.Lower" constructs NONE
    -- of these, which is what keeps every P1\/P3 golden byte-identical.
  | BGApplies !BSectionRef !BTerm
    -- ^ @applies@ (@blawx-blocks.js:3176-3199@; generator @:1259-1264@):
    -- @blawx_applies(\<sec\>,\<obj\>)@. The @object@ slot checks
    -- @[\"OBJECT\",\"VARIABLE\"]@, so it is an @objectSlot@ in the XML; the
    -- @applicable_rule@ slot checks @[\"RULE\",\"VARIABLE\"]@ and we only ever
    -- put a @doc_selector@ there.
  | BGHolds !BSectionRef !BGoal
    -- ^ @holds@ (@blawx-blocks.js:2010-2036@; generator @:755-769@):
    -- @holds(\<sec\>, \<deconstruct_term of the inner\>)@ — the payload is
    -- FLATTENED into the argument list, not nested, so @holds@ of
    -- @-blawx_applies(sec_5_section,pingu)@ is the 4-ary
    -- @holds(sec_5__span_pingu_section,-blawx_applies,sec_5_section,pingu)@
    -- (witness: bird's @sec_5__span_pingu_section@ workspace).
  | BGAccordingTo !BSectionRef !BGoal
    -- ^ @according_to@ (@blawx-blocks.js:1966-1998@; generator @:733-747@);
    -- same flattening, different functor, and a @rule@ (not @section@) input.
  | BGNegated !BNegKind !BGoal
    -- ^ @logical_negation@ (@blawx-blocks.js:109-129@) \/ @default_negation@
    -- (@:130-152@) over an arbitrary statement — the general wrappers, needed
    -- because bird nests them: @not -blawx_applies(…)@.
    --
    -- Build ONLY via 'mkBGNegated', which normalises the two cases that
    -- already have a spelling ('BGCall' 'False' and 'BGNaf'). Without that,
    -- the P3 seeds would emit one form and Parse would rebuild the other, and
    -- @lift . emit = id@ would fail on documents that are byte-identical.
  | BGNewObjectCategory !BName !BTerm
    -- ^ @new_object_category@ (@blawx-blocks.js:3066-3105@; generator
    -- @:1161-1166@) — byte-identical in s(CASP) to @'BGCall' 'True' cat [obj]@
    -- (both print @cat(obj)@), and DISTINCT from it for exactly one reason:
    -- the @attributed_rule@ generator injects the applicability guard only for
    -- a condition whose block type is literally @new_object_category@
    -- (@scasp_generator.js:1188-1194@), and "L4.Blawx.EmitXml" images our own
    -- category goals as @object_category@ instead, on purpose (quirk #4, the
    -- test-page dropdown race). So the trigger is the IMAGE, not the
    -- semantics.
    --
    -- __Mode-A export never constructs it__: Parse builds it only for a wild
    -- @new_object_category@; a wild @object_category@ normalises to
    -- @'BGCall' 'True'@, which is the form our own renderers emit and re-read.
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | Classical negation (@-p@) versus negation as failure (@not p@).
data BNegKind = BNegClassical | BNegDefault
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- | Normalising constructor for 'BGNegated': after it, every negated goal has
-- exactly one spelling. @logical_negation@ of a plain positive call is
-- 'BGCall' 'False'; @default_negation@ of one is 'BGNaf'; everything else —
-- including bird's @not -blawx_applies(…)@, where the inner is itself negated
-- — is the general wrapper.
mkBGNegated :: BNegKind -> BGoal -> BGoal
mkBGNegated BNegClassical (BGCall True p as) = BGCall False p as
mkBGNegated BNegDefault   (BGCall True p as) = BGNaf p as
mkBGNegated k             g                  = BGNegated k g

data BCmpOp = BEq | BNeq | BGt | BGte | BLt | BLte
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

data BAggFn = BCount | BSum | BAverage | BMin | BMax
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- | Mirror of 'L4.Relational.IR.RArith' with variables already renamed to
-- 'BVar'. Operand order and association are load-bearing (see @RArith@'s
-- haddock); the emitter renders __every__ binary node as @( l op r )@ — the
-- generator's own image (@scasp_generator.js:557-563@, one paren layer per
-- node) — so association is carried by the parens and is never reassociated.
data BArith
  = BANum !Rational   -- ^ must render exactly; non-integral rendering is
                      -- R7-gated, and non-integral has __no @number_value@
                      -- image__ — its only block form is the
                      -- @math_operation@ @( num \/ den )@
  | BAVar !BVar
  | BABin !BArithOp !BArith !BArith
  | BANeg !BArith     -- ^ Blawx has __no unary-negation block__: the image is
                      -- a signed @number_value@ field when the operand is a
                      -- literal, else the @math_operation@ @( 0 - e )@
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BArithOp = BAdd | BSub | BMul | BDiv
  -- ^ no Mod: Blawx's calculation block has @+ - * \/@ only; @RMod@ is
  -- rejected in Lower with a named diagnostic
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Terms
-- ---------------------------------------------------------------------------

data BTerm
  = BTVar  !BVar
  | BTNum  !Rational   -- ^ see 'BANum' note
  | BTAtom !BName      -- ^ an object, enum constructor, or string-literal atom
  | BTNil
  | BTCons !BTerm !BTerm  -- ^ rendered @[H | T]@ (head_tail block spacing)
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Structural renderers
-- ---------------------------------------------------------------------------

-- These three render a structural name that BOTH emitters must spell
-- identically: "L4.Blawx.Emit" splices them into s(CASP) text and
-- "L4.Blawx.EmitXml" into the block fields and mutations that regenerate that
-- same text, and the re-save fixpoint (R12) compares the two byte for byte.
-- They live here, beside the types they render, so there is exactly one
-- spelling to keep right.

-- | The workspace name, __verbatim__: @root_section@ \/ @sec_\<n\>_section@ \/
-- @sec_5__span_pingu_section@. This is the @.blawx@ YAML's @workspace_name@
-- and the @doc_selector@ mutation's @section_reference@.
--
-- It is __not__ what reaches the s(CASP) — see 'renderDocAtom'.
--
-- __Byte-stability__ (the P1\/P3 regression gate): @renderSectionRef (bSec i)@
-- is @\"sec\" \<\> \"_\" \<\> textShow i \<\> \"_section\"@, character for
-- character the old @BSec i@ rendering, for every @i@; 'BRoot' is untouched.
renderSectionRef :: BSectionRef -> Text
renderSectionRef = \case
  BRoot    -> "root_section"
  BPath ss -> Text.intercalate "__" (map step (toList ss)) <> "_section"
 where
  step s = s.bstKind <> "_" <> s.bstLabel

-- | A section reference __as the s(CASP) sees it__. Every path from a section
-- reference into generated logic runs through @sCASP['doc_selector']@, which
-- is @block.section_reference.toLowerCase()@
-- (@scasp_generator.js:264-270@) — so @according_to@, @holds@,
-- @blawx_defeated@ and @blawx_applies@ all receive the lowercased name.
-- Everywhere it reaches the XML or the YAML it is verbatim
-- ('renderSectionRef').
--
-- The two coincide for every reference Mode-A export builds ('bSec' is already
-- lowercase, and so is @root_section@), so no golden byte moves; they diverge
-- on an imported span whose label carries a capital.
renderDocAtom :: BSectionRef -> Text
renderDocAtom = Text.toLower . renderSectionRef

-- | The Blawx value-type keyword: the third argument of @blawx_attribute@,
-- the type list of @blawx_relationship@, and the @attribute_type@ \/ @typeN@
-- field and mutation values.
renderValueType :: BValueType -> Text
renderValueType = \case
  BVBoolean    -> "boolean"
  BVNumber     -> "number"
  BVDate       -> "date"
  BVTime       -> "time"
  BVDatetime   -> "datetime"
  BVDuration   -> "duration"
  BVList       -> "list"
  BVCategory n -> bNameText n

-- | @ov@ \/ @vo@: the second argument of @blawx_attribute_nlg@ and the
-- @order@ field of @new_attribute_declaration@.
renderNlgOrder :: BNlgOrder -> Text
renderNlgOrder = \case
  BOrderOV -> "ov"
  BOrderVO -> "vo"

-- | A term in argument position. "L4.Blawx.Emit" splices this into the
-- s(CASP); "L4.Blawx.EmitXml" builds the block tree that regenerates it, and
-- — where the slot's connection check leaves it no structural choice — puts
-- this very text in an @object_selector@ label, whose generator arm is
-- @this.getFieldValue('object_name')@ verbatim. One spelling, therefore, and
-- it lives here.
renderTerm :: BTerm -> Text
renderTerm = \case
  BTVar (MkBVar v) -> v
  BTNum q          -> renderRational q
  BTAtom n         -> bNameText n
  BTNil            -> "[]"
  BTCons h t       -> "[" <> renderTerm h <> " | " <> renderTerm t <> "]"

-- | A 'Rational' in __term__ position (the @number_value@ block plugged into
-- an attribute or relationship selector). An integral one renders as its
-- integer text — the @field_number@'s JS number, which carries no decimal
-- point (@blawx-blocks.js:924-938@; no @min@, no @precision@, so negatives
-- and decimals are both admissible field values).
--
-- A non-integral one renders @num\/den@, which is __not__ a @number_value@
-- image: the field holds one number, never a ratio, and term position has no
-- other slot to put a @math_operation@ in. The arm is totality, not policy —
-- Lower's R7 gate rejects non-integral literals with a named diagnostic — and
-- lifting that gate needs a term-position answer before this text can ship.
-- In /arithmetic/ position there is an answer: see
-- @L4.Blawx.Emit.renderArithNum@.
renderRational :: Rational -> Text
renderRational q
  | denominator q == 1 = Text.textShow (numerator q)
  | otherwise          = Text.textShow (numerator q) <> "/" <> Text.textShow (denominator q)

-- ---------------------------------------------------------------------------
-- deconstruct_term
-- ---------------------------------------------------------------------------

-- | @deconstruct_term@ (@scasp_generator.js:1542-1554@), reproduced including
-- its limits, because three generator arms — @overrules@, @holds@ and
-- @according_to@ — flatten their statement payload through it and the emitted
-- bytes are whatever it returns (R10).
--
-- The JS is
--
-- > const term_pattern  = /(?<functor>[^\(\)]*)\((?<parameters>.*)\)/gm
-- > const param_pattern = /(?:([^,\(\)]+(?:\([^\)]+\))?)(?:,?))/gm;
--
-- so, faithfully:
--
--   * the functor match is @[^()]*@ and the parameter match is greedy to the
--     LAST @)@ __on the same line__ (@.@ does not match a newline and the @s@
--     flag is absent), which is why exactly one level of nesting is recovered;
--   * a paren-free input yields the EMPTY list — which is why @holds@ of a
--     bare atom prints as the 1-ary @holds(sec)@. Callers must not \"fix\"
--     that;
--   * if the first paren is a @)@, or a @(@ has no @)@ after it on its line,
--     the engine advances the start index and retries — so the functor is
--     re-measured from just past that paren.
--
-- It is fed the already-rendered inner statement, because that is literally
-- what the generator does (@statementToCode@, then the regex). The leading
-- two-space Blockly statement indent lands in the functor and is removed by
-- the caller's per-element strip, exactly as the JS @.trim()@ does — so
-- passing un-indented text gives the same answer.
--
-- __Deliberately not used to re-express @L4.Blawx.Emit@'s @ruleTriple@__,
-- whose structural flattener is byte-frozen by four goldens; routing that
-- through a regex mirror would make a golden depend on this function. They are
-- cross-checked by a test instead.
deconstructTerm :: Text -> [Text]
deconstructTerm t = case termMatch t of
  Nothing              -> []
  Just (functor, args) -> functor : paramMatches args
 where
  isParen c = c == '(' || c == ')'
  -- The first successful start index of @term_pattern@.
  termMatch s =
    let (pre, rest) = Text.break isParen s
    in  case Text.uncons rest of
          Nothing -> Nothing
          Just ('(', after) ->
            let line = Text.takeWhile (/= '\n') after
                (upto, _) = Text.breakOnEnd ")" line
            in  if Text.null upto then termMatch after else Just (pre, Text.dropEnd 1 upto)
          -- a bare ')': every start at or before it fails identically, so the
          -- engine resumes just past it
          Just (_, after) -> termMatch after
  -- @matchAll(param_pattern)@, collecting capture group 1.
  paramMatches s = case Text.uncons s of
    Nothing -> []
    Just (c, rest)
      | isSep c -> paramMatches rest
      | otherwise ->
          let (core, r1)  = Text.break isSep s          -- [^,()]+
              (grp, r2)   = optParenGroup r1            -- (?:\([^)]+\))?
              r3          = fromMaybe r2 (Text.stripPrefix "," r2)
          in  (core <> grp) : paramMatches r3
  isSep c = c == ',' || isParen c
  optParenGroup r = case Text.uncons r of
    Just ('(', after) ->
      let (inner, rest) = Text.break (== ')') after
      in  if Text.null inner || Text.null rest
            then ("", r)
            else ("(" <> inner <> ")", Text.drop 1 rest)
    _ -> ("", r)

-- ---------------------------------------------------------------------------
-- Tests
-- ---------------------------------------------------------------------------

-- | One BlawxTest row: scenario facts asserted directly in the body (never
-- @fact_scenario@ — R11), optional @false :-@ constraints for @#ASSERT@s,
-- and the query as the final block. The L4-oracle expected value is NOT
-- here — it lives in the tier-1 harness (R11: the oracle stays outside the
-- artifact).
data BTest = MkBTest
  { btName    :: !Text        -- ^ slug, @[-a-zA-Z0-9_]+@ (Django URL converter)
  , btStacks  :: ![[BBlock]]  -- ^ facts\/constraints\/abducibles; the 'BQuery'
                              --   must be the last block of the last stack
  , btComment :: !(Maybe Text)
    -- ^ __Import only__ (ruling P5-4): the @\<comment\>@ text the test's
    -- blocks carry, newlines intact, which "L4.Blawx.Lift" re-wraps as @--@
    -- lines above the @#EVAL@. It is deliberately __not__ imaged by either
    -- renderer, so a re-emitted @.blawx@ drops it: the generator prefixes a
    -- block comment through @Blockly.utils.string.wrap@
    -- (@scasp_generator.js:41-49@), whose line balancing we do not reproduce,
    -- so an XML comment without that exact wrap would break the R12 byte-diff.
    -- Dropping it on BOTH sides keeps the two agreeing, and keeps every
    -- P1\/P3 golden byte-identical ("L4.Blawx.Lower" sets 'Nothing').
  , btProv    :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)
