-- | The __block-level__ intermediate representation of a Blawx project: one
-- 'BlawxDoc' per L4 module, modelling Blawx's /block/ inventory — categories,
-- attributes, relationships, attributed rules, facts, constraints, abducibles,
-- queries — and never s(CASP) text. Blocks are the pivot because they are the
-- only representation from which __both__ wire formats derive
-- (BLAWX-EXPORT-SPEC R12): the server stores @scasp_encoding@ and
-- @xml_content@ verbatim and derives neither from the other; only the block
-- structure determines both.
--
-- __The two-renderer contract.__ Both renderers consume this IR and nothing
-- else:
--
--   * @L4.Blawx.Emit.renderScasp :: BlawxDoc -> Text@ — P1; byte-exact
--     against @scasp_generator.js@ at Blawx commit @02eded1@, quirks included
--     (R10), because the fidelity gate is the re-save fixpoint: the Blawx
--     editor regenerates @scasp_encoding@ from blocks on every save, and the
--     stored text must not change (R12).
--   * @L4.Blawx.EmitXml.renderDocXml :: BlawxDoc -> BlawxXml@ — P3; the
--     paired Blockly XML, i.e. the blocks that make that regeneration land on
--     those bytes. Its per-row texts are what @renderBlawxYaml@ stores as
--     @xml_content@, and its @bxGaps@ are the rows it could not image.
--
-- The two are written against the same evidence from opposite ends, so a
-- change to either without the other breaks the fixpoint silently. The
-- structural names they must spell identically ('renderSectionRef',
-- 'renderValueType', 'renderNlgOrder', 'renderTerm') therefore live here
-- rather than in either emitter — as does 'blockRuns', which decides where a
-- stack becomes two Blockly roots and so where @renderScasp@ must put a blank
-- line.
--
-- Anything expressible in this IR must therefore be expressible as /blocks/:
-- a constructor with no block image (e.g. a raw Prolog escape hatch) must not
-- be added, because @renderScasp@ could print it but the XML could not, and
-- the first UI save would destroy it.
--
-- __That is necessary, not sufficient__: an image can also be missing for a
-- /combination/ of constructor and argument sort that each have images
-- separately. The witness is a binary predicate whose first argument is a
-- list: @attribute_selector@'s object slot is pinned to @[OBJECT,VARIABLE]@
-- by @attributes.js@ in /both/ argument orders, so @running_total([],0)@ has
-- no structural image even though @BFact@, @BTNil@ and @BTNum@ all do.
-- "L4.Blawx.EmitXml" answers such a slot with a verbatim @object_selector@
-- surrogate where it can (the generated bytes are then exact and the subterm
-- is merely not editable in the UI) and with an @XmlGap@ where it cannot.
--
-- __The P5 import-pivot role.__ The import direction (R14, @l4 blawx
-- --import@) parses @xml_content@ into /this same IR/ (@L4.Blawx.Parse@) and
-- lifts it to L4 (@L4.Blawx.Lift@); @scasp_encoding@ is only a cross-check —
-- regenerate via @renderScasp@ and diff to detect stale or hand-edited
-- encodings before lifting. The round-trip property @lift . emit = id@
-- (modulo formatting) on the v1 export fragment is stated against this type.
-- Consequently the IR must stay faithful to what blocks /store/ (e.g. NLG
-- prefix\/infix\/postfix as three separate fields, not a fused sentence),
-- or the fixpoint and the import both lose information.
--
-- __Names are already target-lexical here.__ "L4.Blawx.Lower" mangles
-- 'L4.Relational.IR.RName's into 'BName's (@^[a-z]\\w*$@, not ending
-- @_\\d+@ — the UI validator silently rewrites violations) and runs the
-- injective collision check /before/ building the 'BlawxDoc'; the emitters
-- never mangle. Provenance for citations rides along as the original
-- 'Unique'\/'SrcRange' so P4's justification story and the goldens' error
-- messages can still point at L4 source.
module L4.Blawx.IR
  ( -- * The document
    BlawxDoc (..)
  , BRuleText (..)
  , BSection (..)
  , BSectionRef (..)
    -- * Workspaces and blocks
  , BWorkspace (..)
  , BBlock (..)
  , BRun (..)
  , blockRuns
  , runBlocks
    -- * Ontology declaration blocks
  , BCategoryDecl (..)
  , BAttributeDecl (..)
  , BRelationshipDecl (..)
  , BValueType (..)
  , BNlgOrder (..)
    -- * Rules and goals
  , BRule (..)
  , BConclusion (..)
  , BGoal (..)
  , BCmpOp (..)
  , BAggFn (..)
  , BArith (..)
  , BArithOp (..)
    -- * Terms and names
  , BTerm (..)
  , BVar (..)
  , BName -- abstract: see 'mkBName'
  , bNameText
  , mkBName
    -- * Structural renderers, shared by both emitters
  , renderSectionRef
  , renderValueType
  , renderNlgOrder
  , renderTerm
  , renderRational
    -- * Tests
  , BTest (..)
  ) where

import Base
import qualified Base.Text as Text
import Data.Char (isAsciiLower, isAsciiUpper, isDigit)
import Data.Ratio (denominator, numerator)

import L4.Parser.SrcSpan (SrcRange)
import L4.Syntax (Unique)

-- ---------------------------------------------------------------------------
-- Names
-- ---------------------------------------------------------------------------

-- | A Blawx-conforming atom: matches @^[a-z]\w*$@ and does not end @_\d+@.
--
-- Abstract on purpose: the only constructor is 'mkBName', which checks the
-- regex-and-suffix invariant, so an emitter printing a 'BName' verbatim can
-- never emit an atom the UI validator would rewrite (breaking the R12
-- fixpoint). The original L4 identity ('Unique') is carried for provenance
-- joins; equality is on the /text/, because in the target the atom text IS
-- the identity (two distinct L4 names mangling to one atom are a collision
-- "L4.Blawx.Lower" must have rejected already).
data BName = MkBName
  { bnText   :: !Text
  , bnUnique :: !(Maybe Unique)  -- ^ 'Nothing' for synthesised names (skolems, aux)
  }
  deriving stock (Show, Generic)
  deriving anyclass (NFData)

instance Eq  BName where a == b = a.bnText == b.bnText
instance Ord BName where compare a b = compare a.bnText b.bnText

bNameText :: BName -> Text
bNameText n = n.bnText

-- | Smart constructor; 'Nothing' when the text violates the atom invariant.
-- "L4.Blawx.Lower"'s mangler is supposed to produce only valid atoms, so a
-- 'Nothing' at a Lower call site is a mangler bug surfacing as a diagnostic,
-- never a silent rewrite (the UI validator's failure mode this type exists to
-- prevent).
mkBName :: Maybe Unique -> Text -> Maybe BName
mkBName u t
  | validAtom, not endsUnderscoreDigits = Just (MkBName t u)
  | otherwise = Nothing
 where
  validAtom = case Text.uncons t of
    Nothing      -> False
    Just (c, cs) -> isAsciiLower c && Text.all wordChar cs
  wordChar c = isAsciiLower c || isAsciiUpper c || isDigit c || c == '_'
  -- @_\d+$@: a nonempty digit suffix immediately preceded by an underscore.
  endsUnderscoreDigits =
    let ds = Text.takeWhileEnd isDigit t
    in  not (Text.null ds) && "_" `Text.isSuffixOf` Text.dropWhileEnd isDigit t

-- | A Blawx variable: capitalised text, unique within its clause. Rendering
-- of unused head variables as @_@\/@_Name@ is the emitter's job.
newtype BVar = MkBVar Text
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- The document
-- ---------------------------------------------------------------------------

-- | One Blawx project: exactly what one @.blawx@ file (and its sibling @.pl@
-- dump) serialises. Workspaces are ordered: @root_section@ first, then the
-- numbered sections ascending — the emission order of the YAML stream and of
-- the concatenated s(CASP).
data BlawxDoc = MkBlawxDoc
  { bdName       :: !Text        -- ^ @ruledoc_name@
  , bdRuleText   :: !BRuleText   -- ^ structured CLEAN source; rendered by Emit
  , bdWorkspaces :: ![BWorkspace]
  , bdTests      :: ![BTest]
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | The CLEAN @rule_text@, kept structured so eIds are predictable (R4): the
-- rendered form is @title\n\n1. …\n2. …@ with flat numbered sections only —
-- section /n/ yields AKN eId @sec_n@, hence workspace @sec_n_section@.
data BRuleText = MkBRuleText
  { brTitle    :: !Text
  , brSections :: ![BSection]   -- ^ numbered 1.. in list order
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BSection = MkBSection
  { bsNumber :: !Int    -- ^ 1-based; invariant: position in 'brSections' + 1
  , bsText   :: !Text   -- ^ one paragraph, no newlines
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | A workspace name, structurally: never a free-form string, so a typo like
-- @sec1_section@ cannot be constructed. Rendered @root_section@ \/
-- @sec_\<n\>_section@.
data BSectionRef = BRoot | BSec !Int
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

data BWorkspace = MkBWorkspace
  { bwName   :: !BSectionRef
  , bwStacks :: ![[BBlock]]
    -- ^ __Top-level block stacks__, mirroring the Blockly canvas: separate
    -- stacks are separated by one blank line, and so are the 'blockRuns' of
    -- a single stack — a stack that mixes chainable and root-only blocks
    -- draws as more than one root. This nesting is byte-load-bearing for
    -- @renderScasp@ (see @p1-design\/emit-plan.md@ §1) and is what
    -- "L4.Blawx.EmitXml" turns into @\<block\>@ roots with @x@\/@y@
    -- placement. Convention from the evidence pair: declarations form ONE
    -- stack; each attributed rule is its OWN stack.
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Blocks
-- ---------------------------------------------------------------------------

-- | One block (or one statement-position block tree). Each constructor
-- corresponds to a block type in @blawx-blocks.js@; nothing here is "raw
-- s(CASP)" — see the module header for why.
data BBlock
  = BDeclareCategory !BCategoryDecl
    -- ^ @new_category_declaration@ — a 44-line s(CASP) image
  | BDeclareAttribute !BAttributeDecl
    -- ^ @new_attribute_declaration@ — a 44-line s(CASP) image
  | BDeclareRelationship !BRelationshipDecl
    -- ^ @relationship_declaration@ (arity 3–10) — a 44-line s(CASP) image
  | BAttributedRule !BRule
    -- ^ @attributed_rule@ — the defeasibility triple with dedup markers
  | BFact !Bool !BName ![BTerm]
    -- ^ a ground assertion; the 'Bool' is the sign (@False@ = classical
    -- @-p(…)@). Used for enum-constructor membership facts in
    -- @root_section@ and for test-scenario facts (NEVER @fact_scenario@,
    -- R11).
  | BConstraint ![BGoal]
    -- ^ @false :- goals.@ — the @#ASSERT@-as-constraint emission (R11)
  | BAbducible !BName ![BTerm]
    -- ^ @#abducible p(…).@ — the interview test's input declarations
  | BQuery !BName ![BTerm]
    -- ^ the test query, rendered as the LAST line @?- p(…).@ (reasoner scan
    -- contract). Only valid inside a 'BTest' body; Lower never puts one in a
    -- workspace.
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | __One @'bwStacks'@ entry is not one Blockly stack.__ Only the declaration
-- and fact blocks have a @previousStatement@ and can therefore chain;
-- @unattributed_constraint@, @assume@, @attributed_rule@ and @query@ have
-- none (@blawx-blocks.js:565-581, 1907-1923, 3107-3146, 235-250@) and can
-- only be canvas roots. A 'BRun' is what /does/ become one root.
--
-- This is byte-load-bearing for @renderScasp@, not only for the XML:
-- @Generator.workspaceToCode@ joins the code of separate top blocks with a
-- newline while each root's own code already ends in one, so __every run
-- boundary is a blank line__. Both emitters read the boundary from here so
-- they cannot disagree — which they did until 2026-08-19, when a test's
-- @[facts…, BConstraint]@ stack round-tripped one blank line richer than the
-- text we had stored (harness @benefit blawxtest/q2@, @q3@).
data BRun
  = BRunMembers ![BBlock]  -- ^ a maximal chain of statement-position blocks
  | BRunRoot !BBlock       -- ^ a block that can only be a root
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

blockRuns :: [BBlock] -> [BRun]
blockRuns = go
 where
  go [] = []
  go (b : bs)
    | chains b  = let (more, rest) = span chains bs in BRunMembers (b : more) : go rest
    | otherwise = BRunRoot b : go bs
  chains = \case
    BDeclareCategory{}     -> True
    BDeclareAttribute{}    -> True
    BDeclareRelationship{} -> True
    BFact{}                -> True
    BAttributedRule{}      -> False
    BConstraint{}          -> False
    BAbducible{}           -> False
    BQuery{}               -> False

runBlocks :: BRun -> [BBlock]
runBlocks = \case
  BRunMembers bs -> bs
  BRunRoot b     -> [b]

-- | Blawx attribute\/relationship value types (@scasp_generator.js@ value-type
-- vocabulary; the dropdown options in @blawx-blocks.js@ are @boolean@,
-- @number@, @date@, @time@, @datetime@, @duration@, @list@ plus every declared
-- category). M1\/v1 never constructs the date\/time\/duration members
-- (dates are rejected upstream), but the type names them so P5 import can
-- represent every shipped example.
data BValueType
  = BVBoolean | BVNumber | BVDate | BVTime | BVDatetime | BVDuration
  | BVList
  | BVCategory !BName
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | Argument order of a binary attribute's NLG sentence: @ov@ (object then
-- value → args @X,Y@) or @vo@ (args @Y,X@). v1 always emits 'BOrderOV';
-- carried so the import can read either.
data BNlgOrder = BOrderOV | BOrderVO
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @new_category_declaration@ fields. NLG slots are stored exactly as the
-- block stores them (prefix\/postfix around @(X)@) — fusing them would break
-- the R12 fixpoint and the P5 lift.
data BCategoryDecl = MkBCategoryDecl
  { bcName    :: !BName
  , bcPrefix  :: !Text
  , bcPostfix :: !Text
  , bcProv    :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @new_attribute_declaration@ fields. A 'BVBoolean' attribute is a UNARY
-- predicate and its infix\/order fields render as the bare atom
-- @not_applicable@ in @blawx_attribute_nlg@ — the emitter, not this type,
-- owns that quirk.
data BAttributeDecl = MkBAttributeDecl
  { baCategory :: !BName        -- ^ the owning category
  , baName     :: !BName        -- ^ the attribute = the global predicate name
  , baType     :: !BValueType
  , baOrder    :: !BNlgOrder
  , baPrefix   :: !Text
  , baInfix    :: !Text         -- ^ ignored (→ @not_applicable@) when boolean
  , baPostfix  :: !Text
  , baProv     :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | @relationship_declaration@ fields; arity = @length brTypes@, 3–10
-- (checked in Lower with a named diagnostic — the ceiling is the emitter's
-- to enforce, per "L4.Relational.IR"'s module haddock).
data BRelationshipDecl = MkBRelationshipDecl
  { brName     :: !BName
  , brTypes    :: ![BValueType]
  , brPrefixes :: ![Text]        -- ^ one per argument, same length as 'brTypes'
  , brPostfix  :: !Text
  , brProv     :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Rules
-- ---------------------------------------------------------------------------

-- | One @attributed_rule@ block. The section is carried on the rule (not
-- inferred from the enclosing workspace) because the @doc_selector@ block
-- stores it, and P5 import must detect a rule filed in the wrong workspace.
--
-- Mode A (v1): 'brDefeasible' is always 'False' — the checkbox states the
-- truth, no defeat rules exist. Negative conclusions ('bcSign' = 'False')
-- are never constructed in v1 (no CWA bridges yet, R5 "yes-later").
data BRule = MkBRule
  { brSection    :: !BSectionRef
  , brConclusion :: !BConclusion
  , brConditions :: ![BGoal]     -- ^ ordered; order is semantics (inherited from RClause)
  , brDefeasible :: !Bool
  , brProvenance :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BConclusion = MkBConclusion
  { bcSign :: !Bool              -- ^ 'False' = classical negative conclusion @-p@
  , bcPred :: !BName
  , bcArgs :: ![BTerm]
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- | One condition-position goal. Each constructor is a block in the
-- condition drawer; the mapping from 'L4.Relational.IR.RGoal' is
-- "L4.Blawx.Lower"'s classification step (see @p1-design\/emit-plan.md@ §4
-- for the goal-by-goal table and @p1-design\/risks.md@ for where it can go
-- wrong).
data BGoal
  = BGCall !Bool !BName ![BTerm]
    -- ^ signed predicate goal: @True@ → @p(…)@, @False@ → classical @-p(…)@
    -- (image of 'L4.Relational.IR.RNotCall' on an input predicate, and of
    -- the boolean-projection-@FALSE@ peephole)
  | BGNaf !BName ![BTerm]
    -- ^ negation as failure @not p(…)@ (image of 'L4.Relational.IR.RNotCall'
    -- on a computed\/auxiliary predicate — R5)
  | BGCompare !BCmpOp !BTerm !BTerm
    -- ^ @blawx_comparison(X,op,Y)@ — numeric operands only (REq dispatch
    -- happens in Lower, by sort)
  | BGUnify !BTerm !BTerm
    -- ^ @X = Y@ — generic equality on atoms\/objects (non-numeric @REq@,
    -- and @RMatch@ discrimination)
  | BGDiseq !BTerm !BTerm
    -- ^ @blawx_diseq(X,Y)@ — non-numeric @RNeq@
  | BGIs !BVar !BArith
    -- ^ @Var is Expr@ (image of @REval@)
  | BGFindall !BVar ![BGoal] !BVar
    -- ^ @findall(Template ,   Goal , List)@ — template var, single-goal body
    -- in v1 (a multi-goal body is factored through an auxiliary predicate by
    -- Lower; see @p1-design\/risks.md@ R7), output list var
  | BGAggregate !BAggFn !BVar !BVar
    -- ^ @\<fn\>_blawx_list(List , Out)@ — list first, out second, matching
    -- 'L4.Relational.IR.RAggregate''s stated order
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BCmpOp = BEq | BNeq | BGt | BGte | BLt | BLte
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

data BAggFn = BCount | BSum | BAverage | BMin | BMax
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- | Mirror of 'L4.Relational.IR.RArith' with variables already renamed to
-- 'BVar'. Operand order and association are load-bearing (see @RArith@'s
-- haddock); the emitter renders __every__ binary node as @( l op r )@ — the
-- generator's own image (@scasp_generator.js:557-563@, one paren layer per
-- node) — so association is carried by the parens and is never reassociated.
data BArith
  = BANum !Rational   -- ^ must render exactly; non-integral rendering is
                      -- R7-gated, and non-integral has __no @number_value@
                      -- image__ — its only block form is the
                      -- @math_operation@ @( num \/ den )@
  | BAVar !BVar
  | BABin !BArithOp !BArith !BArith
  | BANeg !BArith     -- ^ Blawx has __no unary-negation block__: the image is
                      -- a signed @number_value@ field when the operand is a
                      -- literal, else the @math_operation@ @( 0 - e )@
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

data BArithOp = BAdd | BSub | BMul | BDiv
  -- ^ no Mod: Blawx's calculation block has @+ - * \/@ only; @RMod@ is
  -- rejected in Lower with a named diagnostic
  deriving stock (Eq, Ord, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Terms
-- ---------------------------------------------------------------------------

data BTerm
  = BTVar  !BVar
  | BTNum  !Rational   -- ^ see 'BANum' note
  | BTAtom !BName      -- ^ an object, enum constructor, or string-literal atom
  | BTNil
  | BTCons !BTerm !BTerm  -- ^ rendered @[H | T]@ (head_tail block spacing)
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)

-- ---------------------------------------------------------------------------
-- Structural renderers
-- ---------------------------------------------------------------------------

-- These three render a structural name that BOTH emitters must spell
-- identically: "L4.Blawx.Emit" splices them into s(CASP) text and
-- "L4.Blawx.EmitXml" into the block fields and mutations that regenerate that
-- same text, and the re-save fixpoint (R12) compares the two byte for byte.
-- They live here, beside the types they render, so there is exactly one
-- spelling to keep right.

-- | The workspace name: @root_section@ \/ @sec_\<n\>_section@. Also the
-- @doc_selector@ mutation's @section_reference@ and the first argument of
-- every @according_to@ \/ @holds@ literal.
renderSectionRef :: BSectionRef -> Text
renderSectionRef = \case
  BRoot  -> "root_section"
  BSec i -> "sec_" <> Text.textShow i <> "_section"

-- | The Blawx value-type keyword: the third argument of @blawx_attribute@,
-- the type list of @blawx_relationship@, and the @attribute_type@ \/ @typeN@
-- field and mutation values.
renderValueType :: BValueType -> Text
renderValueType = \case
  BVBoolean    -> "boolean"
  BVNumber     -> "number"
  BVDate       -> "date"
  BVTime       -> "time"
  BVDatetime   -> "datetime"
  BVDuration   -> "duration"
  BVList       -> "list"
  BVCategory n -> bNameText n

-- | @ov@ \/ @vo@: the second argument of @blawx_attribute_nlg@ and the
-- @order@ field of @new_attribute_declaration@.
renderNlgOrder :: BNlgOrder -> Text
renderNlgOrder = \case
  BOrderOV -> "ov"
  BOrderVO -> "vo"

-- | A term in argument position. "L4.Blawx.Emit" splices this into the
-- s(CASP); "L4.Blawx.EmitXml" builds the block tree that regenerates it, and
-- — where the slot's connection check leaves it no structural choice — puts
-- this very text in an @object_selector@ label, whose generator arm is
-- @this.getFieldValue('object_name')@ verbatim. One spelling, therefore, and
-- it lives here.
renderTerm :: BTerm -> Text
renderTerm = \case
  BTVar (MkBVar v) -> v
  BTNum q          -> renderRational q
  BTAtom n         -> bNameText n
  BTNil            -> "[]"
  BTCons h t       -> "[" <> renderTerm h <> " | " <> renderTerm t <> "]"

-- | A 'Rational' in __term__ position (the @number_value@ block plugged into
-- an attribute or relationship selector). An integral one renders as its
-- integer text — the @field_number@'s JS number, which carries no decimal
-- point (@blawx-blocks.js:924-938@; no @min@, no @precision@, so negatives
-- and decimals are both admissible field values).
--
-- A non-integral one renders @num\/den@, which is __not__ a @number_value@
-- image: the field holds one number, never a ratio, and term position has no
-- other slot to put a @math_operation@ in. The arm is totality, not policy —
-- Lower's R7 gate rejects non-integral literals with a named diagnostic — and
-- lifting that gate needs a term-position answer before this text can ship.
-- In /arithmetic/ position there is an answer: see
-- @L4.Blawx.Emit.renderArithNum@.
renderRational :: Rational -> Text
renderRational q
  | denominator q == 1 = Text.textShow (numerator q)
  | otherwise          = Text.textShow (numerator q) <> "/" <> Text.textShow (denominator q)

-- ---------------------------------------------------------------------------
-- Tests
-- ---------------------------------------------------------------------------

-- | One BlawxTest row: scenario facts asserted directly in the body (never
-- @fact_scenario@ — R11), optional @false :-@ constraints for @#ASSERT@s,
-- and the query as the final block. The L4-oracle expected value is NOT
-- here — it lives in the tier-1 harness (R11: the oracle stays outside the
-- artifact).
data BTest = MkBTest
  { btName   :: !Text        -- ^ slug, @[-a-zA-Z0-9_]+@ (Django URL converter)
  , btStacks :: ![[BBlock]]  -- ^ facts\/constraints\/abducibles; the 'BQuery'
                             --   must be the last block of the last stack
  , btProv   :: !(Maybe (Unique, Maybe SrcRange))
  }
  deriving stock (Eq, Show, Generic)
  deriving anyclass (NFData)
