# Generated by `l4 openfisca` from agecheck.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
import numpy as np

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

Household = build_entity(
    key='household',
    plural='households',
    label='Household',
    doc='',
    roles=[
        {'key': 'member', 'plural': 'members', 'label': 'members'},
    ],
    is_person=False,
)

class birth_year(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'birth_year'

class age(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Age in whole years'
    def formula(person, period):
        return (period.start.year - person('birth_year', period))

class has_young_child(Variable):
    value_type = bool
    entity = Household
    definition_period = MONTH
    label = 'Whether the household has any child under 8'
    def formula(household, period):
        return household.any((household.members('age', period) < 8))

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Person, Household])
        self.add_variables(birth_year, age, has_young_child)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
