# Generated by `l4 openfisca` from basic-income.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.parameters import ParameterNode
import numpy as np

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

_PARAMETERS = {
    'benefits': {
        'basic_income': {
            'values': {'1900-01-01': 600},
        },
    },
    'general': {
        'age_of_majority': {
            'values': {'1900-01-01': 21, '1971-01-01': 18},
        },
    },
}

class age(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'age'

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class basic_income(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Basic income payable to a person for a period'
    def formula(person, period):
        return 0
    def formula_2016_12(person, period, parameters):
        return np.where((person('age', period) >= parameters(period).general.age_of_majority), parameters(period).benefits.basic_income, 0)
    def formula_2015_12(person, period, parameters):
        return np.where(((person('age', period) >= parameters(period).general.age_of_majority) & (person('salary', period) == 0)), parameters(period).benefits.basic_income, 0)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Person])
        self.parameters = ParameterNode("", data=_PARAMETERS)
        self.add_variables(age, salary, basic_income)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
