# Generated by `l4 export openfisca` from defaults.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.indexed_enums import Enum
import numpy as np

Claimant = build_entity(
    key='claimant',
    plural='claimants',
    label='Claimant',
    doc='',
    is_person=True,
)

class Status(Enum):
    single = 'single'
    married = 'married'

class income(Variable):
    value_type = float
    entity = Claimant
    definition_period = MONTH
    label = 'income'

class hours_a_week(Variable):
    value_type = float
    default_value = 40.0
    entity = Claimant
    definition_period = MONTH
    label = 'hours_a_week'

class is_resident(Variable):
    value_type = bool
    default_value = True
    entity = Claimant
    definition_period = MONTH
    label = 'is_resident'

class status(Variable):
    value_type = Enum
    possible_values = Status
    default_value = Status.married
    entity = Claimant
    definition_period = MONTH
    label = 'status'

class rate(Variable):
    value_type = float
    default_value = 3.0
    entity = Claimant
    definition_period = MONTH
    label = 'rate'

class allowance(Variable):
    value_type = float
    entity = Claimant
    definition_period = MONTH
    label = 'Allowance for a claimant'
    def formula(claimant, period):
        return np.where((claimant('is_resident', period) & (claimant('hours_a_week', period) >= 20)), np.where((claimant('status', period) == Status.single), claimant('income', period), (claimant('income', period) * claimant('rate', period))), 0)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Claimant])
        self.add_variables(income, hours_a_week, is_resident, status, rate, allowance)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
