# Generated by `l4 openfisca` from housing.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.indexed_enums import Enum
import numpy as np

Household = build_entity(
    key='household',
    plural='households',
    label='Household',
    doc='',
    is_person=True,
)

class Occupancy_Status(Enum):
    owner = 'Owner'
    tenant = 'Tenant'
    free_lodger = 'Free Lodger'
    homeless = 'Homeless'

class accommodation_size(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'accommodation_size'

class occupancy_status(Variable):
    value_type = Enum
    possible_values = Occupancy_Status
    default_value = Occupancy_Status.owner
    entity = Household
    definition_period = MONTH
    label = 'occupancy_status'

class owns_or_rents(Variable):
    value_type = bool
    entity = Household
    definition_period = MONTH
    label = 'Whether the household owns or rents its home'
    def formula(household, period):
        return np.where((household('occupancy_status', period) == Occupancy_Status.owner), True, np.where((household('occupancy_status', period) == Occupancy_Status.tenant), True, False))

class housing_tax(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'Monthly housing tax (size-based; owners and tenants only)'
    def formula(household, period):
        return np.where(household('owns_or_rents', period), np.maximum(200, (household('accommodation_size', period) * 10)), 0)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Household])
        self.add_variables(accommodation_size, occupancy_status, owns_or_rents, housing_tax)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
