# Generated by `l4 openfisca` from household.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
import numpy as np

Household = build_entity(
    key='household',
    plural='households',
    label='Household',
    doc='',
    roles=[
        {'key': 'member', 'plural': 'members', 'label': 'members'},
    ],
    is_person=False,
)

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

class name(Variable):
    value_type = str
    entity = Person
    definition_period = MONTH
    label = 'name'

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class household_income(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'Total monthly income of a household (sum of member salaries)'
    def formula(household, period):
        return household.sum(household.members('salary', period))

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Household, Person])
        self.add_variables(name, salary, household_income)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
