# Generated by `l4 openfisca` from roles.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
import numpy as np

Household = build_entity(
    key='household',
    plural='households',
    label='Household',
    doc='',
    roles=[
        {'key': 'adult', 'plural': 'adults', 'label': 'adults'},
        {'key': 'children', 'plural': 'children', 'label': 'children'},
    ],
    is_person=False,
)

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

class name(Variable):
    value_type = str
    entity = Person
    definition_period = MONTH
    label = 'name'

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class number_of_adults(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'Number of adults in the household'
    def formula(household, period):
        return household.nb_persons(Household.ADULT)

class adult_income(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'Total monthly income of the adults'
    def formula(household, period):
        return household.sum(household.members('salary', period), role=Household.ADULT)

class any_high_earner(Variable):
    value_type = bool
    entity = Household
    definition_period = MONTH
    label = 'Whether anyone in the household earns over 1000'
    def formula(household, period):
        return household.any((household.members('salary', period) > 1000))

class all_adults_earn(Variable):
    value_type = bool
    entity = Household
    definition_period = MONTH
    label = 'Whether every adult earns something'
    def formula(household, period):
        return household.all((household.members('salary', period) > 0), role=Household.ADULT)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Household, Person])
        self.add_variables(name, salary, number_of_adults, adult_income, any_high_earner, all_adults_earn)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
