#!/usr/bin/env bash
# P7 — the TNR / NLG (prose round-trip) leg.
#
# THIS STAGE CANNOT REGENERATE ITS ARTIFACT, AND SAYS SO.
#
# There is no `l4` subcommand that emits NLG prose. `l4 render --format text`
# produces a formatted document, which is a different thing. The committed
# goldens (subject.json, legs['p7-tnr']) are produced IN-PROCESS by the
# Haskell test suite (jl4/tests/Main.hs, `jl4NlgAnnotationsGolden`, writing
# `<stem>.nlg.golden`), which requires `cabal test jl4:jl4-test` — and this
# orchestrator never builds.
#
# So the status is NOT-REGENERATED: the artifact exists in the tree, the report
# cites its sha256 and where it came from, and states plainly that this run did
# not produce it. That is different from NOT-BUILT (the capability is missing)
# and different from SKIPPED (the machine lacks a tool).

if [[ "${1:-}" == "--inputs" ]]; then
  printf '%s\n' "$GO_S_CORPUS" "${BASH_SOURCE[0]}" \
    "$GO_S_TNR_GOLDEN" ${GO_S_TNR_WIZARD_GOLDEN:+"$GO_S_TNR_WIZARD_GOLDEN"}
  exit 0
fi

source "$(dirname "${BASH_SOURCE[0]}")/../lib/phase-prelude.sh"

declare -a GOLDENS=("$GO_S_TNR_GOLDEN")
[[ -n "${GO_S_TNR_WIZARD_GOLDEN:-}" ]] && GOLDENS+=("$GO_S_TNR_WIZARD_GOLDEN")
LOG="$GO_OUT/p7-tnr.txt"

{
  echo "TNR/NLG leg — NOT REGENERATED BY THIS RUN."
  echo
  echo "No l4 subcommand emits NLG prose. The verified command list is:"
  echo "  run check format ast batch trace state-graph render export openfisca"
  echo "and none of them produces a .nlg artifact. 'render --format text' emits a"
  echo "formatted document, which is not the prose round-trip SPEC.md §P7 names."
  echo
  echo "The committed goldens and where they come from:"
  for f in "${GOLDENS[@]}"; do
    if [[ -f "$f" ]]; then
      echo "  ${f#"$GO_ROOT"/}"
      echo "    sha256 $(node "$GO_LIB/digest.mjs" "$f")"
      echo "    bytes  $(wc -c <"$f" | tr -d ' ')"
      echo "    last touched by $(git -C "$GO_ROOT" log -1 --format='%h %ad %s' --date=short -- "$f" 2>/dev/null || echo '(no git history)')"
    else
      echo "  ${f#"$GO_ROOT"/} ABSENT"
    fi
  done
  echo
  echo "Producer: jl4/tests/Main.hs, jl4NlgAnnotationsGolden, writing <stem>.nlg.golden."
  echo "Reachable only via: cabal test jl4:jl4-test — which this orchestrator will not run."
} | tee "$LOG"

ARTS=(--artifact "$LOG")
for f in "${GOLDENS[@]}"; do [[ -f "$f" ]] && ARTS+=(--artifact "$f"); done

go_receipt --status NOT-REGENERATED \
  --reason "the NLG goldens exist in the tree and this run did not produce them. Their sha256 and originating commit are recorded in $LOG so the report can cite what it is actually showing, rather than implying the prose was regenerated from the current corpus." \
  --blocker "no l4 subcommand emits NLG. The goldens are produced in-process by jl4/tests/Main.hs (jl4NlgAnnotationsGolden), reachable only through 'cabal test jl4:jl4-test'. This orchestrator never runs cabal (CLAUDE.md §2.1, the build lock). Closing this needs either an 'l4 render --format nlg'-shaped subcommand or a golden-regeneration step run outside the orchestrator." \
  "${ARTS[@]}"
