#!/bin/sh
# blawx-census-smoke.sh — run `l4 blawx --import --parse-only` over every
# example Blawx ships, and record what the parse layer did with each
# (BLAWX-EXPORT-SPEC §10 P5; brief evidence item 3).
#
# This RECORDS a census; it does not gate on one. It exits 0 whenever the
# corpus was found, because 5 of the 15 examples are supposed to be refused —
# they use the date and event layers, which ruling P5-1 keeps out of the IR
# this phase. Its regression value comes from p5-design/census-results.md
# being committed and diffed.
#
# The corpus is a READ-ONLY foreign checkout on an external volume, so — like
# etc/validate-dmn.mjs — this skips silently when it is absent and is never a
# build or test dependency (repo CLAUDE.md §1.2, spec R13).
#
#   BLAWX_CHECKOUT=/path/to/blawx etc/blawx-census-smoke.sh [-o OUT.md]
set -eu

checkout="${BLAWX_CHECKOUT:-/Volumes/transcend/src/blawx}"
out=""
case "${1:-}" in
  -o) out="${2:?-o needs a path}" ;;
esac

repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
examples="$checkout/blawx/static/blawx/examples"

# blawx/fixtures/docs/examples/bird.yaml is a 10-line blawx.docpage DECOY.
# Pointing the harness at it would produce a confidently wrong census, so
# assert we are under static/.
case "$examples" in
  */static/blawx/examples) ;;
  *) echo "SKIP: refusing an examples path that is not .../static/blawx/examples" >&2; exit 0 ;;
esac

if [ ! -d "$examples" ]; then
  echo "SKIP: Blawx checkout not found at $checkout (set BLAWX_CHECKOUT)" >&2
  exit 0
fi

l4="${L4_BIN:-}"
if [ -z "$l4" ]; then
  l4=$(cd "$repo" && cabal list-bin exe:l4)
fi

commit=$(git -C "$checkout" rev-parse --short HEAD 2>/dev/null || echo "unknown")

emit() {
  if [ -n "$out" ]; then cat >>"$out"; else cat; fi
}
[ -n "$out" ] && : >"$out"

{
  echo "<!-- generated by etc/blawx-census-smoke.sh; do not hand-edit the tables -->"
  echo
  echo "Corpus: \`$examples\` at Blawx commit \`$commit\`."
  echo "Generated $(date -u +%Y-%m-%d) by \`l4 blawx --import --parse-only\`."
  echo
  echo "| example | verdict | blocks | types | ws | tests | encodings | stale | warn | err |"
  echo "| ------- | ------- | -----: | ----: | -: | ----: | --------: | ----: | ---: | --: |"
} | emit

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

for f in "$examples"/*.yaml; do
  stem=$(basename "$f" .yaml)
  line=$("$l4" blawx --import --parse-only "$f" 2>"$tmp") || true
  set -- $line
  # CENSUS stem verdict blocks= types= ws= tests= encodings= stale= warnings= errors=
  printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
    "$stem" "$3" "${4#*=}" "${5#*=}" "${6#*=}" "${7#*=}" "${8#*=}" "${9#*=}" "${10#*=}" "${11#*=}" | emit
done

echo | emit
echo "## Diagnostics, per example" | emit

for f in "$examples"/*.yaml; do
  stem=$(basename "$f" .yaml)
  "$l4" blawx --import --parse-only "$f" >/dev/null 2>"$tmp" || true
  {
    echo
    echo "### $stem"
    echo
    if [ -s "$tmp" ]; then
      echo '```'
      sed 's/^l4 blawx: //' "$tmp"
      echo '```'
    else
      echo "_no diagnostics._"
    fi
  } | emit
done
