# Generated by `l4 export openfisca` from eternity-parameter.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.parameters import ParameterNode
import numpy as np

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

_PARAMETERS = {
    'benefits': {
        'amount': {
            'values': {'1900-01-01': 600},
        },
    },
}

class income(Variable):
    value_type = float
    entity = Person
    definition_period = ETERNITY
    label = 'income'

class grant(Variable):
    value_type = float
    entity = Person
    definition_period = ETERNITY
    label = 'A one-off grant, with no period'
    def formula(person, period, parameters):
        return np.where((person('income', period) <= 1000), parameters(period).benefits.amount, 0)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Person])
        self.parameters = ParameterNode("", data=_PARAMETERS)
        self.add_variables(income, grant)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
