# Generated by `l4 export openfisca` from gt-guard.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.parameters import ParameterNode
import numpy as np

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

_PARAMETERS = {
    'taxes': {
        'flat': {
            'values': {'1900-01-01': 100, '2016-01-01': 200},
        },
    },
}

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class tax(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Tax for a period'
    def formula(person, period, parameters):
        return parameters(period).taxes.flat

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Person])
        self.parameters = ParameterNode("", data=_PARAMETERS)
        self.add_variables(salary, tax)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
