# Generated by `l4 export openfisca` from not-scalar.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.parameters import ParameterNode
import numpy as np

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

_PARAMETERS = {
    'taxes': {
        'rate': {
            'values': {'1900-01-01': 0.1, '2015-01-01': 0.15},
        },
    },
}

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class old_amount(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Amount, before and after the 2020 reform'
    def formula(person, period):
        return person.filled_array(np.where(np.logical_not((period.start.year >= 2020)), 100, 200))

class pre_reform(Variable):
    value_type = bool
    entity = Person
    definition_period = MONTH
    label = 'Whether the period is before the 2020 reform'
    def formula(person, period):
        return person.filled_array(np.logical_not((period.start.year >= 2020)))

class reform_test(Variable):
    value_type = bool
    entity = Person
    definition_period = MONTH
    label = 'After the reform, a person must earn over 5'
    def formula(person, period):
        return (np.logical_not((period.start.year >= 2020)) | (person('salary', period) > 5))

class relief(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Relief, unless the high rate is in force'
    def formula(person, period, parameters):
        return np.where(np.logical_not((parameters(period).taxes.rate >= 0.15)), (person('salary', period) * 0.05), 0)

class never(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'Never'
    def formula(person, period):
        return person.filled_array(np.where(np.logical_not(True), 1, 2))

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Person])
        self.parameters = ParameterNode("", data=_PARAMETERS)
        self.add_variables(salary, old_amount, pre_reform, reform_test, relief, never)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
