# Generated by `l4 export openfisca` from python-builtins.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
from openfisca_core.indexed_enums import Enum
import numpy as np

super_ = build_entity(
    key='super_',
    plural='super_s',
    label='super_',
    doc='',
    is_person=True,
)

class bool_(Enum):
    low = 'low'
    high = 'high'

class period_(Enum):
    peak = 'peak'
    offpeak = 'offpeak'

class band(Variable):
    value_type = Enum
    possible_values = bool_
    default_value = bool_.low
    entity = super_
    definition_period = ETERNITY
    label = 'band'

class slot(Variable):
    value_type = Enum
    possible_values = period_
    default_value = period_.peak
    entity = super_
    definition_period = ETERNITY
    label = 'slot'

class float_(Variable):
    value_type = bool
    entity = super_
    definition_period = ETERNITY
    label = 'float_'

class salary(Variable):
    value_type = float
    entity = super_
    definition_period = ETERNITY
    label = 'salary'

class tax(Variable):
    value_type = float
    entity = super_
    definition_period = ETERNITY
    label = 'Tax'
    def formula(super_, period):
        return np.where((super_('band', period) == bool_.low), np.where(super_('float_', period), super_('salary', period), 0), 20)

class fare(Variable):
    value_type = float
    entity = super_
    definition_period = ETERNITY
    label = 'Fare'
    def formula(super_, period):
        return np.where((super_('slot', period) == period_.peak), 3, 2)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([super_])
        self.add_variables(band, slot, float_, salary, tax, fare)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
