# Generated by `l4 export openfisca` from role-status.l4.
# Do not edit by hand; regenerate from the L4 source instead.
from openfisca_core.taxbenefitsystems import TaxBenefitSystem
from openfisca_core.entities import build_entity
from openfisca_core.variables import Variable
from openfisca_core.periods import MONTH, YEAR, ETERNITY
import numpy as np

Household = build_entity(
    key='household',
    plural='households',
    label='Household',
    doc='',
    roles=[
        {'key': 'status', 'plural': 'status', 'label': 'status'},
        {'key': 'children', 'plural': 'children', 'label': 'children'},
    ],
    is_person=False,
)

Person = build_entity(
    key='person',
    plural='persons',
    label='Person',
    doc='',
    is_person=True,
)

class salary(Variable):
    value_type = float
    entity = Person
    definition_period = MONTH
    label = 'salary'

class status_income(Variable):
    value_type = float
    entity = Household
    definition_period = MONTH
    label = 'Income of the status members'
    def formula(household, period):
        return household.sum(household.members('salary', period), role=Household.STATUS)

class L4TaxBenefitSystem(TaxBenefitSystem):
    def __init__(self):
        super().__init__([Household, Person])
        self.add_variables(salary, status_income)

# Convenience alias for `python -m openfisca` / SimulationBuilder.
CountryTaxBenefitSystem = L4TaxBenefitSystem
