-- | Render a @['YsRule']@ to yscript source text.
--
-- Pure text templating (no @Doc@ pretty-printer, no whitespace-sensitivity
-- games): a yscript codebase is a flat sequence of
--
-- > RULE <label> PROVIDES
-- > <proposition> ONLY IF
-- >     <conjunct/disjunct> AND
-- >     <conjunct/disjunct>
--
-- blocks, matching the shape of the three verbatim worked examples in
-- @specs\/research\/DATALEX-YSCRIPT-RESEARCH.md@ §C.
--
-- __What this deliberately does not reproduce.__ The worked examples wrap
-- @ONLY IF@ onto its own line wherever the preceding proposition text runs
-- past the print column of the /paper/ it was typeset in — that is a PDF
-- artefact of the source academic figure, not a yscript grammar requirement,
-- and nothing in the research memo says whitespace is significant to the
-- interpreter beyond separating tokens. This emitter always trails @ONLY IF@
-- on the proposition line and puts every conjunct\/disjunct on its own
-- 4-space-indented line, which is a strict subset of what the three figures
-- show (every one of them accepts a condition split one-per-line) rather than
-- an invented convention.
--
-- __No header comment.__ Every other backend this repo ships stamps a
-- @# Generated by ...@ line at the top of its output. yscript's comment
-- syntax (if it has one) was not found in either primary source this session
-- could open, so inventing one would be exactly the kind of guessed-syntax
-- byte the parent spec's R2 refuses to emit for @NOT@; the file is emitted
-- with no header rather than a wrong one.
module L4.Yscript.Emit
  ( renderYscript
  ) where

import Base
import qualified Base.Text as Text

import L4.Yscript.IR

renderYscript :: [YsRule] -> Text
renderYscript rules = Text.intercalate "\n\n" (map renderRule rules) <> "\n"

renderRule :: YsRule -> Text
renderRule r =
  Text.intercalate "\n" $
       [ "RULE " <> r.label <> " PROVIDES"
       , r.provides <> " ONLY IF"
       ]
    <> map ("    " <>) (renderCondition r.condition)

-- | One line per conjunct\/disjunct, each carrying its own trailing
-- connective except the last. A single-atom body (@Body ::= Atom@, R2) is
-- one line with no connective at all.
renderCondition :: YsExpr -> [Text]
renderCondition = \case
  YAtom t -> [t]
  e@YAnd{} -> renderChain CAnd e
  e@YOr{}  -> renderChain COr e

data Conn = CAnd | COr

connWord :: Conn -> Text
connWord = \case
  CAnd -> "AND"
  COr  -> "OR"

-- | Same-connective chains flatten to a single flat list (matching every
-- worked example, none of which nests same-op parentheses); a chain that
-- switches connective is parenthesised at the switch, since no primary
-- source was found describing yscript's own grouping syntax and this is the
-- conservative, self-consistent choice rather than a guess at one.
flattenSame :: Conn -> YsExpr -> [YsExpr]
flattenSame CAnd (YAnd l r) = flattenSame CAnd l <> flattenSame CAnd r
flattenSame COr  (YOr  l r) = flattenSame COr  l <> flattenSame COr  r
flattenSame _ e = [e]

renderChain :: Conn -> YsExpr -> [Text]
renderChain c e =
  let items = map (renderItem c) (flattenSame c e)
      n     = length items
  in [ t <> (if i < n - 1 then " " <> connWord c else "") | (i, t) <- zip [0 ..] items ]

-- | One conjunct\/disjunct, inline (used both for a flattened chain's own
-- items and for the parenthesised sub-chain nested inside one).
renderItem :: Conn -> YsExpr -> Text
renderItem _ (YAtom t) = t
renderItem _ e =
  let c' = case e of
        YAnd{} -> CAnd
        _      -> COr
  in "(" <> Text.intercalate (" " <> connWord c' <> " ") (map (renderItem c') (flattenSame c' e)) <> ")"
