-- | Render an 'OFPackage' to a single self-contained OpenFisca Python module.
--
-- The emitted file defines the entity, every variable (input + computed), and
-- a 'TaxBenefitSystem' subclass that registers them — enough to instantiate and
-- run with @SimulationBuilder@. Output is built as plain 'Text' (not a 'Doc')
-- so indentation is exact and golden-stable.
module L4.OpenFisca.Emit
  ( renderPackage
  ) where

import Base
import qualified Data.Map.Strict as Map
import Data.Ratio (denominator, numerator)
import qualified Data.Text as Text

import L4.OpenFisca.IR

renderPackage :: OFPackage -> Text
renderPackage pkg =
  Text.unlines $
       header pkg
    <> [""]
    <> concatMap entityLines pkg.pkgEntities
    <> concatMap enumLines pkg.pkgEnums
    <> parameterLines pkg.pkgParameters
    <> concatMap variableLines pkg.pkgVariables
    <> systemLines pkg

header :: OFPackage -> [Text]
header pkg =
  [ "# Generated by `l4 openfisca` from " <> pkg.pkgSource <> "."
  , "# Do not edit by hand; regenerate from the L4 source instead."
  , "from openfisca_core.taxbenefitsystems import TaxBenefitSystem"
  , "from openfisca_core.entities import build_entity"
  , "from openfisca_core.variables import Variable"
  , "from openfisca_core.periods import MONTH, YEAR, ETERNITY"
  ]
  <> [ "from openfisca_core.indexed_enums import Enum" | not (null pkg.pkgEnums) ]
  <> [ "from openfisca_core.parameters import ParameterNode" | not (null pkg.pkgParameters) ]
  <> [ "import numpy as np" ]

enumLines :: OFEnumDef -> [Text]
enumLines e =
     [ "class " <> e.enName <> "(Enum):" ]
  <> [ ind 1 <> mem <> " = " <> pyStr val | (mem, val) <- e.enMembers ]
  <> [ "" ]

entityLines :: OFEntity -> [Text]
entityLines e =
     [ e.entPy <> " = build_entity("
     , ind 1 <> "key=" <> pyStr e.entKey <> ","
     , ind 1 <> "plural=" <> pyStr e.entPlural <> ","
     , ind 1 <> "label=" <> pyStr e.entLabel <> ","
     , ind 1 <> "doc=" <> pyStr "" <> ","
     ]
  <> roleLines e.entRoles
  <> [ ind 1 <> "is_person=" <> (if e.entIsPerson then "True" else "False") <> ","
     , ")"
     , ""
     ]

roleLines :: [OFRole] -> [Text]
roleLines [] = []
roleLines roles =
     [ ind 1 <> "roles=[" ]
  <> map roleEntry roles
  <> [ ind 1 <> "]," ]
 where
  roleEntry r =
    ind 2 <> "{'key': " <> pyStr r.roleKey
      <> ", 'plural': " <> pyStr r.rolePlural
      <> ", 'label': " <> pyStr r.roleLabel <> "},"

variableLines :: OFVariable -> [Text]
variableLines v =
     [ "class " <> v.varName <> "(Variable):"
     , ind 1 <> "value_type = " <> pyValueType v.varType
     ]
  <> enumAttrs v.varType
  <> [ ind 1 <> "entity = " <> v.varEntity
     , ind 1 <> "definition_period = " <> pyPeriod v.varPeriod
     , ind 1 <> "label = " <> pyStr v.varLabel
     ]
  <> formulaLines v
  <> [""]

enumAttrs :: OFType -> [Text]
enumAttrs = \case
  OFEnum cls dflt ->
    [ ind 1 <> "possible_values = " <> cls
    , ind 1 <> "default_value = " <> cls <> "." <> dflt
    ]
  _ -> []

formulaLines :: OFVariable -> [Text]
formulaLines v =
     maybe [] (oneFormula "formula") v.varFormula
  <> concatMap (\(d, b) -> oneFormula ("formula_" <> dateSuffix d) b) v.varDated
 where
  -- A formula reading a legislation parameter takes OpenFisca's 3-arg shape.
  oneFormula name body =
    let args = if usesParams body
                 then v.varEntKey <> ", period, parameters"
                 else v.varEntKey <> ", period"
    in [ ind 1 <> "def " <> name <> "(" <> args <> "):"
       , ind 2 <> "return " <> emitExpr v.varEntKey v.varEntity body
       ]
  -- "YYYY-MM-DD" → "YYYY_MM" (OpenFisca dated-formula method suffix).
  dateSuffix d = case Text.splitOn "-" d of
    (y : m : _) -> y <> "_" <> m
    _           -> Text.replace "-" "_" d

usesParams :: OFExpr -> Bool
usesParams = \case
  OFScaleCalc _ _ -> True
  OFBin _ a b     -> usesParams a || usesParams b
  OFCmp _ a b     -> usesParams a || usesParams b
  OFAnd a b       -> usesParams a || usesParams b
  OFOr a b        -> usesParams a || usesParams b
  OFNot a         -> usesParams a
  OFNeg a         -> usesParams a
  OFSum _ a       -> usesParams a
  OFAny _ a       -> usesParams a
  OFAll _ a       -> usesParams a
  OFNpCall _ as   -> any usesParams as
  OFCond a b c    -> usesParams a || usesParams b || usesParams c
  _               -> False

systemLines :: OFPackage -> [Text]
systemLines pkg =
     [ "class L4TaxBenefitSystem(TaxBenefitSystem):"
     , ind 1 <> "def __init__(self):"
     , ind 2 <> "super().__init__([" <> Text.intercalate ", " (map (.entPy) pkg.pkgEntities) <> "])"
     ]
  <> [ ind 2 <> "self.parameters = ParameterNode(\"\", data=_PARAMETERS)" | not (null pkg.pkgParameters) ]
  <> [ ind 2 <> "self.add_variables(" <> Text.intercalate ", " (map (.varName) pkg.pkgVariables) <> ")"
     , ""
     , "# Convenience alias for `python -m openfisca` / SimulationBuilder."
     , "CountryTaxBenefitSystem = L4TaxBenefitSystem"
     ]

-- ---------------------------------------------------------------------------
-- Parameter store (_PARAMETERS dict mirroring OpenFisca's parameter YAML)
-- ---------------------------------------------------------------------------

-- | A path-addressed tree of scale parameters, rendered as a nested dict.
data PTree = PScale [OFBracket] | PMap (Map Text PTree)

parameterLines :: [OFScaleParam] -> [Text]
parameterLines [] = []
parameterLines params =
     [ "_PARAMETERS = {" ]
  <> renderEntries 1 (foldr ins (PMap Map.empty) params)
  <> [ "}", "" ]
 where
  ins p t = insertScale (Text.splitOn "." p.spPath) p.spBrackets t

insertScale :: [Text] -> [OFBracket] -> PTree -> PTree
insertScale path bs tree = case (path, tree) of
  ([], _)          -> PScale bs
  (k : ks, PMap m) -> PMap (Map.alter (Just . insertScale ks bs . fromMaybe (PMap Map.empty)) k m)
  (k : ks, PScale _) -> PMap (Map.singleton k (insertScale ks bs (PMap Map.empty)))

renderEntries :: Int -> PTree -> [Text]
renderEntries n = \case
  PScale bs -> scaleEntries n bs
  PMap m    -> concatMap (uncurry (entry n)) (Map.toList m)
 where
  entry n' k child =
       [ ind n' <> pyStr k <> ": {" ]
    <> renderEntries (n' + 1) child
    <> [ ind n' <> "}," ]

scaleEntries :: Int -> [OFBracket] -> [Text]
scaleEntries n bs =
     [ ind n <> "'brackets': [" ]
  <> map bracketLine bs
  <> [ ind n <> "]," ]
 where
  bracketLine b =
    ind (n + 1) <> "{'rate': " <> datedMap b.brRate
      <> ", 'threshold': " <> datedMap b.brThreshold <> "},"
  datedMap kvs =
    "{" <> Text.intercalate ", " [ pyStr d <> ": " <> renderNum v | (d, v) <- kvs ] <> "}"

-- ---------------------------------------------------------------------------
-- Expression emission (vectorised numpy semantics)
-- ---------------------------------------------------------------------------

-- | Emit an expression. @ent@ is the entity key bound as the formula's first
-- argument (e.g. @person@), used to read other variables.
--
-- Compound nodes are fully parenthesised. This matters for numpy: the bitwise
-- operators @& | ~@ (used for boolean and/or/not on arrays) bind /tighter/ than
-- comparison operators in Python, so @a > b & c@ would misparse without parens.
emitExpr :: Text -> Text -> OFExpr -> Text
emitExpr ent entPy = go
 where
  go = \case
    OFNum r      -> renderNum r
    OFStrLit t   -> pyStr t
    OFBoolLit b  -> if b then "True" else "False"
    OFLocal t    -> t
    OFVarRef nm  -> ent <> "(" <> pyStr nm <> ", period)"
    OFMembersVar nm -> ent <> ".members(" <> pyStr nm <> ", period)"
    OFSum r e    -> ent <> ".sum(" <> go e <> roleArg r <> ")"
    OFAny r e    -> ent <> ".any(" <> go e <> roleArg r <> ")"
    OFAll r e    -> ent <> ".all(" <> go e <> roleArg r <> ")"
    OFNbPersons r -> ent <> ".nb_persons(" <> maybe "" roleConst r <> ")"
    OFBin op a b -> paren (go a <> " " <> binOp op <> " " <> go b)
    OFCmp op a b -> paren (go a <> " " <> cmpOp op <> " " <> go b)
    OFAnd a b    -> paren (go a <> " & " <> go b)
    OFOr  a b    -> paren (go a <> " | " <> go b)
    OFNot a      -> paren ("~" <> go a)
    OFNeg a      -> paren ("-" <> go a)
    OFCond c t e -> "np.where(" <> go c <> ", " <> go t <> ", " <> go e <> ")"
    OFScaleCalc path income -> "parameters(period)." <> path <> ".calc(" <> go income <> ")"
    OFEnumLit cls mem -> cls <> "." <> mem
    OFNpCall fn as -> "np." <> fn <> "(" <> Text.intercalate ", " (map go as) <> ")"
    OFPeriodField f -> "period.start." <> f

  binOp = \case
    OFAdd -> "+"; OFSub -> "-"; OFMul -> "*"; OFDiv -> "/"; OFMod -> "%"
  cmpOp = \case
    OFLt -> "<"; OFLeq -> "<="; OFGt -> ">"; OFGeq -> ">="; OFEq -> "=="; OFNeq -> "!="

  roleArg  = maybe "" (\r -> ", role=" <> roleConst r)
  roleConst r = entPy <> "." <> Text.toUpper r

paren :: Text -> Text
paren t = "(" <> t <> ")"

-- ---------------------------------------------------------------------------
-- Literal / token rendering
-- ---------------------------------------------------------------------------

pyValueType :: OFType -> Text
pyValueType = \case
  OFFloat -> "float"; OFInt -> "int"; OFBool -> "bool"; OFStr -> "str"
  OFEnum _ _ -> "Enum"

pyPeriod :: OFPeriod -> Text
pyPeriod = \case
  OFMonth -> "MONTH"; OFYear -> "YEAR"; OFEternity -> "ETERNITY"

-- | A Python single-quoted string literal with minimal escaping.
pyStr :: Text -> Text
pyStr t = "'" <> Text.concatMap esc t <> "'"
 where
  esc '\\' = "\\\\"
  esc '\'' = "\\'"
  esc '\n' = "\\n"
  esc c    = Text.singleton c

-- | Render a rational as a clean Python numeric literal. Integers print bare;
-- fractions that terminate in base 10 print as decimals; anything else prints
-- as an exact division so no precision is silently lost.
renderNum :: Rational -> Text
renderNum r
  | d == 1    = sign <> tshow (abs n)
  | otherwise = case terminating (abs n) d of
      Just t  -> sign <> t
      Nothing -> "(" <> tshow n <> " / " <> tshow d <> ")"
 where
  n    = numerator r
  d    = denominator r
  sign = if n < 0 then "-" else ""

-- | If @num/den@ (den > 0, num >= 0) terminates in base 10, render it.
terminating :: Integer -> Integer -> Maybe Text
terminating num den =
  let places = countFactors 2 den `max` countFactors 5 den
  in if stripFactors 5 (stripFactors 2 den) == 1
       then Just (format places (num * (10 ^ places) `div` den))
       else Nothing
 where
  countFactors p x = go (0 :: Integer) x
    where go acc y | y `mod` p == 0 && y /= 0 = go (acc + 1) (y `div` p)
                   | otherwise               = acc
  stripFactors p x | x `mod` p == 0 && x /= 0 = stripFactors p (x `div` p)
                   | otherwise               = x
  format places scaled
    | places == 0 = tshow scaled
    | otherwise =
        let s         = Text.justifyRight (fromIntegral places + 1) '0' (tshow scaled)
            (whole, frac) = Text.splitAt (Text.length s - fromIntegral places) s
        in whole <> "." <> frac

tshow :: Show a => a -> Text
tshow = Text.pack . show

ind :: Int -> Text
ind n = Text.replicate (n * 4) " "
