---
config:
  railroad:
    nonTerminalFill: "#ffffff"
    nonTerminalStroke: "#222222"
    nonTerminalTextColor: "#111111"
    terminalFill: "transparent"
    terminalStroke: "transparent"
    terminalTextColor: "#888888"
    lineColor: "#8a8a8a"
    markerFill: "#222222"
    strokeWidth: 1.5
    fontSize: 15
---
railroad-beta
transfer_is_permitted = choice(nonterminal("NOT transfer is within the one-year restricted period OF transfer"), nonterminal("transfer falls within an exception in Rule 501(a) OF transfer"));
