<script lang="ts">
  import Outcome from './Outcome.svelte'
  import Disclosure from '../Disclosure.svelte'
  import { formatIso, lawTimeComparison, money } from '$lib/lawtime'
  import type { AppliedLawTime } from '$lib/lawtime'
  import type { InvestmentLimitAnswer } from '$lib/api/types'

  /**
   * The R8 card. Three numbers, three provenances, and the page never computes
   * any of them:
   *
   *   - `underRuleDate`  — the limit under the rules in force on the APPLIED
   *                        rule date, from the law-time export;
   *   - `underToday`     — the same export, asked again at today's date;
   *   - `now`            — the full, prose-carrying answer under the current
   *                        rules, from `investment limit check`.
   *
   * `now` is what carries the citations, and it is labelled as current-rules
   * reasoning throughout. It is NOT re-used to explain a pinned past date: the
   * corpus's prose for a past regime would have to be generated by the corpus,
   * and inventing it here is precisely the "second copy of the law" this design
   * refuses.
   */
  let {
    now,
    underRuleDate,
    underToday,
    applied,
    todayIsoDate,
    onRestart,
  }: {
    now: InvestmentLimitAnswer
    underRuleDate: number
    underToday: number
    applied: AppliedLawTime
    todayIsoDate: string
    onRestart: () => void
  } = $props()

  const noLimitNow = $derived(now['you have no limit'])
  const moved = $derived(underRuleDate !== underToday)
</script>

<Outcome
  tone="neither"
  word="Your 12-month limit"
  line={`${money(underRuleDate)} under the rules in force on ${formatIso(applied.ruleDate)}.`}
/>

<!-- Ruling R8 piece 2. Without this sentence the page presents ONE slider, and
     the fact-time / law-time distinction the exhibit rests on collapses. -->
<p class="because" class:pinned={applied.source === 'override'}>
  {applied.because}
</p>

<p class="compare" class:moved>
  {lawTimeComparison(
    underRuleDate,
    noLimitNow ? null : underToday,
    applied,
    formatIso(todayIsoDate)
  )}
</p>

<section class="now">
  <h2>Under the rules in force now</h2>
  {#if noLimitNow}
    <p class="lead">
      Regulation Crowdfunding sets no investment limit for an accredited
      investor.
    </p>
  {:else}
    <dl>
      <dt>Your 12-month limit</dt>
      <dd>{money(now['your 12 month limit'] ?? 0)}</dd>
      <dt>Already used</dt>
      <dd>{money(now['you have already used'])}</dd>
      <dt>Still available</dt>
      <dd>{money(now['you can still invest'] ?? 0)}</dd>
      <dt>Measured against</dt>
      <dd>{money(now['we measured against'])}</dd>
    </dl>
  {/if}
  <p class="citation">{now['which limb applies']}</p>
  <p class="working">{now['how this is worked out']}</p>
</section>

<Disclosure
  summary="Where this model is thinner than the law"
  count={now.caveats.length}
>
  <ul>
    {#each now.caveats as item (item)}
      <li>{item}</li>
    {/each}
  </ul>
</Disclosure>

<button type="button" class="linkish" onclick={onRestart}>
  Change my answers
</button>

<style>
  .because {
    font-weight: 700;
    margin: 0 0 0.6rem;
  }
  .because.pinned {
    color: var(--brand-dark);
  }
  .compare {
    margin: 0 0 1.4rem;
  }
  .compare.moved {
    border-left: 4px solid var(--brand);
    padding-left: 0.85rem;
    font-weight: 600;
  }
  .now {
    margin-bottom: 1.2rem;
  }
  h2 {
    font-size: 1.05rem;
    margin: 0 0 0.6rem;
  }
  dl {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 0.3rem 1rem;
    margin: 0 0 0.8rem;
  }
  dt {
    color: var(--muted);
  }
  dd {
    margin: 0;
    font-weight: 700;
  }
  .lead {
    font-weight: 700;
    margin: 0 0 0.5rem;
  }
  .citation {
    font-size: 0.95rem;
    margin: 0 0 0.4rem;
  }
  .working {
    margin: 0;
  }
</style>
