#!/usr/bin/env node
// Static stand-in for a compile: every module named in a .cabal on this branch
// must have a source file on this branch, and every new .hs file should be named
// by some .cabal (or GHC never builds it and -Wunused warnings hide).
//   cabalcheck.mjs <worktree>
import { readFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const wt = process.argv[2]
const git = (...a) => execFileSync('git', a, { encoding: 'utf8', cwd: wt, maxBuffer: 1 << 28 })

const CABALS = [
  ['jl4-core/jl4-core.cabal', 'jl4-core'],
  ['jl4/jl4.cabal', 'jl4'],
  ['jl4-lsp/jl4-lsp.cabal', 'jl4-lsp'],
  ['jl4-service/jl4-service.cabal', 'jl4-service'],
  ['jl4-mlir/jl4-mlir.cabal', 'jl4-mlir'],
  ['jl4-proleg/jl4-proleg.cabal', 'jl4-proleg'],
  ['jl4-query-plan/jl4-query-plan.cabal', 'jl4-query-plan'],
]
const SRC_DIRS = ['src', 'app', 'test', 'tests']

const missing = []
for (const [cabal, pkg] of CABALS) {
  const p = `${wt}/${cabal}`
  if (!existsSync(p)) continue
  const text = readFileSync(p, 'utf8')
  // module names sit alone on indented lines inside *-modules stanzas
  const mods = new Set()
  let inMods = false
  for (const raw of text.split('\n')) {
    const line = raw.replace(/--.*$/, '')
    if (/^\s*(exposed-modules|other-modules)\s*:/.test(line)) {
      inMods = true
      const tail = line.split(':')[1]?.trim()
      if (tail) tail.split(/[,\s]+/).filter(Boolean).forEach((m) => mods.add(m))
      continue
    }
    if (inMods) {
      const m = line.match(/^\s+([A-Z][\w.']*)\s*,?\s*$/)
      if (m) { mods.add(m[1]); continue }
      if (line.trim() === '') continue
      inMods = false
    }
  }
  for (const mod of mods) {
    if (mod.startsWith('Paths_')) continue // generated by cabal
    const rel = mod.replace(/\./g, '/') + '.hs'
    const found = SRC_DIRS.some((d) => existsSync(`${wt}/${pkg}/${d}/${rel}`))
    if (!found) missing.push(`${cabal}: names ${mod}, but no ${pkg}/{${SRC_DIRS}}/${rel}`)
  }
}

// the other direction: .hs files this branch adds that no .cabal mentions
const added = git('diff', '--cached', '--name-only', '--diff-filter=A', 'origin/main')
  .trim().split('\n').filter((f) => f.endsWith('.hs'))
const orphans = []
for (const f of added) {
  const m = f.match(/^([^/]+)\/(?:src|app|test|tests)\/(.+)\.hs$/)
  if (!m) continue
  const [, pkg, rest] = m
  const mod = rest.replace(/\//g, '.')
  const cabal = CABALS.find(([, p]) => p === pkg)?.[0]
  if (!cabal || !existsSync(`${wt}/${cabal}`)) continue
  const text = readFileSync(`${wt}/${cabal}`, 'utf8')
  if (!new RegExp(`(^|\\s)${mod.replace(/\./g, '\\.')}(\\s|,|$)`, 'm').test(text)) {
    if (!/Spec\.hs$|Main\.hs$/.test(f)) orphans.push(`${f} -> module ${mod} not named in ${cabal}`)
  }
}

if (missing.length) { console.log('MODULES NAMED BUT ABSENT:'); missing.forEach((x) => console.log('  ' + x)) }
if (orphans.length) { console.log('FILES ADDED BUT UNNAMED:'); orphans.forEach((x) => console.log('  ' + x)) }
if (!missing.length && !orphans.length) console.log('cabal/module consistency ok')
process.exit(missing.length ? 1 : 0)
