name: CI faster
on:
  push:
    branches:
      - main
      - 'mengwong/build**'
      - 'thomasgorissen/vscode-extension**'
  pull_request:
    branches: [main]

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-haskell:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ["9.6.7"]
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

    steps:
      - name: Update repositories
        run: sudo apt update
      - name: Install deps
        run: >
          sudo apt install -y
          git
          sudo
          software-properties-common
          build-essential
          curl
          libffi-dev
          libffi8
          libgmp-dev
          libgmp10
          libncurses-dev
          pkg-config
          zlib1g-dev
          liblzma-dev
          xz-utils
      - name: Update git config
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Update git submodules
        run: git submodule update --init

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: "latest"
          cabal-update: true
          enable-stack: false

      - name: Configure the build
        run: |
          cabal update
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            dist-newstyle
            ~/.cache/cabal
            ~/.cabal/packages
            ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-plan-${{ hashFiles('**/plan.json') }}

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all

      # - name: Build documentation
      #   run: cabal haddock all
