name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: VSCode ${{ matrix.node-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["20.x"]

        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
        working-directory: vscode/
      - run: npm run compile
        working-directory: vscode/
      - run: npm run lint
        working-directory: vscode/
      # - run: npm test
      #   working-directory: vscode/
